// Modus „aktivitaet" – Format: siehe ../README.md

import { masse } from '../geometrie.js';

// Knoten über ihren Mittelpunkt setzen – so liegen Pfeile ohne Rechnen senkrecht oder waagerecht.
const um = (k, cx, cy) => {
  const m = masse({ ...k, x: 0, y: 0 });
  return { ...k, x: cx - m.w / 2, y: cy - m.h / 2 };
};
const start = (id, cx, cy) => um({ id, typ: 'start' }, cx, cy);
const ende = (id, cx, cy, extra) => um({ id, typ: 'ende', ...extra }, cx, cy);
const aus = (id, cx, cy, extra) => um({ id, typ: 'ablaufende', ...extra }, cx, cy);
const akt = (id, cx, cy, text, w = 130, extra) => um({ id, typ: 'aktion', text, w, ...extra }, cx, cy);
const raute = (id, cx, cy, extra) => um({ id, typ: 'entscheidung', ...extra }, cx, cy);
const quer = (id, cx, cy, w, extra) => um({ id, typ: 'balken', w, h: 7, ...extra }, cx, cy);
const notiz = (id, x, y, text, anker = 'start') => ({ id, typ: 'text', x, y, text, anker, klein: true });
const f = (von, nach, extra) => ({ von, nach, typ: 'fluss', ...extra });

export const spickzettel = `- **Startknoten** (gefüllter Kreis) beginnt den Ablauf, **Endknoten** (Kreis mit Punkt) beendet die **ganze** Aktivität
- **Aktion** (Rechteck mit runden Ecken): Gegenstand + Verb, z. B. „Rechnung prüfen"
- **Entscheidung** (Raute): ein Pfeil rein, mehrere raus – jeder mit **[Bedingung]**, zusammen lückenlos und ohne Überschneidung
- **Zusammenführung** (Raute): mehrere alternative Pfeile rein, einer raus – wartet **nicht**
- **Teilung** (Balken): alle Zweige laufen gleichzeitig los; **Synchronisation** (Balken) wartet, bis **alle** Zweige angekommen sind
- **Wiederholung**: Rücksprung von einer Entscheidung über eine Zusammenführung vor die zu wiederholende Aktion
- **Ablaufende** (Kreis mit Kreuz) beendet nur **diesen** Zweig; **Schwimmbahnen** ordnen jede Aktion ihrem Beteiligten zu`;

// ---------- Notation ----------

const notationAblauf = {
  breite: 760,
  hoehe: 550,
  knoten: [
    start('s', 400, 26),
    raute('m1', 400, 80),
    akt('pruefen', 400, 140, 'Bestellung prüfen'),
    raute('d1', 400, 205),
    akt('nachfragen', 620, 205, 'Kunden nachfragen', 140),
    quer('teil', 400, 265, 480),
    akt('packen', 200, 325, 'Ware verpacken'),
    akt('rechnung', 400, 325, 'Rechnung erstellen'),
    akt('lager', 600, 325, 'Lager informieren'),
    aus('x', 600, 395),
    quer('sync', 300, 395, 280),
    akt('versand', 300, 455, 'Paket versenden'),
    ende('e', 300, 515),
    notiz('n1', 382, 26, 'Startknoten', 'end'),
    notiz('n2', 378, 80, 'Zusammenführung', 'end'),
    notiz('n3', 327, 140, 'Aktion', 'end'),
    notiz('n4', 378, 205, 'Entscheidung', 'end'),
    notiz('n5', 510, 66, 'Rücksprung = Wiederholung', 'middle'),
    notiz('n6', 150, 265, 'Teilung', 'end'),
    notiz('n7', 150, 395, 'Synchronisation', 'end'),
    notiz('n8', 620, 395, 'Ablaufende'),
    notiz('n9', 280, 515, 'Endknoten', 'end'),
  ],
  kanten: [
    f('s', 'm1'),
    f('m1', 'pruefen'),
    f('pruefen', 'd1'),
    f('d1', 'nachfragen', { text: '[unvollständig]' }),
    f('nachfragen', 'm1', { vonSeite: 'oben', via: [[620, 80]], nachSeite: 'rechts' }),
    f('d1', 'teil', { nachSeite: 'oben', text: '[vollständig]' }),
    f('teil', 'packen', { vonSeite: 'unten:-200', nachSeite: 'oben' }),
    f('teil', 'rechnung', { vonSeite: 'unten', nachSeite: 'oben' }),
    f('teil', 'lager', { vonSeite: 'unten:200', nachSeite: 'oben' }),
    f('lager', 'x'),
    f('packen', 'sync', { vonSeite: 'unten', nachSeite: 'oben:-100' }),
    f('rechnung', 'sync', { vonSeite: 'unten', nachSeite: 'oben:100' }),
    f('sync', 'versand', { vonSeite: 'unten', nachSeite: 'oben' }),
    f('versand', 'e'),
  ],
};

const notationBahnen = {
  breite: 720,
  hoehe: 290,
  rahmen: [{ typ: 'bahnen', x: 20, y: 10, h: 270, bahnen: [{ text: 'Kunde', w: 220 }, { text: 'Vertrieb', w: 220 }, { text: 'Lager', w: 220 }] }],
  knoten: [
    start('s', 130, 64),
    akt('aufgeben', 130, 120, 'Bestellung aufgeben', 150),
    akt('erfassen', 350, 120, 'Bestellung erfassen', 150),
    akt('versenden', 570, 120, 'Ware versenden', 150),
    akt('empfangen', 130, 195, 'Ware empfangen', 150),
    ende('e', 130, 252),
  ],
  kanten: [
    f('s', 'aufgeben'),
    f('aufgeben', 'erfassen'),
    f('erfassen', 'versenden'),
    f('versenden', 'empfangen', { vonSeite: 'unten', via: [[570, 195]], nachSeite: 'rechts' }),
    f('empfangen', 'e'),
  ],
};

export const notation = {
  text: 'So liest du das obere Diagramm: Die Bestellung wird geprüft. Ist sie **unvollständig**, fragt man beim Kunden nach und prüft **erneut** (Rücksprung). Ist sie **vollständig**, laufen Verpacken, Rechnung und Lagermeldung **gleichzeitig**. Versendet wird erst, wenn Verpacken **und** Rechnung fertig sind. Der Zweig „Lager informieren" endet für sich im Ablaufende. Im unteren Diagramm zeigen **Schwimmbahnen**, wer welche Aktion ausführt.',
  bilder: [
    { titel: 'Ablauf mit Entscheidung, Wiederholung und Parallelität', diagramm: notationAblauf },
    { titel: 'Schwimmbahnen', diagramm: notationBahnen },
  ],
  punkte: [
    'Jeder Pfeil aus einer **Entscheidung** trägt eine Bedingung in eckigen Klammern. Zusammen decken die Bedingungen **alle** Fälle ab und überschneiden sich nicht – z. B. [betrag >= 100] und [betrag < 100].',
    'Eine **Wiederholung** zeichnest du als Rücksprung in eine Zusammenführung **vor** der Aktion, die wiederholt wird – nicht direkt in die Aktion.',
    'Der **Teilungsbalken** startet alle Zweige gleichzeitig. Der **Synchronisationsbalken** wartet, bis alle ankommenden Zweige fertig sind. Eine Raute würde nicht warten.',
    '**Endknoten** (Kreis mit Punkt) beendet die ganze Aktivität, auch noch laufende Zweige. **Ablaufende** (Kreis mit Kreuz) beendet nur den eigenen Zweig.',
    'Mehrere Endknoten in einem Diagramm sind erlaubt – z. B. einer für „abgelehnt" und einer für „erledigt".',
    '**Schwimmbahnen** teilen das Diagramm nach Beteiligten. Jede Aktion liegt in der Bahn dessen, der sie ausführt; Pfeile dürfen Bahnen überqueren.',
  ],
};

// ---------- Aufgaben ----------

const OPT_SYMBOL = ['Teilung', 'Synchronisation', 'Entscheidung', 'Zusammenführung'];

export const aufgaben = [
  {
    id: 'ak-e1',
    art: 'ergaenzen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-3',
    titel: 'Störungsmeldung am Telefon',
    text: 'Der Service Desk nimmt eine Störung auf. Kann sie am Telefon gelöst werden, erklärt der Mitarbeiter dem Anwender die Lösung. Sonst beauftragt er einen Techniker. In beiden Fällen wird danach das Ticket geschlossen. Ergänze [1] bis [3].',
    diagramm: {
      breite: 620,
      hoehe: 430,
      knoten: [
        start('s', 300, 26),
        akt('aufnehmen', 300, 86, 'Störung aufnehmen', 150),
        raute('d', 300, 150),
        akt('erklaeren', 120, 215, 'Lösung erklären', 150),
        akt('techniker', 480, 215, 'Techniker beauftragen', 150),
        raute('m', 300, 280),
        notiz('n', 314, 302, '{2}'),
        akt('schliessen', 300, 340, '{3}', 150),
        ende('e', 300, 400),
      ],
      kanten: [
        f('s', 'aufnehmen'),
        f('aufnehmen', 'd'),
        f('d', 'erklaeren', { vonSeite: 'links', via: [[120, 150]], nachSeite: 'oben', text: '{1}' }),
        f('d', 'techniker', { vonSeite: 'rechts', via: [[480, 150]], nachSeite: 'oben', text: '[nicht telefonisch lösbar]', textPos: 0.45 }),
        f('erklaeren', 'm', { vonSeite: 'unten', via: [[120, 280]], nachSeite: 'links' }),
        f('techniker', 'm', { vonSeite: 'unten', via: [[480, 280]], nachSeite: 'rechts' }),
        f('m', 'schliessen'),
        f('schliessen', 'e'),
      ],
    },
    felder: [
      { id: '1', label: 'Bedingung am linken Zweig', optionen: ['[Ticket geschlossen]', '[telefonisch lösbar]', '[Techniker verfügbar]', 'keine Bedingung nötig'], erwartet: '[telefonisch lösbar]' },
      { id: '2', label: 'Was ist die Raute vor der letzten Aktion?', optionen: OPT_SYMBOL, erwartet: 'Zusammenführung' },
      { id: '3', label: 'Letzte Aktion', optionen: ['Störung aufnehmen', 'Techniker beauftragen', 'Ticket schließen', 'Ticketsystem'], erwartet: 'Ticket schließen' },
    ],
    loesung: [
      '[1] Jeder Pfeil aus einer Entscheidung braucht eine Bedingung. Die beiden Bedingungen müssen sich ergänzen: [telefonisch lösbar] und [nicht telefonisch lösbar] decken jeden Fall genau einmal ab.',
      '[2] Die untere Raute hat zwei Pfeile hinein und einen hinaus. Sie führt die beiden **alternativen** Wege wieder zusammen – das ist eine Zusammenführung.',
      '[3] Laut Text wird zum Schluss in beiden Fällen das Ticket geschlossen. „Störung aufnehmen" und „Techniker beauftragen" stehen schon weiter oben im Ablauf. „Ticketsystem" ist ein Gegenstand ohne Tätigkeit, also keine Aktion – Aktionen benennst du mit Gegenstand + Verb.',
    ],
  },
  {
    id: 'ak-e2',
    art: 'ergaenzen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-3',
    titel: 'Bezahlen an der Kantinenkasse',
    text: 'Der Gast legt seine Karte auf und gibt die PIN ein. Ist die PIN falsch, erscheint eine Fehlermeldung und er gibt sie erneut ein. Ist sie richtig, werden **gleichzeitig** der Betrag abgebucht und der Beleg gedruckt. Erst wenn **beides** erledigt ist, gibt die Kasse das Tablett frei. Ergänze die Lücken und beantworte die Frage.',
    diagramm: {
      breite: 620,
      hoehe: 590,
      knoten: [
        start('s', 260, 26),
        akt('karte', 260, 80, 'Karte auflegen'),
        raute('m', 260, 140),
        akt('pin', 260, 200, 'PIN eingeben'),
        raute('d', 260, 265),
        akt('fehler', 480, 265, 'Fehlermeldung anzeigen', 150),
        quer('teil', 260, 325, 300),
        notiz('n2', 100, 325, '{2}', 'end'),
        akt('abbuchen', 160, 385, 'Betrag abbuchen'),
        akt('beleg', 360, 385, 'Beleg drucken'),
        quer('sync', 260, 445, 300),
        notiz('n3', 100, 445, '{3}', 'end'),
        akt('frei', 260, 505, 'Tablett freigeben'),
        ende('e', 260, 562),
      ],
      kanten: [
        f('s', 'karte'),
        f('karte', 'm'),
        f('m', 'pin'),
        f('pin', 'd'),
        f('d', 'fehler', { text: '{1}' }),
        f('fehler', 'm', { vonSeite: 'oben', via: [[480, 140]], nachSeite: 'rechts' }),
        f('d', 'teil', { nachSeite: 'oben', text: '[PIN richtig]' }),
        f('teil', 'abbuchen', { vonSeite: 'unten:-100', nachSeite: 'oben' }),
        f('teil', 'beleg', { vonSeite: 'unten:100', nachSeite: 'oben' }),
        f('abbuchen', 'sync', { vonSeite: 'unten', nachSeite: 'oben:-100' }),
        f('beleg', 'sync', { vonSeite: 'unten', nachSeite: 'oben:100' }),
        f('sync', 'frei', { vonSeite: 'unten', nachSeite: 'oben' }),
        f('frei', 'e'),
      ],
    },
    felder: [
      { id: '1', label: 'Bedingung zur Fehlermeldung', optionen: ['[PIN falsch]', '[PIN eingegeben]', '[Karte aufgelegt]', '[Fehlermeldung]'], erwartet: '[PIN falsch]' },
      { id: '2', label: 'Balken nach der PIN-Prüfung', optionen: OPT_SYMBOL, erwartet: 'Teilung' },
      { id: '3', label: 'Balken vor „Tablett freigeben"', optionen: OPT_SYMBOL, erwartet: 'Synchronisation' },
      {
        id: 'a',
        label: 'Wann beginnt „Tablett freigeben"?',
        optionen: ['Sobald einer der beiden Zweige fertig ist', 'Erst wenn Abbuchen und Belegdruck beide fertig sind', 'Gleichzeitig mit dem Belegdruck', 'Direkt nach der PIN-Eingabe'],
        erwartet: 'Erst wenn Abbuchen und Belegdruck beide fertig sind',
      },
    ],
    loesung: [
      '[1] Die Bedingung beschreibt den Fall, in dem dieser Weg genommen wird. Gegenstück zu [PIN richtig] ist [PIN falsch] – zusammen lückenlos.',
      'Der Rücksprung von „Fehlermeldung anzeigen" führt in die Zusammenführung **vor** „PIN eingeben". So wird die Eingabe wiederholt.',
      '[2] Ein Balken mit einem Pfeil hinein und mehreren hinaus ist eine **Teilung**: Ab hier laufen die Zweige gleichzeitig.',
      '[3] Ein Balken mit mehreren Pfeilen hinein und einem hinaus ist eine **Synchronisation**: Er wartet, bis **alle** Zweige angekommen sind. Deshalb startet „Tablett freigeben" erst nach Abbuchen **und** Belegdruck.',
    ],
  },
  {
    id: 'ak-f1',
    art: 'fehler',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-3',
    titel: 'Urlaubsantrag mit Schwimmbahnen',
    text: 'Der Mitarbeiter stellt einen Urlaubsantrag. Der Vorgesetzte prüft ihn. Lehnt er ab, informiert **der Vorgesetzte** den Mitarbeiter, und der Ablauf endet. Genehmigt er, trägt die Personalabteilung den Urlaub ein und sendet eine Bestätigung. Prüfe die Stellen 1–4.',
    diagramm: {
      breite: 700,
      hoehe: 370,
      rahmen: [{ typ: 'bahnen', x: 20, y: 10, h: 350, bahnen: [{ text: 'Mitarbeiter', w: 220 }, { text: 'Vorgesetzter', w: 220 }, { text: 'Personalabteilung', w: 220 }] }],
      knoten: [
        start('s', 130, 64),
        akt('stellen', 130, 120, 'Urlaubsantrag stellen', 150),
        akt('pruefen', 350, 120, 'Antrag prüfen', 150),
        raute('d', 350, 190),
        akt('info', 130, 260, 'Mitarbeiter informieren', 150, { marke: 2 }),
        ende('e1', 130, 325),
        akt('eintragen', 570, 190, 'Urlaub eintragen', 150),
        akt('bestaetigen', 570, 260, 'Bestätigung senden', 150),
        ende('e2', 570, 325, { marke: 3 }),
      ],
      kanten: [
        f('s', 'stellen'),
        f('pruefen', 'stellen', { marke: 4 }),
        f('pruefen', 'd'),
        f('d', 'info', { vonSeite: 'links', via: [[130, 190]], nachSeite: 'oben', text: '[abgelehnt]', textPos: 0.3 }),
        f('d', 'eintragen', { text: '[Antrag geprüft]', marke: 1 }),
        f('info', 'e1'),
        f('eintragen', 'bestaetigen'),
        f('bestaetigen', 'e2'),
      ],
    },
    felder: [
      { id: '1', label: 'Bedingung [Antrag geprüft]', optionen: ['korrekt', 'falsch: muss [genehmigt] heißen', 'überflüssig: nur ein Zweig braucht eine Bedingung', 'muss ein Teilungsbalken sein'], erwartet: 'falsch: muss [genehmigt] heißen' },
      { id: '2', label: 'Aktion „Mitarbeiter informieren"', optionen: ['korrekt', 'liegt in der falschen Schwimmbahn', 'muss ein Endknoten sein', 'muss vor der Entscheidung stehen'], erwartet: 'liegt in der falschen Schwimmbahn' },
      { id: '3', label: 'Zweiter Endknoten in der Bahn Personalabteilung', optionen: ['korrekt', 'unzulässig: nur ein Endknoten pro Diagramm', 'muss ein Startknoten sein', 'muss in der Bahn Mitarbeiter liegen'], erwartet: 'korrekt' },
      { id: '4', label: 'Pfeil zwischen „Urlaubsantrag stellen" und „Antrag prüfen"', optionen: ['korrekt', 'Pfeilrichtung falsch', 'muss gestrichelt sein', 'muss eine Bedingung tragen'], erwartet: 'Pfeilrichtung falsch' },
    ],
    loesung: [
      '[1] Die Bedingungen einer Entscheidung müssen sich gegenseitig ausschließen und alle Fälle abdecken. Geprüft ist der Antrag in **beiden** Fällen – Gegenstück zu [abgelehnt] ist [genehmigt].',
      '[2] Eine Aktion gehört in die Bahn dessen, der sie **ausführt**. Den Mitarbeiter informiert der Vorgesetzte – also Bahn „Vorgesetzter".',
      '[3] Richtig: Ein Diagramm darf mehrere Endknoten haben. Hier endet jeder der beiden Wege für sich.',
      '[4] Der Kontrollfluss zeigt in Ablaufrichtung: Erst wird der Antrag gestellt, dann geprüft. Der Pfeil muss also auf „Antrag prüfen" zeigen.',
    ],
    muster: {
      breite: 700,
      hoehe: 370,
      rahmen: [{ typ: 'bahnen', x: 20, y: 10, h: 350, bahnen: [{ text: 'Mitarbeiter', w: 220 }, { text: 'Vorgesetzter', w: 220 }, { text: 'Personalabteilung', w: 220 }] }],
      knoten: [
        start('s', 130, 64),
        akt('stellen', 130, 120, 'Urlaubsantrag stellen', 150),
        akt('pruefen', 350, 120, 'Antrag prüfen', 150),
        raute('d', 350, 190),
        akt('info', 350, 260, 'Mitarbeiter informieren', 150, { hervor: true }),
        ende('e1', 350, 325),
        akt('eintragen', 570, 190, 'Urlaub eintragen', 150),
        akt('bestaetigen', 570, 260, 'Bestätigung senden', 150),
        ende('e2', 570, 325),
      ],
      kanten: [
        f('s', 'stellen'),
        f('stellen', 'pruefen', { hervor: true }),
        f('pruefen', 'd'),
        f('d', 'info', { text: '[abgelehnt]' }),
        f('d', 'eintragen', { text: '[genehmigt]', hervor: true }),
        f('info', 'e1'),
        f('eintragen', 'bestaetigen'),
        f('bestaetigen', 'e2'),
      ],
    },
  },
  {
    id: 'ak-q1',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-3',
    titel: 'Symbole und Bedingungen',
    text: 'Beantworte die Fragen zu den Grundregeln des Aktivitätsdiagramms.',
    felder: [
      {
        id: 'a',
        label: 'Eine Entscheidung prüft das Alter. Welches Bedingungspaar ist richtig?',
        optionen: ['[alter > 18] und [alter < 18]', '[alter >= 18] und [alter <= 18]', '[alter >= 18] und [alter < 18]', '[volljährig] und [alter < 21]'],
        erwartet: '[alter >= 18] und [alter < 18]',
      },
      {
        id: 'b',
        label: 'Was stellt ein Rücksprung von einer Entscheidung zu einer früheren Stelle dar?',
        optionen: ['eine parallele Ausführung', 'eine Wiederholung (Schleife)', 'das Ende der Aktivität', 'einen Fehler im Diagramm'],
        erwartet: 'eine Wiederholung (Schleife)',
      },
      {
        id: 'c',
        label: 'Ein Balken hat einen Pfeil hinein und drei Pfeile hinaus. Was bedeutet das?',
        optionen: ['Genau einer der drei Zweige wird ausgeführt.', 'Die drei Zweige laufen nacheinander von links nach rechts.', 'Der Ablauf wartet auf drei Ereignisse.', 'Die drei Zweige laufen gleichzeitig los (Teilung).'],
        erwartet: 'Die drei Zweige laufen gleichzeitig los (Teilung).',
      },
      {
        id: 'd',
        label: 'Womit führst du zwei alternative Zweige nach einer Entscheidung wieder zusammen?',
        optionen: ['mit einer Raute (Zusammenführung)', 'mit einem Synchronisationsbalken', 'mit einem Endknoten', 'mit einem zweiten Startknoten'],
        erwartet: 'mit einer Raute (Zusammenführung)',
      },
      {
        id: 'e',
        label: 'Wie benennst du eine Aktion?',
        optionen: ['nur mit einem Substantiv, z. B. „Rechnung"', 'mit Gegenstand + Verb, z. B. „Rechnung prüfen"', 'mit dem Beteiligten, z. B. „Buchhaltung"', 'mit einer Bedingung, z. B. „[Rechnung ok]"'],
        erwartet: 'mit Gegenstand + Verb, z. B. „Rechnung prüfen"',
      },
    ],
    loesung: [
      '(a) Bedingungen müssen **lückenlos** und **überschneidungsfrei** sein. Bei > und < fehlt genau 18; bei >= und <= trifft 18 beide Zweige; [volljährig] und [alter < 21] treffen bei 18 bis 20 Jahren beide zu. Nur >= 18 / < 18 passt.',
      '(b) Führt ein Pfeil zurück vor eine frühere Aktion, wird dieser Teil erneut durchlaufen – eine Schleife.',
      '(c) Ein Balken mit mehreren Ausgängen ist eine Teilung: Alle Zweige starten gleichzeitig. Bei einer Raute würde nur **ein** Zweig genommen.',
      '(d) Nach einer Entscheidung kommt nur **ein** Zweig an. Ein Synchronisationsbalken würde auf alle warten und nie weiterlaufen – deshalb die Zusammenführungsraute.',
      '(e) Eine Aktion ist eine Tätigkeit: Gegenstand + Verb. Wer sie ausführt, zeigt die Schwimmbahn; Bedingungen stehen an den Pfeilen.',
    ],
  },
  {
    id: 'ak-e3',
    art: 'ergaenzen',
    raum: ['AP2'],
    sp: 'AP2-2-1-3',
    titel: 'Deployment mit Schwimmbahnen',
    text: 'Ein Entwickler pusht seinen Code. Der CI-Server baut die Anwendung und führt danach Unit-Tests und eine Code-Analyse **parallel** aus. Sind **beide** Prüfungen bestanden, spielt der Betrieb die Anwendung auf den Testserver ein, und der Ablauf endet. Ist mindestens eine Prüfung fehlgeschlagen, behebt der Entwickler den Fehler und pusht erneut. Ergänze die Lücken.',
    diagramm: {
      breite: 800,
      hoehe: 500,
      rahmen: [{ typ: 'bahnen', x: 20, y: 10, h: 480, bahnen: [{ text: 'Entwickler', w: 190 }, { text: 'CI-Server', w: 360 }, { text: 'Betrieb', w: 210 }] }],
      knoten: [
        start('s', 115, 64),
        raute('m', 115, 115),
        akt('push', 115, 170, 'Code pushen', 120),
        akt('bauen', 390, 170, 'Anwendung bauen'),
        quer('teil', 390, 225, 260),
        akt('tests', 300, 285, 'Unit-Tests ausführen', 165),
        akt('analyse', 480, 285, '{2}', 165),
        quer('sync', 390, 345, 260),
        raute('d', 390, 405),
        akt('fix', 115, 405, 'Fehler beheben', 120),
        akt('deploy', 675, 405, '{3}', 190),
        ende('e', 675, 462),
      ],
      kanten: [
        f('s', 'm'),
        f('m', 'push'),
        f('push', 'bauen'),
        f('bauen', 'teil', { nachSeite: 'oben' }),
        f('teil', 'tests', { vonSeite: 'unten:-90', nachSeite: 'oben' }),
        f('teil', 'analyse', { vonSeite: 'unten:90', nachSeite: 'oben' }),
        f('tests', 'sync', { vonSeite: 'unten', nachSeite: 'oben:-90' }),
        f('analyse', 'sync', { vonSeite: 'unten', nachSeite: 'oben:90' }),
        f('sync', 'd', { vonSeite: 'unten' }),
        f('d', 'deploy', { text: '[beide bestanden]' }),
        f('d', 'fix', { text: '{1}' }),
        f('fix', 'm', { vonSeite: 'unten', via: [[115, 455], [35, 455], [35, 115]], nachSeite: 'links' }),
        f('deploy', 'e'),
      ],
    },
    felder: [
      { id: '1', label: 'Bedingung zu „Fehler beheben"', optionen: ['[beide fehlgeschlagen]', '[Unit-Tests fehlgeschlagen]', '[mind. eine fehlgeschlagen]', '[Code gepusht]'], erwartet: '[mind. eine fehlgeschlagen]' },
      { id: '2', label: 'Zweite parallele Aktion', optionen: ['Fehler beheben', 'Code-Analyse ausführen', 'Code pushen', 'Auf Testserver einspielen'], erwartet: 'Code-Analyse ausführen' },
      { id: '3', label: 'Aktion in der Bahn „Betrieb"', optionen: ['Anwendung bauen', 'Unit-Tests ausführen', 'Fehler beheben', 'Auf Testserver einspielen'], erwartet: 'Auf Testserver einspielen' },
      {
        id: 'a',
        label: 'Die Unit-Tests sind fertig, die Code-Analyse läuft noch. Was passiert?',
        optionen: ['Die Entscheidung fällt sofort mit dem Testergebnis.', 'Die Code-Analyse wird abgebrochen.', 'Der Ablauf wartet am Synchronisationsbalken auf die Code-Analyse.', 'Der Ablauf endet.'],
        erwartet: 'Der Ablauf wartet am Synchronisationsbalken auf die Code-Analyse.',
      },
    ],
    loesung: [
      '[1] Gegenstück zu [beide bestanden] ist [mind. eine fehlgeschlagen]. [beide fehlgeschlagen] oder [Unit-Tests fehlgeschlagen] lassen Fälle offen (z. B. nur die Analyse schlägt fehl) – dann ginge es nirgends weiter.',
      '[2] Laut Text laufen Unit-Tests und Code-Analyse parallel – also stehen beide zwischen Teilung und Synchronisation in der Bahn des CI-Servers.',
      '[3] Die Bahn zeigt, **wer** eine Aktion ausführt: Das Einspielen auf den Testserver übernimmt der Betrieb.',
      '(a) Die Synchronisation wartet, bis **alle** eingehenden Zweige angekommen sind. Erst dann wird entschieden.',
      'Der Rücksprung von „Fehler beheben" führt in die Zusammenführung vor „Code pushen" – so beginnt der Durchlauf von vorn.',
    ],
  },
  {
    id: 'ak-f2',
    art: 'fehler',
    raum: ['AP2'],
    sp: 'AP2-2-1-3',
    titel: 'Fehler in der Bestellabwicklung',
    text: 'Ablauf im Webshop: Nach dem Erfassen wird geprüft, ob die Ware vorrätig ist. Wenn nicht, wird storniert, und der Ablauf endet. Sonst laufen „Rechnung erstellen" und „Ware kommissionieren" **parallel**; zusätzlich wird parallel eine Info-Mail gesendet, die den restlichen Ablauf **nicht** beeinflussen soll. Sind Rechnung **und** Ware fertig, wird ab einem Bestellwert von **100 €** versandkostenfrei verschickt, darunter mit Versandkosten. Danach wird das Paket versendet. Prüfe die Stellen 1–4.',
    diagramm: {
      breite: 620,
      hoehe: 650,
      knoten: [
        start('s', 350, 26),
        akt('erfassen', 350, 80, 'Bestellung erfassen', 150),
        raute('d1', 350, 140),
        akt('storno', 120, 140, 'Bestellung stornieren', 150),
        ende('e1', 120, 205),
        quer('teil', 350, 200, 380),
        akt('rechnung', 200, 260, 'Rechnung erstellen'),
        akt('ware', 350, 260, 'Ware kommissionieren'),
        akt('mail', 500, 260, 'Info-Mail senden'),
        ende('e2', 500, 325, { marke: 2 }),
        raute('m1', 275, 325, { marke: 1 }),
        raute('d2', 275, 385),
        akt('kosten', 110, 445, 'Versandkosten berechnen', 150),
        akt('frei', 440, 445, 'Versandkostenfrei buchen', 150),
        raute('m2', 275, 505, { marke: 4 }),
        akt('versand', 275, 565, 'Paket versenden'),
        ende('e3', 275, 622),
      ],
      kanten: [
        f('s', 'erfassen'),
        f('erfassen', 'd1'),
        f('d1', 'storno', { text: '[nicht vorrätig]' }),
        f('storno', 'e1'),
        f('d1', 'teil', { nachSeite: 'oben', text: '[vorrätig]' }),
        f('teil', 'rechnung', { vonSeite: 'unten:-150', nachSeite: 'oben' }),
        f('teil', 'ware', { vonSeite: 'unten', nachSeite: 'oben' }),
        f('teil', 'mail', { vonSeite: 'unten:150', nachSeite: 'oben' }),
        f('mail', 'e2'),
        f('rechnung', 'm1', { vonSeite: 'unten', via: [[200, 325]], nachSeite: 'links' }),
        f('ware', 'm1', { vonSeite: 'unten', via: [[350, 325]], nachSeite: 'rechts' }),
        f('m1', 'd2'),
        f('d2', 'kosten', { vonSeite: 'links', via: [[110, 385]], nachSeite: 'oben', text: '[bestellwert < 100 €]', textPos: 0.42 }),
        f('d2', 'frei', { vonSeite: 'rechts', via: [[440, 385]], nachSeite: 'oben', text: '[bestellwert > 100 €]', textPos: 0.42, marke: 3 }),
        f('kosten', 'm2', { vonSeite: 'unten', via: [[110, 505]], nachSeite: 'links' }),
        f('frei', 'm2', { vonSeite: 'unten', via: [[440, 505]], nachSeite: 'rechts' }),
        f('m2', 'versand'),
        f('versand', 'e3'),
      ],
    },
    felder: [
      { id: '1', label: 'Raute nach „Rechnung erstellen" und „Ware kommissionieren"', optionen: ['korrekt', 'muss ein Synchronisationsbalken sein', 'muss ein Endknoten sein', 'braucht Bedingungen an den eingehenden Pfeilen'], erwartet: 'muss ein Synchronisationsbalken sein' },
      { id: '2', label: 'Endknoten nach „Info-Mail senden"', optionen: ['korrekt', 'muss ein Ablaufende sein', 'muss in die Raute bei Stelle 1 führen', 'muss ein Startknoten sein'], erwartet: 'muss ein Ablaufende sein' },
      { id: '3', label: 'Bedingung [bestellwert > 100 €]', optionen: ['korrekt', 'Überschneidung mit der linken Bedingung', 'Lücke bei genau 100 € – richtig: [bestellwert >= 100 €]', 'Bedingungen gehören in die Raute'], erwartet: 'Lücke bei genau 100 € – richtig: [bestellwert >= 100 €]' },
      { id: '4', label: 'Raute vor „Paket versenden"', optionen: ['korrekt', 'muss ein Synchronisationsbalken sein', 'muss eine Entscheidung mit Bedingungen sein', 'muss ein Teilungsbalken sein'], erwartet: 'korrekt' },
    ],
    loesung: [
      '[1] Rechnung und Ware laufen **parallel**. Weiter geht es erst, wenn **beide** fertig sind – das leistet nur ein Synchronisationsbalken. Eine Raute wartet nicht, der Ablauf liefe doppelt weiter.',
      '[2] Ein Endknoten beendet die **ganze** Aktivität. Ist die Mail schnell verschickt, würden Rechnung und Kommissionierung abgebrochen. Das Ablaufende beendet nur den Mail-Zweig. In die Zusammenführung bei Stelle 1 darf der Mail-Zweig auch nicht: Dann hinge der weitere Ablauf von der Mail ab – laut Text soll sie ihn nicht beeinflussen.',
      '[3] Mit < 100 und > 100 passt bei genau 100 € keine Bedingung. Laut Text gilt „ab 100 €" versandkostenfrei – also [bestellwert >= 100 €].',
      '[4] Richtig: Nach der Entscheidung kommt nur **ein** Weg an, die Zusammenführung führt ihn weiter. Ein Synchronisationsbalken würde auf **beide** Wege warten – es kommt aber nur einer, der Ablauf bliebe stehen. Eine Entscheidung oder Teilung passt nicht, weil hier zwei Pfeile hinein- und nur einer hinausgehen.',
    ],
    muster: {
      breite: 620,
      hoehe: 650,
      knoten: [
        start('s', 350, 26),
        akt('erfassen', 350, 80, 'Bestellung erfassen', 150),
        raute('d1', 350, 140),
        akt('storno', 120, 140, 'Bestellung stornieren', 150),
        ende('e1', 120, 205),
        quer('teil', 350, 200, 380),
        akt('rechnung', 200, 260, 'Rechnung erstellen'),
        akt('ware', 350, 260, 'Ware kommissionieren'),
        akt('mail', 500, 260, 'Info-Mail senden'),
        aus('e2', 500, 325, { hervor: true }),
        quer('sync', 275, 325, 220, { hervor: true }),
        raute('d2', 275, 385),
        akt('kosten', 110, 445, 'Versandkosten berechnen', 150),
        akt('frei', 440, 445, 'Versandkostenfrei buchen', 150),
        raute('m2', 275, 505),
        akt('versand', 275, 565, 'Paket versenden'),
        ende('e3', 275, 622),
      ],
      kanten: [
        f('s', 'erfassen'),
        f('erfassen', 'd1'),
        f('d1', 'storno', { text: '[nicht vorrätig]' }),
        f('storno', 'e1'),
        f('d1', 'teil', { nachSeite: 'oben', text: '[vorrätig]' }),
        f('teil', 'rechnung', { vonSeite: 'unten:-150', nachSeite: 'oben' }),
        f('teil', 'ware', { vonSeite: 'unten', nachSeite: 'oben' }),
        f('teil', 'mail', { vonSeite: 'unten:150', nachSeite: 'oben' }),
        f('mail', 'e2'),
        f('rechnung', 'sync', { vonSeite: 'unten', nachSeite: 'oben:-75' }),
        f('ware', 'sync', { vonSeite: 'unten', nachSeite: 'oben:75' }),
        f('sync', 'd2', { vonSeite: 'unten' }),
        f('d2', 'kosten', { vonSeite: 'links', via: [[110, 385]], nachSeite: 'oben', text: '[bestellwert < 100 €]', textPos: 0.42 }),
        f('d2', 'frei', { vonSeite: 'rechts', via: [[440, 385]], nachSeite: 'oben', text: '[bestellwert >= 100 €]', textPos: 0.42, hervor: true }),
        f('kosten', 'm2', { vonSeite: 'unten', via: [[110, 505]], nachSeite: 'links' }),
        f('frei', 'm2', { vonSeite: 'unten', via: [[440, 505]], nachSeite: 'rechts' }),
        f('m2', 'versand'),
        f('versand', 'e3'),
      ],
    },
  },
  {
    id: 'ak-e4',
    art: 'ergaenzen',
    raum: ['AP2'],
    sp: 'AP2-2-1-3',
    titel: 'Algorithmus: Maximum suchen',
    text: 'Der Pseudocode sucht den größten Wert in einem Array `werte` mit `n` Elementen. Das Aktivitätsdiagramm bildet ihn ab. Ergänze die Lücken und beantworte die Frage.',
    tabelle: {
      kopf: ['Zeile', 'Pseudocode'],
      zeilen: [
        ['1', 'max = werte[0]'],
        ['2', 'i = 1'],
        ['3', 'solange i < n'],
        ['4', '    wenn werte[i] > max'],
        ['5', '        max = werte[i]'],
        ['6', '    i = i + 1'],
        ['7', 'gib max zurück'],
      ],
    },
    diagramm: {
      breite: 620,
      hoehe: 560,
      knoten: [
        start('s', 260, 26),
        akt('a1', 260, 80, 'max = werte[0]'),
        akt('a2', 260, 140, 'i = 1'),
        raute('m1', 260, 200),
        raute('d1', 260, 255),
        raute('d2', 260, 320),
        akt('a5', 260, 385, 'max = werte[i]'),
        raute('m2', 260, 445),
        akt('a6', 260, 505, '{3}'),
        akt('a7', 520, 255, 'max zurückgeben'),
        ende('e', 520, 320),
      ],
      kanten: [
        f('s', 'a1'),
        f('a1', 'a2'),
        f('a2', 'm1'),
        f('m1', 'd1'),
        f('d1', 'd2', { text: '[i < n]' }),
        f('d1', 'a7', { text: '{1}' }),
        f('d2', 'a5', { text: '[werte[i] > max]' }),
        f('d2', 'm2', { vonSeite: 'rechts', via: [[400, 320], [400, 445]], nachSeite: 'rechts', text: '{2}', textPos: 0.25 }),
        f('a5', 'm2'),
        f('m2', 'a6'),
        f('a6', 'm1', { vonSeite: 'links', via: [[100, 505], [100, 200]], nachSeite: 'links' }),
        f('a7', 'e'),
      ],
    },
    felder: [
      { id: '1', label: 'Bedingung zum Schleifenende', optionen: ['[i > n]', '[i >= n]', '[i <= n]', '[i = n + 1]'], erwartet: '[i >= n]' },
      { id: '2', label: 'Bedingung, wenn kein neues Maximum gefunden wurde', optionen: ['[werte[i] < max]', '[werte[i] >= max]', '[werte[i] <= max]', '[i >= n]'], erwartet: '[werte[i] <= max]' },
      { id: '3', label: 'Aktion vor dem Rücksprung', optionen: ['max = werte[i]', 'i = 1', 'i = i + 1', 'max zurückgeben'], erwartet: 'i = i + 1' },
      {
        id: 'a',
        label: 'Welche Zeile des Pseudocodes bildet der Rücksprung nach oben ab?',
        optionen: ['Zeile 1: max = werte[0]', 'Zeile 3: solange i < n', 'Zeile 4: wenn werte[i] > max', 'Zeile 7: gib max zurück'],
        erwartet: 'Zeile 3: solange i < n',
      },
    ],
    loesung: [
      '[1] Die Schleife läuft, solange [i < n] gilt. Das genaue Gegenteil ist [i >= n]. Mit [i > n] oder [i = n + 1] bliebe der Ablauf bei i = n hängen.',
      '[2] Gegenstück zu [werte[i] > max] ist [werte[i] <= max]. Mit < fehlt der Fall „gleich", mit >= würde „gleich" in beide Zweige passen.',
      '[3] Zeile 6 erhöht den Zähler am Ende **jedes** Durchlaufs – nach der Zusammenführung, also in beiden Fällen der inneren Verzweigung.',
      '(a) Eine kopfgesteuerte Schleife (solange) wird zu: Zusammenführung → Entscheidung mit Bedingung → Schleifenrumpf → Rücksprung in die Zusammenführung.',
      'Die innere wenn-Anweisung ohne sonst-Zweig wird zu einer Entscheidung, deren zweiter Pfeil die Aktion überspringt und in eine Zusammenführung läuft.',
    ],
  },
  {
    id: 'ak-q2',
    art: 'fragen',
    raum: ['AP2'],
    sp: 'AP2-2-1-3',
    titel: 'Endknoten oder Ablaufende?',
    text: 'Nach dem Hochladen eines Videos laufen zwei Zweige parallel. Beantworte die Fragen zum Diagramm.',
    diagramm: {
      breite: 500,
      hoehe: 350,
      knoten: [
        start('s', 250, 26),
        akt('hoch', 250, 80, 'Video hochladen'),
        quer('teil', 250, 135, 300),
        akt('umwandeln', 160, 195, 'Video umwandeln', 150),
        akt('veroeff', 160, 260, 'Video veröffentlichen', 150),
        ende('e', 160, 322),
        akt('vorschau', 340, 195, 'Vorschaubild erzeugen', 150),
        aus('x', 340, 260),
      ],
      kanten: [
        f('s', 'hoch'),
        f('hoch', 'teil', { nachSeite: 'oben' }),
        f('teil', 'umwandeln', { vonSeite: 'unten:-90', nachSeite: 'oben' }),
        f('teil', 'vorschau', { vonSeite: 'unten:90', nachSeite: 'oben' }),
        f('umwandeln', 'veroeff'),
        f('veroeff', 'e'),
        f('vorschau', 'x'),
      ],
    },
    felder: [
      {
        id: 'a',
        label: 'Das Vorschaubild ist fertig, das Umwandeln läuft noch. Was passiert?',
        optionen: ['Die ganze Aktivität endet sofort.', 'Nur der Zweig „Vorschaubild" endet, das Umwandeln läuft weiter.', 'Das Umwandeln wird abgebrochen.', 'Das Vorschaubild wird erneut erzeugt.'],
        erwartet: 'Nur der Zweig „Vorschaubild" endet, das Umwandeln läuft weiter.',
      },
      {
        id: 'b',
        label: 'Das Video ist veröffentlicht, das Vorschaubild wird noch erzeugt. Was passiert am Endknoten?',
        optionen: ['Nur der linke Zweig endet, das Vorschaubild wird fertig erzeugt.', 'Der Endknoten wartet auf das Vorschaubild.', 'Die ganze Aktivität endet – auch das Erzeugen des Vorschaubilds wird abgebrochen.', 'Das Video wird erneut veröffentlicht.'],
        erwartet: 'Die ganze Aktivität endet – auch das Erzeugen des Vorschaubilds wird abgebrochen.',
      },
      {
        id: 'c',
        label: 'Das Vorschaubild soll sicher vor dem Veröffentlichen fertig sein. Wie änderst du das Diagramm?',
        optionen: [
          'Beide Zweige vor „Video veröffentlichen" mit einem Synchronisationsbalken zusammenführen.',
          'Das Ablaufende durch einen Endknoten ersetzen.',
          'Beide Zweige vor „Video veröffentlichen" mit einer Raute zusammenführen.',
          'Den Teilungsbalken durch eine Entscheidung ersetzen.',
        ],
        erwartet: 'Beide Zweige vor „Video veröffentlichen" mit einem Synchronisationsbalken zusammenführen.',
      },
      { id: 'd', label: 'Wie sieht das Ablaufende aus?', optionen: ['gefüllter Kreis', 'Kreis mit Punkt darin', 'Kreis mit Kreuz darin', 'Raute'], erwartet: 'Kreis mit Kreuz darin' },
    ],
    loesung: [
      '(a) Das Ablaufende beendet nur den Fluss, der dort ankommt. Andere Zweige laufen weiter.',
      '(b) Der Endknoten beendet die **gesamte** Aktivität – alle noch laufenden Zweige werden abgebrochen. Ist das Vorschaubild dann noch nicht fertig, fehlt es – so ein Diagramm nimmt das in Kauf. Soll es sicher fertig werden, brauchst du eine Synchronisation (siehe c).',
      '(c) Nur der Synchronisationsbalken wartet auf **alle** Zweige. Eine Raute würde nicht warten, sondern „Video veröffentlichen" zweimal anstoßen; eine Entscheidung würde nur einen Zweig ausführen.',
      '(d) Gefüllter Kreis = Startknoten, Kreis mit Punkt = Endknoten, Kreis mit Kreuz = Ablaufende.',
    ],
  },

  // ---------- Zeichnen ----------
  {
    id: 'ak-z1',
    art: 'zeichnen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-3',
    titel: 'Rücksendung im Onlineshop',
    text: 'Zeichne ein Aktivitätsdiagramm mit den Schwimmbahnen **Kunde** und **Lager**:\n- Der Kunde meldet die Rücksendung online an und schickt das Paket ab.\n- Das Lager prüft die Ware.\n- Ist die Ware in Ordnung, werden **gleichzeitig** der Kaufpreis erstattet und die Ware eingelagert.\n- Ist die Ware beschädigt, lehnt das Lager die Rücksendung ab.\n- In beiden Fällen informiert das Lager danach den Kunden. Dann endet der Ablauf.',
    muster: {
      breite: 750,
      hoehe: 640,
      rahmen: [{ typ: 'bahnen', x: 20, y: 10, h: 620, bahnen: [{ text: 'Kunde', w: 220 }, { text: 'Lager', w: 490 }] }],
      knoten: [
        start('s', 130, 64),
        akt('anmelden', 130, 120, 'Rücksendung anmelden', 164),
        akt('abschicken', 130, 185, 'Paket abschicken', 164),
        akt('pruefen', 420, 185, 'Ware prüfen'),
        raute('d', 420, 250),
        akt('ablehnen', 650, 250, 'Rücksendung ablehnen'),
        quer('teil', 420, 305, 240),
        akt('erstatten', 340, 360, 'Kaufpreis erstatten'),
        akt('einlagern', 500, 360, 'Ware einlagern'),
        quer('sync', 420, 415, 240),
        raute('m', 420, 470),
        akt('info', 420, 530, 'Kunden informieren'),
        ende('e', 420, 592),
      ],
      kanten: [
        f('s', 'anmelden'),
        f('anmelden', 'abschicken'),
        f('abschicken', 'pruefen'),
        f('pruefen', 'd'),
        f('d', 'ablehnen', { text: '[Ware beschädigt]' }),
        f('d', 'teil', { nachSeite: 'oben', text: '[Ware in Ordnung]' }),
        f('teil', 'erstatten', { vonSeite: 'unten:-80', nachSeite: 'oben' }),
        f('teil', 'einlagern', { vonSeite: 'unten:80', nachSeite: 'oben' }),
        f('erstatten', 'sync', { vonSeite: 'unten', nachSeite: 'oben:-80' }),
        f('einlagern', 'sync', { vonSeite: 'unten', nachSeite: 'oben:80' }),
        f('sync', 'm', { vonSeite: 'unten' }),
        f('ablehnen', 'm', { vonSeite: 'unten', via: [[650, 470]], nachSeite: 'rechts' }),
        f('m', 'info'),
        f('info', 'e'),
      ],
    },
    pruefliste: [
      'Zwei **Schwimmbahnen** Kunde und Lager; jede Aktion liegt in der Bahn dessen, der sie ausführt',
      '**Startknoten** in der Bahn Kunde, danach „Rücksendung anmelden" → „Paket abschicken" → „Ware prüfen"',
      '**Entscheidung** nach „Ware prüfen" mit **[Ware in Ordnung]** und **[Ware beschädigt]**',
      '**Teilungsbalken** vor „Kaufpreis erstatten" und „Ware einlagern", **Synchronisationsbalken** danach',
      '**Zusammenführung** (Raute) vor „Kunden informieren" – beide Fälle laufen dort zusammen',
      '**Endknoten** nach „Kunden informieren"',
      'Alle Kanten als Pfeile in Ablaufrichtung, Aktionen als Gegenstand + Verb',
    ],
    hinweise: 'Führe die beiden Fälle **nicht** direkt in „Kunden informieren": Zwei eingehende Pfeile an einer Aktion bedeuten in UML, dass auf **beide** gewartet wird – es kommt aber nur einer. Ein Synchronisationsbalken an dieser Stelle wäre aus demselben Grund falsch.',
  },
  {
    id: 'ak-z2',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-1-3',
    titel: 'Störungsbearbeitung mit drei Bahnen',
    text: 'Zeichne den Ablauf mit den Schwimmbahnen **Anwender**, **Service Desk** und **Techniker**:\n- Der Anwender meldet eine Störung. Der Service Desk erfasst ein Ticket.\n- Gibt es eine bekannte Lösung, teilt der Service Desk sie dem Anwender mit.\n- Sonst analysiert der Techniker die Störung und behebt sie.\n- Danach testet der Anwender die Lösung. Funktioniert es nicht, analysiert der Techniker die Störung erneut.\n- Funktioniert es, schließt der Service Desk das Ticket, und **gleichzeitig** dokumentiert der Techniker die Lösung. Sind beide Schritte erledigt, endet der Ablauf.',
    muster: {
      breite: 700,
      hoehe: 700,
      rahmen: [{ typ: 'bahnen', x: 20, y: 10, h: 680, bahnen: [{ text: 'Anwender', w: 200 }, { text: 'Service Desk', w: 220 }, { text: 'Techniker', w: 240 }] }],
      knoten: [
        start('s', 120, 64),
        akt('melden', 120, 120, 'Störung melden'),
        akt('erfassen', 330, 120, 'Ticket erfassen'),
        raute('d1', 330, 180),
        akt('mitteilen', 330, 245, 'Lösung mitteilen'),
        raute('m1', 560, 180),
        akt('analyse', 560, 245, 'Störung analysieren'),
        akt('beheben', 560, 310, 'Störung beheben'),
        raute('m2', 330, 375),
        akt('testen', 120, 375, 'Lösung testen'),
        raute('d2', 120, 440),
        quer('teil', 340, 500, 460),
        akt('schliessen', 330, 555, 'Ticket schließen'),
        akt('doku', 560, 555, 'Lösung dokumentieren'),
        quer('sync', 400, 610, 340),
        ende('e', 400, 662),
      ],
      kanten: [
        f('s', 'melden'),
        f('melden', 'erfassen'),
        f('erfassen', 'd1'),
        f('d1', 'mitteilen', { text: '[Lösung bekannt]' }),
        f('d1', 'm1', { text: '[Lösung unbekannt]' }),
        f('m1', 'analyse'),
        f('analyse', 'beheben'),
        f('mitteilen', 'm2'),
        f('beheben', 'm2', { vonSeite: 'unten', via: [[560, 375]], nachSeite: 'rechts' }),
        f('m2', 'testen'),
        f('testen', 'd2'),
        f('d2', 'm1', { vonSeite: 'rechts', via: [[650, 440], [650, 180]], nachSeite: 'rechts', text: '[funktioniert nicht]', textPos: 0.18 }),
        f('d2', 'teil', { nachSeite: 'oben:-220', text: '[funktioniert]' }),
        f('teil', 'schliessen', { vonSeite: 'unten:-10', nachSeite: 'oben' }),
        f('teil', 'doku', { vonSeite: 'unten:220', nachSeite: 'oben' }),
        f('schliessen', 'sync', { vonSeite: 'unten', nachSeite: 'oben:-70' }),
        f('doku', 'sync', { vonSeite: 'unten', nachSeite: 'oben:160' }),
        f('sync', 'e', { vonSeite: 'unten' }),
      ],
    },
    pruefliste: [
      'Drei **Schwimmbahnen** Anwender, Service Desk, Techniker; jede Aktion in der Bahn dessen, der sie ausführt',
      'Start beim Anwender: „Störung melden" → „Ticket erfassen" (Service Desk)',
      '**Entscheidung** mit [Lösung bekannt] / [Lösung unbekannt]',
      'Techniker: „Störung analysieren" → „Störung beheben"',
      '**Zusammenführung** vor „Lösung testen" – beide Wege kommen dort an',
      '**Entscheidung** nach dem Test; [funktioniert nicht] springt über eine Zusammenführung zurück vor „Störung analysieren"',
      '**Teilung**: „Ticket schließen" und „Lösung dokumentieren" parallel, danach **Synchronisation**',
      '**Endknoten** nach der Synchronisation',
    ],
    hinweise: 'Balken dürfen über Bahngrenzen reichen. Der Rücksprung endet in einer Zusammenführung, nicht direkt an „Störung analysieren" – sonst hätte die Aktion zwei eingehende Pfeile und würde auf beide warten.',
  },
  {
    id: 'ak-z3',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-1-3',
    titel: 'Bestellung mit zwei Parallelisierungen',
    text: 'Zeichne ein vollständiges Aktivitätsdiagramm (ohne Schwimmbahnen):\n- Der Kunde schickt eine Bestellung ab.\n- Das System prüft **gleichzeitig** die Bonität und die Verfügbarkeit der Ware.\n- Erst wenn beide Prüfungen fertig sind, wird entschieden: Ist mindestens eine Prüfung negativ, wird die Bestellung abgelehnt, und der Ablauf endet.\n- Sind beide positiv, wird die Bestellung bestätigt.\n- Danach laufen **parallel**: Ware versenden, Rechnung erstellen und Bewertungsanfrage planen. Die Bewertungsanfrage soll den Rest **nicht** aufhalten und endet für sich.\n- Sind Ware versendet und Rechnung erstellt, wird die Bestellung abgeschlossen, und der Ablauf endet.',
    muster: {
      breite: 640,
      hoehe: 700,
      knoten: [
        start('s', 330, 26),
        akt('abschicken', 330, 80, 'Bestellung abschicken', 150),
        quer('teil1', 330, 135, 260),
        akt('bonitaet', 240, 190, 'Bonität prüfen'),
        akt('verfueg', 420, 190, 'Verfügbarkeit prüfen'),
        quer('sync1', 330, 250, 260),
        raute('d', 330, 305),
        akt('ablehnen', 565, 305, 'Bestellung ablehnen', 140),
        ende('e1', 565, 368),
        akt('bestaetigen', 330, 370, 'Bestellung bestätigen', 150),
        quer('teil2', 330, 430, 380),
        akt('versenden', 180, 490, 'Ware versenden'),
        akt('rechnung', 330, 490, 'Rechnung erstellen'),
        akt('bewertung', 480, 490, 'Bewertungsanfrage planen', 140),
        aus('x', 480, 555),
        quer('sync2', 255, 555, 200),
        akt('abschliessen', 255, 615, 'Bestellung abschließen', 150),
        ende('e2', 255, 675),
      ],
      kanten: [
        f('s', 'abschicken'),
        f('abschicken', 'teil1', { nachSeite: 'oben' }),
        f('teil1', 'bonitaet', { vonSeite: 'unten:-90', nachSeite: 'oben' }),
        f('teil1', 'verfueg', { vonSeite: 'unten:90', nachSeite: 'oben' }),
        f('bonitaet', 'sync1', { vonSeite: 'unten', nachSeite: 'oben:-90' }),
        f('verfueg', 'sync1', { vonSeite: 'unten', nachSeite: 'oben:90' }),
        f('sync1', 'd', { vonSeite: 'unten' }),
        f('d', 'ablehnen', { text: '[mind. eine negativ]' }),
        f('ablehnen', 'e1'),
        f('d', 'bestaetigen', { text: '[beide positiv]' }),
        f('bestaetigen', 'teil2', { nachSeite: 'oben' }),
        f('teil2', 'versenden', { vonSeite: 'unten:-150', nachSeite: 'oben' }),
        f('teil2', 'rechnung', { vonSeite: 'unten', nachSeite: 'oben' }),
        f('teil2', 'bewertung', { vonSeite: 'unten:150', nachSeite: 'oben' }),
        f('bewertung', 'x'),
        f('versenden', 'sync2', { vonSeite: 'unten', nachSeite: 'oben:-75' }),
        f('rechnung', 'sync2', { vonSeite: 'unten', nachSeite: 'oben:75' }),
        f('sync2', 'abschliessen', { vonSeite: 'unten', nachSeite: 'oben' }),
        f('abschliessen', 'e2'),
      ],
    },
    pruefliste: [
      'Startknoten, „Bestellung abschicken", dann **Teilung** in „Bonität prüfen" und „Verfügbarkeit prüfen"',
      '**Synchronisation** nach beiden Prüfungen, erst danach die Entscheidung',
      'Entscheidung mit lückenlosen Bedingungen, z. B. **[beide positiv]** / **[mind. eine negativ]**',
      'Ablehnung: „Bestellung ablehnen" → **Endknoten**',
      '„Bestellung bestätigen", danach **zweite Teilung** in drei Zweige',
      '„Bewertungsanfrage planen" endet im **Ablaufende** (Kreis mit Kreuz)',
      '„Ware versenden" und „Rechnung erstellen" → **Synchronisation** → „Bestellung abschließen" → **Endknoten**',
      'Alle Kanten als Pfeile, Aktionen als Gegenstand + Verb',
    ],
    hinweise: 'Ein Endknoten im Bewertungszweig wäre falsch: Sobald die Planung fertig ist, würde er die **ganze** Aktivität beenden – auch Versand und Rechnung. Läuft die Planung noch, wenn der Endknoten nach „Bestellung abschließen" erreicht wird, wird sie abgebrochen – das nimmt der Text mit „soll den Rest nicht aufhalten" in Kauf. Zwei Endknoten für „abgelehnt" und „abgeschlossen" sind erlaubt; ebenso richtig ist, beide Wege über eine Zusammenführung zu **einem** Endknoten zu führen.',
  },
];

export default { spickzettel, notation, aufgaben };
