// Modus „Anwendungsfalldiagramm" – Format: siehe ../README.md

export const spickzettel = `- **Akteur** (Strichmännchen) steht **außerhalb** der Systemgrenze: Person, Rolle oder fremdes System
- **Anwendungsfall** (Ellipse) aus Sicht des Akteurs benennen: Gegenstand + Tätigkeit, z. B. „Ware bestellen"
- **Assoziation**: durchgezogene Linie Akteur – Anwendungsfall
- **«include»**: gestrichelter Pfeil vom Basis-Fall **zum eingeschlossenen** Fall – läuft **immer** mit
- **«extend»**: gestrichelter Pfeil vom erweiternden Fall **zum Basis-Fall** – nur **unter einer Bedingung**
- **Generalisierung**: Pfeil mit hohlem Dreieck zum **allgemeineren** Akteur (oder Fall)`;

const notationDiagramm = {
  breite: 760,
  hoehe: 360,
  rahmen: [{ typ: 'system', x: 200, y: 16, w: 540, h: 328, text: 'Systemgrenze: Online-Shop' }],
  knoten: [
    { id: 'kunde', typ: 'akteur', x: 70, y: 52, text: 'Kunde' },
    { id: 'stamm', typ: 'akteur', x: 70, y: 232, text: 'Stammkunde' },
    { id: 'bestellen', typ: 'anwendungsfall', x: 240, y: 60, w: 160, text: 'Ware bestellen' },
    { id: 'anmelden', typ: 'anwendungsfall', x: 540, y: 60, w: 160, text: 'Anmelden' },
    { id: 'gutschein', typ: 'anwendungsfall', x: 240, y: 240, w: 160, text: 'Gutschein einlösen' },
    { id: 'n1', typ: 'text', x: 430, y: 168, text: 'Erweiterungspunkt: Bezahlung\nBedingung: [Gutschein vorhanden]', klein: true },
  ],
  kanten: [
    { von: 'kunde', nach: 'bestellen', typ: 'assoziation', text: 'Assoziation' },
    { von: 'bestellen', nach: 'anmelden', typ: 'abhaengigkeit', text: '«include»' },
    { von: 'gutschein', nach: 'bestellen', typ: 'abhaengigkeit', text: '«extend»', textSeite: -1 },
    { von: 'stamm', nach: 'kunde', typ: 'generalisierung', text: 'Generalisierung', textSeite: -1 },
    { von: 'stamm', nach: 'gutschein', typ: 'assoziation' },
  ],
};

export const notation = {
  text: 'So liest du das Diagramm: Der Kunde bestellt Ware. Zum Bestellen gehört **immer** das Anmelden (include). Hat jemand einen Gutschein, **kann** das Bestellen um das Einlösen erweitert werden (extend). Ein Stammkunde kann alles, was ein Kunde kann – und zusätzlich Gutscheine einlösen.',
  diagramm: notationDiagramm,
  punkte: [
    '**include** – Pfeil zeigt auf den Fall, der immer mitläuft („Bestellen schließt Anmelden ein").',
    '**extend** – Pfeil zeigt auf den Basis-Fall, der erweitert wird („Gutschein einlösen erweitert Bestellen"). Bedingung und Erweiterungspunkt gehören dazu.',
    'Die **Systemgrenze** umschließt nur Anwendungsfälle. Akteure stehen immer außerhalb.',
    'Zwischen zwei Anwendungsfällen gibt es keine einfache Linie – nur include, extend oder Generalisierung.',
    'Zwischen Akteuren gibt es keine Assoziation – nur Generalisierung.',
  ],
};

const OPT_BEZ = ['«include»', '«extend»'];

export const aufgaben = [
  {
    id: 'af-e1',
    art: 'ergaenzen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-1',
    titel: 'Online-Shop',
    text: 'Beim Bestellen muss sich der Kunde **immer** anmelden. Hat er einen Gutschein, **kann** er ihn beim Bestellen einlösen. Ein Stammkunde kann alles, was ein Kunde kann. Ergänze die Beschriftungen [1] und [2] und beantworte die Frage.',
    diagramm: {
      breite: 760,
      hoehe: 330,
      rahmen: [{ typ: 'system', x: 200, y: 16, w: 540, h: 298, text: 'Online-Shop' }],
      knoten: [
        { id: 'kunde', typ: 'akteur', x: 70, y: 52, text: 'Kunde' },
        { id: 'stamm', typ: 'akteur', x: 70, y: 220, text: 'Stammkunde' },
        { id: 'bestellen', typ: 'anwendungsfall', x: 240, y: 60, w: 160, text: 'Ware bestellen' },
        { id: 'anmelden', typ: 'anwendungsfall', x: 540, y: 60, w: 160, text: 'Anmelden' },
        { id: 'gutschein', typ: 'anwendungsfall', x: 240, y: 226, w: 160, text: 'Gutschein einlösen' },
      ],
      kanten: [
        { von: 'kunde', nach: 'bestellen', typ: 'assoziation' },
        { von: 'bestellen', nach: 'anmelden', typ: 'abhaengigkeit', text: '{1}' },
        { von: 'gutschein', nach: 'bestellen', typ: 'abhaengigkeit', text: '{2}', textSeite: -1 },
        { von: 'stamm', nach: 'kunde', typ: 'generalisierung' },
        { von: 'stamm', nach: 'gutschein', typ: 'assoziation' },
      ],
    },
    felder: [
      { id: '1', label: 'Beziehung von „Ware bestellen" zu „Anmelden"', optionen: OPT_BEZ, erwartet: '«include»' },
      { id: '2', label: 'Beziehung von „Gutschein einlösen" zu „Ware bestellen"', optionen: OPT_BEZ, erwartet: '«extend»' },
      {
        id: 'g',
        label: 'Was bedeutet der Pfeil mit dem hohlen Dreieck von „Stammkunde" zu „Kunde"?',
        optionen: ['Der Stammkunde kann alles, was der Kunde kann (Generalisierung).', 'Der Kunde kann alles, was der Stammkunde kann.', 'Der Stammkunde ruft den Kunden auf.', 'Der Kunde besteht aus Stammkunden.'],
        erwartet: 'Der Stammkunde kann alles, was der Kunde kann (Generalisierung).',
      },
    ],
    loesung: [
      '[1] Anmelden gehört **immer** zum Bestellen → «include». Der Pfeil zeigt vom Basis-Fall auf den eingeschlossenen Fall.',
      '[2] Den Gutschein gibt es nur **manchmal** → «extend». Der Pfeil zeigt vom erweiternden Fall auf den Basis-Fall.',
      'Die Generalisierung zeigt zum allgemeineren Akteur: Der Stammkunde erbt alle Anwendungsfälle des Kunden – er darf also auch bestellen.',
    ],
  },
  {
    id: 'af-e2',
    art: 'ergaenzen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-1',
    titel: 'Ticketsystem im IT-Support',
    text: 'Mitarbeiter erfassen Störungen als Ticket. Beim Erfassen wird **immer** geprüft, ob es schon ein gleiches Ticket gibt. Ist die Störung dringend, **kann** zusätzlich eine SMS an die Bereitschaft gehen. Ein Supporter kann Tickets bearbeiten; ein Admin kann alles, was ein Supporter kann, und zusätzlich Benutzer verwalten. Ordne die Lücken zu.',
    diagramm: {
      breite: 800,
      hoehe: 420,
      rahmen: [{ typ: 'system', x: 190, y: 16, w: 430, h: 388, text: 'Ticketsystem' }],
      knoten: [
        { id: 'ma', typ: 'akteur', x: 70, y: 40, text: 'Mitarbeiter' },
        { id: 'sup', typ: 'akteur', x: 700, y: 140, text: '{3}' },
        { id: 'admin', typ: 'akteur', x: 700, y: 300, text: 'Admin' },
        { id: 'erfassen', typ: 'anwendungsfall', x: 220, y: 50, w: 160, text: 'Ticket erfassen' },
        { id: 'dublette', typ: 'anwendungsfall', x: 430, y: 50, w: 170, text: 'Doppelte Tickets prüfen' },
        { id: 'sms', typ: 'anwendungsfall', x: 220, y: 190, w: 160, text: 'SMS an Bereitschaft senden' },
        { id: 'bearbeiten', typ: 'anwendungsfall', x: 430, y: 160, w: 160, text: 'Ticket bearbeiten' },
        { id: 'benutzer', typ: 'anwendungsfall', x: 430, y: 310, w: 160, text: '{4}' },
      ],
      kanten: [
        { von: 'ma', nach: 'erfassen', typ: 'assoziation' },
        { von: 'erfassen', nach: 'dublette', typ: 'abhaengigkeit', text: '{1}' },
        { von: 'sms', nach: 'erfassen', typ: 'abhaengigkeit', text: '{2}\n[Störung dringend]', textSeite: -1 },
        { von: 'sup', nach: 'bearbeiten', typ: 'assoziation' },
        { von: 'admin', nach: 'sup', typ: 'generalisierung' },
        { von: 'admin', nach: 'benutzer', typ: 'assoziation' },
      ],
    },
    felder: [
      { id: '1', label: 'Beziehung „Ticket erfassen" → „Doppelte Tickets prüfen"', optionen: OPT_BEZ, erwartet: '«include»' },
      { id: '2', label: 'Beziehung „SMS an Bereitschaft senden" → „Ticket erfassen"', optionen: OPT_BEZ, erwartet: '«extend»' },
      { id: '3', label: 'Name des Akteurs oben rechts', optionen: ['Supporter', 'Ticket', 'Bereitschaft', 'Ticketsystem'], erwartet: 'Supporter' },
      { id: '4', label: 'Anwendungsfall, den nur der Admin hat', optionen: ['Benutzer verwalten', 'Admin', 'Benutzerdatenbank', 'Ticket erfassen'], erwartet: 'Benutzer verwalten' },
    ],
    loesung: [
      '[1] Die Prüfung auf doppelte Tickets läuft **immer** → «include».',
      '[2] Die SMS gibt es nur, wenn die Störung dringend ist → «extend» mit Bedingung.',
      '[3] Akteure sind Rollen außerhalb des Systems. Der Supporter bearbeitet Tickets.',
      '[4] Anwendungsfälle beschreiben eine Tätigkeit aus Sicht des Akteurs: Gegenstand + Verb – „Benutzer verwalten".',
      'Weil der Admin zum Supporter generalisiert ist, darf er auch Tickets bearbeiten, ohne eigene Linie dorthin.',
    ],
  },
  {
    id: 'af-f1',
    art: 'fehler',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-1',
    titel: 'Fehler im Bibliothekssystem',
    text: 'Ein Kollege hat das Diagramm für die Ausleihe gezeichnet: Beim Ausleihen wird **immer** der Ausweis geprüft; ist ein Buch überfällig, **kann** eine Mahngebühr erhoben werden. Prüfe die markierten Stellen 1–4.',
    diagramm: {
      breite: 780,
      hoehe: 360,
      rahmen: [{ typ: 'system', x: 170, y: 16, w: 590, h: 328, text: 'Bibliothek' }],
      knoten: [
        { id: 'leser', typ: 'akteur', x: 70, y: 60, text: 'Leser' },
        { id: 'biblio', typ: 'akteur', x: 230, y: 240, text: 'Bibliothekar', marke: 2 },
        { id: 'ausleihen', typ: 'anwendungsfall', x: 230, y: 60, w: 150, text: 'Buch ausleihen' },
        { id: 'ausweis', typ: 'anwendungsfall', x: 560, y: 60, w: 160, text: 'Ausweis prüfen' },
        { id: 'gebuehr', typ: 'anwendungsfall', x: 560, y: 230, w: 170, text: 'Mahngebühr erheben' },
        { id: 'zurueck', typ: 'anwendungsfall', x: 380, y: 160, w: 150, text: 'Buch zurückgeben' },
      ],
      kanten: [
        { von: 'leser', nach: 'ausleihen', typ: 'assoziation' },
        { von: 'ausweis', nach: 'ausleihen', typ: 'abhaengigkeit', text: '«include»', marke: 1 },
        { von: 'gebuehr', nach: 'zurueck', typ: 'abhaengigkeit', text: '«extend»\n[Buch überfällig]', textSeite: -1, marke: 3 },
        { von: 'ausleihen', nach: 'zurueck', typ: 'assoziation', marke: 4 },
        { von: 'biblio', nach: 'zurueck', typ: 'assoziation' },
      ],
    },
    felder: [
      { id: '1', label: '«include»-Pfeil zwischen „Ausweis prüfen" und „Buch ausleihen"', optionen: ['korrekt', 'Pfeilrichtung falsch', 'muss «extend» sein', 'muss durchgezogen sein'], erwartet: 'Pfeilrichtung falsch' },
      { id: '2', label: 'Akteur „Bibliothekar"', optionen: ['korrekt', 'steht innerhalb der Systemgrenze', 'ist kein Akteur, sondern ein Anwendungsfall', 'braucht eine Generalisierung zu „Leser"'], erwartet: 'steht innerhalb der Systemgrenze' },
      { id: '3', label: '«extend»-Pfeil von „Mahngebühr erheben" zu „Buch zurückgeben"', optionen: ['korrekt', 'Pfeilrichtung falsch', 'muss «include» sein', 'Bedingung ist nicht erlaubt'], erwartet: 'korrekt' },
      { id: '4', label: 'Linie zwischen „Buch ausleihen" und „Buch zurückgeben"', optionen: ['korrekt', 'unzulässig: zwischen Anwendungsfällen keine einfache Assoziation', 'muss eine Generalisierung sein', 'muss ein «include» sein'], erwartet: 'unzulässig: zwischen Anwendungsfällen keine einfache Assoziation' },
    ],
    loesung: [
      '[1] Bei «include» zeigt der Pfeil vom Basis-Fall („Buch ausleihen") **auf** den eingeschlossenen Fall („Ausweis prüfen"). Hier ist er umgedreht.',
      '[2] Akteure stehen immer **außerhalb** der Systemgrenze – auch Mitarbeiter, die das System bedienen.',
      '[3] Richtig: Die Gebühr kommt nur bei überfälligem Buch dazu, der Pfeil zeigt auf den Basis-Fall, die Bedingung steht dabei.',
      '[4] Zwei Anwendungsfälle verbindet man nicht mit einer einfachen Linie. Zurückgeben ist ein eigener Fall, den der Leser direkt anstößt – hier fehlt dafür die Linie Leser – „Buch zurückgeben".',
    ],
    muster: {
      breite: 780,
      hoehe: 360,
      rahmen: [{ typ: 'system', x: 170, y: 16, w: 590, h: 328, text: 'Bibliothek' }],
      knoten: [
        { id: 'leser', typ: 'akteur', x: 70, y: 60, text: 'Leser' },
        { id: 'biblio', typ: 'akteur', x: 70, y: 240, text: 'Bibliothekar' },
        { id: 'ausleihen', typ: 'anwendungsfall', x: 230, y: 60, w: 150, text: 'Buch ausleihen' },
        { id: 'ausweis', typ: 'anwendungsfall', x: 560, y: 60, w: 160, text: 'Ausweis prüfen' },
        { id: 'gebuehr', typ: 'anwendungsfall', x: 560, y: 230, w: 170, text: 'Mahngebühr erheben' },
        { id: 'zurueck', typ: 'anwendungsfall', x: 300, y: 200, w: 150, text: 'Buch zurückgeben' },
      ],
      kanten: [
        { von: 'leser', nach: 'ausleihen', typ: 'assoziation' },
        { von: 'leser', nach: 'zurueck', typ: 'assoziation' },
        { von: 'ausleihen', nach: 'ausweis', typ: 'abhaengigkeit', text: '«include»', hervor: true },
        { von: 'gebuehr', nach: 'zurueck', typ: 'abhaengigkeit', text: '«extend»\n[Buch überfällig]', textSeite: -1 },
        { von: 'biblio', nach: 'zurueck', typ: 'assoziation' },
      ],
    },
  },
  {
    id: 'af-q1',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP2-2-1-2',
    titel: 'include oder extend?',
    text: 'Entscheide für jeden Satz aus einer Anforderung einer Banking-App, welche Beziehung passt.',
    felder: [
      { id: 'a', label: 'Bei jeder Überweisung wird eine TAN abgefragt.', optionen: OPT_BEZ, erwartet: '«include»' },
      { id: 'b', label: 'Liegt der Betrag über 1.000 €, kann zusätzlich ein Rückruf vereinbart werden.', optionen: OPT_BEZ, erwartet: '«extend»' },
      { id: 'c', label: 'Wer sein Passwort dreimal falsch eingibt, kann das Konto entsperren lassen.', optionen: OPT_BEZ, erwartet: '«extend»' },
      { id: 'd', label: 'Zum Kontoauszug-Abruf gehört immer die Anmeldung.', optionen: OPT_BEZ, erwartet: '«include»' },
      {
        id: 'e',
        label: 'In welche Richtung zeigt der «extend»-Pfeil?',
        optionen: ['Vom erweiternden Fall zum Basis-Fall', 'Vom Basis-Fall zum erweiternden Fall', 'Vom Akteur zum Anwendungsfall', 'Er hat keine Richtung'],
        erwartet: 'Vom erweiternden Fall zum Basis-Fall',
      },
    ],
    loesung: [
      '„Immer", „jedes Mal", „gehört dazu" → **«include»**.',
      '„kann", „wenn", „falls", „unter der Bedingung" → **«extend»**, die Bedingung schreibst du an den Pfeil.',
      'Merksatz: include zeigt auf das, was immer **mitgemacht** wird; extend zeigt auf das, was **erweitert** wird.',
    ],
  },
  {
    id: 'af-f2',
    art: 'fehler',
    raum: ['AP2'],
    sp: 'AP2-2-1-2',
    titel: 'Fehler im Kinoportal',
    text: 'Anforderung: Besucher können das Programm ansehen und Tickets buchen. Zum Buchen gehört **immer** das Bezahlen. Mitglieder können alles, was Besucher können; zusätzlich **können** sie beim Buchen Bonuspunkte einlösen, wenn ihr Punktestand reicht. Das Zahlungssystem des Zahlungsdienstleisters wickelt die Bezahlung ab. Prüfe die Stellen 1–4.',
    diagramm: {
      breite: 800,
      hoehe: 380,
      rahmen: [{ typ: 'system', x: 180, y: 16, w: 440, h: 348, text: 'Kinoportal' }],
      knoten: [
        { id: 'besucher', typ: 'akteur', x: 70, y: 40, text: 'Besucher' },
        { id: 'mitglied', typ: 'akteur', x: 70, y: 250, text: 'Mitglied' },
        { id: 'zahl', typ: 'akteur', x: 690, y: 200, text: 'Zahlungssystem' },
        { id: 'programm', typ: 'anwendungsfall', x: 220, y: 40, w: 150, text: 'Programm ansehen' },
        { id: 'buchen', typ: 'anwendungsfall', x: 220, y: 150, w: 150, text: 'Ticket buchen' },
        { id: 'bezahlen', typ: 'anwendungsfall', x: 440, y: 190, w: 150, text: 'Bezahlung speichern', marke: 3 },
        { id: 'punkte', typ: 'anwendungsfall', x: 220, y: 280, w: 170, text: 'Bonuspunkte einlösen' },
      ],
      kanten: [
        { von: 'besucher', nach: 'programm', typ: 'assoziation' },
        { von: 'besucher', nach: 'buchen', typ: 'assoziation' },
        { von: 'besucher', nach: 'mitglied', typ: 'generalisierung', marke: 1 },
        { von: 'buchen', nach: 'bezahlen', typ: 'abhaengigkeit', text: '«include»' },
        { von: 'buchen', nach: 'punkte', typ: 'abhaengigkeit', text: '«extend»\n[Punktestand reicht]', marke: 2 },
        { von: 'mitglied', nach: 'punkte', typ: 'assoziation' },
        { von: 'zahl', nach: 'bezahlen', typ: 'assoziation', marke: 4 },
      ],
    },
    felder: [
      { id: '1', label: 'Generalisierung zwischen Besucher und Mitglied', optionen: ['korrekt', 'Pfeilrichtung falsch', 'muss eine Assoziation sein', 'muss «include» sein'], erwartet: 'Pfeilrichtung falsch' },
      { id: '2', label: '«extend» zwischen „Ticket buchen" und „Bonuspunkte einlösen"', optionen: ['korrekt', 'Pfeilrichtung falsch', 'muss «include» sein', 'Bedingung gehört nicht dazu'], erwartet: 'Pfeilrichtung falsch' },
      { id: '3', label: 'Name des Anwendungsfalls „Bezahlung speichern"', optionen: ['korrekt', 'aus Systemsicht benannt – besser „Ticket bezahlen"', 'muss ein Akteur sein', 'gehört außerhalb der Systemgrenze'], erwartet: 'aus Systemsicht benannt – besser „Ticket bezahlen"' },
      { id: '4', label: 'Akteur „Zahlungssystem" mit Linie zum Bezahlen', optionen: ['korrekt', 'fremde Systeme sind keine Akteure', 'muss innerhalb der Systemgrenze stehen', 'braucht «include»'], erwartet: 'korrekt' },
    ],
    loesung: [
      '[1] Die Generalisierung zeigt zum **allgemeineren** Akteur: Mitglied → Besucher. So erbt das Mitglied alles vom Besucher.',
      '[2] Bei «extend» zeigt der Pfeil vom erweiternden Fall („Bonuspunkte einlösen") zum Basis-Fall („Ticket buchen").',
      '[3] Anwendungsfälle benennst du aus Sicht des Akteurs: Was will er erreichen? „Ticket bezahlen" statt „Bezahlung speichern".',
      '[4] Richtig: Ein fremdes System, mit dem dein System zusammenarbeitet, ist ein Akteur außerhalb der Systemgrenze.',
    ],
  },

  // ---------- Zeichnen ----------
  {
    id: 'af-z1',
    art: 'zeichnen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-3-1',
    titel: 'Fitnessstudio-App erweitern',
    text: 'Das begonnene Diagramm zeigt die App eines Fitnessstudios. Erweitere es nach diesen Vorgaben:\n- Mitglieder können **Kurse buchen**. Dabei wird **immer** die Mitgliedschaft geprüft.\n- Ist der Kurs voll, **kann** sich das Mitglied auf die **Warteliste** setzen lassen.\n- **Trainer** können alles, was Mitglieder können, und zusätzlich **Kurse anlegen**.',
    vorlage: {
      breite: 720,
      hoehe: 300,
      rahmen: [{ typ: 'system', x: 190, y: 16, w: 510, h: 268, text: 'Fitness-App' }],
      knoten: [
        { id: 'mitglied', typ: 'akteur', x: 70, y: 60, text: 'Mitglied' },
        { id: 'plan', typ: 'anwendungsfall', x: 230, y: 50, w: 170, text: 'Trainingsplan ansehen' },
      ],
      kanten: [{ von: 'mitglied', nach: 'plan', typ: 'assoziation' }],
    },
    muster: {
      breite: 760,
      hoehe: 420,
      rahmen: [{ typ: 'system', x: 190, y: 16, w: 550, h: 388, text: 'Fitness-App' }],
      knoten: [
        { id: 'mitglied', typ: 'akteur', x: 70, y: 70, text: 'Mitglied' },
        { id: 'trainer', typ: 'akteur', x: 70, y: 290, text: 'Trainer' },
        { id: 'plan', typ: 'anwendungsfall', x: 230, y: 40, w: 170, text: 'Trainingsplan ansehen' },
        { id: 'buchen', typ: 'anwendungsfall', x: 230, y: 140, w: 170, text: 'Kurs buchen' },
        { id: 'pruefen', typ: 'anwendungsfall', x: 520, y: 140, w: 190, text: 'Mitgliedschaft prüfen' },
        { id: 'warte', typ: 'anwendungsfall', x: 520, y: 250, w: 190, text: 'Auf Warteliste setzen' },
        { id: 'anlegen', typ: 'anwendungsfall', x: 230, y: 320, w: 170, text: 'Kurs anlegen' },
      ],
      kanten: [
        { von: 'mitglied', nach: 'plan', typ: 'assoziation' },
        { von: 'mitglied', nach: 'buchen', typ: 'assoziation' },
        { von: 'buchen', nach: 'pruefen', typ: 'abhaengigkeit', text: '«include»' },
        { von: 'warte', nach: 'buchen', typ: 'abhaengigkeit', text: '«extend»\n[Kurs voll]', textSeite: -1 },
        { von: 'trainer', nach: 'mitglied', typ: 'generalisierung' },
        { von: 'trainer', nach: 'anlegen', typ: 'assoziation' },
      ],
    },
    pruefliste: [
      'Neuer Akteur **Trainer** außerhalb der Systemgrenze',
      'Generalisierung **Trainer → Mitglied** mit hohlem Dreieck am Mitglied',
      'Anwendungsfälle **Kurs buchen**, **Mitgliedschaft prüfen**, **Auf Warteliste setzen**, **Kurs anlegen** innerhalb der Systemgrenze',
      'Assoziation Mitglied – Kurs buchen und Trainer – Kurs anlegen',
      '**«include»** gestrichelt von „Kurs buchen" **zu** „Mitgliedschaft prüfen"',
      '**«extend»** gestrichelt von „Auf Warteliste setzen" **zu** „Kurs buchen", Bedingung [Kurs voll] angegeben',
    ],
    hinweise: 'Der Trainer braucht **keine** eigene Linie zu „Kurs buchen" – das erbt er über die Generalisierung.',
  },
  {
    id: 'af-z2',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-1-2',
    titel: 'Carsharing vollständig modellieren',
    text: 'Erstelle ein vollständiges Anwendungsfalldiagramm für die Carsharing-Plattform „StadtFlitzer":\n- **Kunden** können sich registrieren, Fahrzeuge suchen und Fahrzeuge reservieren.\n- Beim Reservieren wird **immer** der Führerschein geprüft.\n- Ist der Kunde bei der Reservierung im Ausland, **kann** eine Zusatzversicherung abgeschlossen werden (Erweiterungspunkt: Abschluss der Reservierung).\n- **Geschäftskunden** können alles, was Kunden können, und zusätzlich Sammelrechnungen abrufen.\n- Ein **Servicemitarbeiter** kann Fahrzeuge warten und Schäden erfassen. Beim Warten wird **immer** der Kilometerstand erfasst.\n- Das **Zahlungssystem** eines Dienstleisters ist am Reservieren beteiligt.',
    muster: {
      breite: 900,
      hoehe: 560,
      rahmen: [{ typ: 'system', x: 190, y: 16, w: 560, h: 528, text: 'StadtFlitzer' }],
      knoten: [
        { id: 'kunde', typ: 'akteur', x: 70, y: 110, text: 'Kunde' },
        { id: 'gk', typ: 'akteur', x: 70, y: 300, text: 'Geschäftskunde' },
        { id: 'service', typ: 'akteur', x: 810, y: 380, text: 'Servicemitarbeiter' },
        { id: 'zahl', typ: 'akteur', x: 810, y: 150, text: 'Zahlungssystem' },
        { id: 'reg', typ: 'anwendungsfall', x: 220, y: 36, w: 150, text: 'Registrieren' },
        { id: 'suchen', typ: 'anwendungsfall', x: 220, y: 110, w: 150, text: 'Fahrzeug suchen' },
        { id: 'res', typ: 'anwendungsfall', x: 300, y: 190, w: 170, text: 'Fahrzeug reservieren' },
        { id: 'fs', typ: 'anwendungsfall', x: 560, y: 60, w: 160, text: 'Führerschein prüfen' },
        { id: 'vers', typ: 'anwendungsfall', x: 540, y: 270, w: 190, text: 'Zusatzversicherung abschließen' },
        { id: 'rech', typ: 'anwendungsfall', x: 220, y: 330, w: 170, text: 'Sammelrechnung abrufen' },
        { id: 'warten', typ: 'anwendungsfall', x: 560, y: 380, w: 160, text: 'Fahrzeug warten' },
        { id: 'km', typ: 'anwendungsfall', x: 320, y: 450, w: 180, text: 'Kilometerstand erfassen' },
        { id: 'schaden', typ: 'anwendungsfall', x: 560, y: 470, w: 160, text: 'Schaden erfassen' },
      ],
      kanten: [
        { von: 'kunde', nach: 'reg', typ: 'assoziation' },
        { von: 'kunde', nach: 'suchen', typ: 'assoziation' },
        { von: 'kunde', nach: 'res', typ: 'assoziation' },
        { von: 'gk', nach: 'kunde', typ: 'generalisierung' },
        { von: 'gk', nach: 'rech', typ: 'assoziation' },
        { von: 'res', nach: 'fs', typ: 'abhaengigkeit', text: '«include»' },
        { von: 'vers', nach: 'res', typ: 'abhaengigkeit', text: '«extend»\n[Kunde im Ausland]', textSeite: -1 },
        { von: 'zahl', nach: 'res', typ: 'assoziation' },
        { von: 'service', nach: 'warten', typ: 'assoziation' },
        { von: 'service', nach: 'schaden', typ: 'assoziation' },
        { von: 'warten', nach: 'km', typ: 'abhaengigkeit', text: '«include»' },
      ],
    },
    pruefliste: [
      'Systemgrenze mit Namen, alle Anwendungsfälle innen, alle **vier Akteure** außen (Kunde, Geschäftskunde, Servicemitarbeiter, Zahlungssystem)',
      'Generalisierung **Geschäftskunde → Kunde**, Geschäftskunde zusätzlich mit „Sammelrechnung abrufen"',
      'Kunde mit **Registrieren**, **Fahrzeug suchen**, **Fahrzeug reservieren** verbunden',
      '**«include»** von „Fahrzeug reservieren" zu „Führerschein prüfen"',
      '**«extend»** von „Zusatzversicherung abschließen" zu „Fahrzeug reservieren" mit Bedingung [Kunde im Ausland] und Erweiterungspunkt',
      'Servicemitarbeiter mit **Fahrzeug warten** und **Schaden erfassen**; **«include»** von „Fahrzeug warten" zu „Kilometerstand erfassen"',
      'Zahlungssystem per Assoziation an „Fahrzeug reservieren"',
      'Anwendungsfälle aus Sicht der Akteure benannt (Gegenstand + Tätigkeit)',
    ],
    hinweise: 'Den Erweiterungspunkt kannst du in die Ellipse von „Fahrzeug reservieren" schreiben (extension points: Abschluss der Reservierung) oder in eine Notiz am «extend»-Pfeil.',
  },
];

export default { spickzettel, notation, aufgaben };
