// Modus „ER-Modell" (Chen-Notation) – Format: siehe ../README.md

export const spickzettel = `- **Entität** (Rechteck): ein Ding, über das Daten gespeichert werden – Substantiv im Singular, z. B. „Kunde"
- **Attribut** (Ellipse): Eigenschaft, mit einer Linie an **genau einer** Entität (oder Beziehung)
- **Primärschlüssel**: Attribut, das jedes Exemplar eindeutig kennzeichnet – **unterstrichen**, meist eine Nummer
- **Beziehung** (Raute): Verb zwischen zwei Entitäten, z. B. „bestellt"
- **Kardinalität** an beide Linien: **1:1**, **1:n** oder **m:n** – frage in beide Richtungen: „Wie viele B hat ein A?" und „Wie viele A hat ein B?"
- Jede Angabe nur **einmal** speichern: Der Kundenname gehört zum Kunden, nicht zur Bestellung
- Gehört ein Wert zu einem **Paar** (Menge je Artikel in einer Bestellung), hängt er an der **Beziehung**`;

// Breite einer Attribut-Ellipse passend zum Text
const breite = (t) => Math.max(84, Math.ceil(String(t).length * 7.9 + 22));
const ent = (id, x, y, text, extra = {}) => ({ id, typ: 'entitaet', x, y, text, ...extra });
const bez = (id, x, y, text, extra = {}) => ({ id, typ: 'beziehung', x, y, text, ...extra });
const att = (id, x, y, text, extra = {}) => ({ id, typ: 'attribut', x, y, w: breite(text), text, ...extra });
const pk = (id, x, y, text, extra = {}) => att(id, x, y, text, { pk: true, ...extra });
const lin = (von, nach, extra = {}) => ({ von, nach, typ: 'linie', ...extra });

const notationDiagramm = {
  breite: 940,
  hoehe: 380,
  knoten: [
    ent('kunde', 30, 160, 'Kunde'),
    bez('bestellt', 220, 155, 'erteilt'),
    ent('bestellung', 400, 160, 'Bestellung'),
    bez('enthaelt', 590, 155, 'enthält'),
    ent('artikel', 770, 160, 'Artikel'),
    pk('knr', 10, 50, 'Kundennummer'),
    att('kname', 140, 50, 'Name'),
    pk('bnr', 360, 50, 'Bestellnummer'),
    att('bdatum', 500, 50, 'Datum'),
    att('menge', 603, 270, 'Menge'),
    pk('anr', 730, 50, 'Artikelnummer'),
    att('preis', 830, 270, 'Preis'),
    { id: 't1', typ: 'text', x: 90, y: 232, text: 'Entität', anker: 'middle', klein: true },
    { id: 't2', typ: 'text', x: 275, y: 228, text: 'Beziehung', anker: 'middle', klein: true },
    { id: 't3', typ: 'text', x: 645, y: 334, text: 'Attribut an der Beziehung', anker: 'middle', klein: true },
    { id: 't4', typ: 'text', x: 68, y: 26, text: 'Primärschlüssel (unterstrichen)', anker: 'start', klein: true },
    { id: 't5', typ: 'text', x: 870, y: 334, text: 'Attribut', anker: 'middle', klein: true },
    { id: 't6', typ: 'text', x: 470, y: 250, text: 'Kardinalitäten: 1 Kunde – n Bestellungen,\nm Bestellungen – n Artikel', anker: 'middle', klein: true },
  ],
  kanten: [
    lin('kunde', 'bestellt', { textVon: '1' }),
    lin('bestellt', 'bestellung', { textNach: 'n' }),
    lin('bestellung', 'enthaelt', { textVon: 'm' }),
    lin('enthaelt', 'artikel', { textNach: 'n' }),
    lin('knr', 'kunde'),
    lin('kname', 'kunde'),
    lin('bnr', 'bestellung'),
    lin('bdatum', 'bestellung'),
    lin('menge', 'enthaelt'),
    lin('anr', 'artikel'),
    lin('preis', 'artikel'),
  ],
};

export const notation = {
  text: 'So liest du das Diagramm: Ein Kunde erteilt **n** (viele) Bestellungen, jede Bestellung stammt von genau **1** Kunden. Eine Bestellung enthält viele Artikel, ein Artikel steckt in vielen Bestellungen (**m:n**). Die Menge gehört weder zur Bestellung allein noch zum Artikel allein – sie hängt an der Beziehung.',
  diagramm: notationDiagramm,
  punkte: [
    '**Rechteck** = Entität, **Raute** = Beziehung, **Ellipse** = Attribut. Linien verbinden nur Entität – Beziehung und Attribut – Entität/Beziehung.',
    'Die Kardinalität steht an der Linie **neben der Entität**, deren Anzahl sie angibt: „1 Kunde erteilt n Bestellungen".',
    '**1:1** – je eins auf beiden Seiten (Mitarbeiter – Dienstausweis). **1:n** – eins zu vielen (Abteilung – Mitarbeiter). **m:n** – viele zu vielen (Teilnehmer – Kurs).',
    'Jede Entität braucht einen **Primärschlüssel** (unterstrichen). Name oder Datum taugen nicht – sie können doppelt vorkommen.',
    'Den Zusammenhang zweier Entitäten zeigt **allein die Beziehung**. Trage also keine Nummer oder keinen Namen der anderen Entität als Attribut ein.',
  ],
};

const KARD = ['1', 'n'];

// ---------- Hardware-Verleih (Fehler + Muster) ----------
function verleih(fehler) {
  return {
    breite: 760,
    hoehe: 300,
    knoten: [
      ent('ma', 60, 130, 'Mitarbeiter'),
      bez('leiht', 300, 125, 'leiht aus'),
      ent('geraet', 560, 130, 'Gerät'),
      pk('pnr', 10, 30, 'Personalnummer', fehler ? { marke: 4 } : {}),
      att('name', 170, 30, 'Name'),
      att('abt', 60, 230, 'Abteilung'),
      fehler ? att('inv', 440, 30, 'Inventarnummer', { marke: 1 }) : pk('inv', 440, 30, 'Inventarnummer', { hervor: true }),
      att('typ', 610, 30, 'Gerätetyp'),
      ...(fehler ? [att('maname', 560, 230, 'Mitarbeitername', { marke: 2 })] : []),
    ],
    kanten: [
      lin('ma', 'leiht', { textVon: fehler ? 'n' : '1', hervor: !fehler }),
      lin('leiht', 'geraet', { textNach: fehler ? '1' : 'n', ...(fehler ? { marke: 3 } : { hervor: true }) }),
      lin('pnr', 'ma'),
      lin('name', 'ma'),
      lin('abt', 'ma'),
      lin('inv', 'geraet'),
      lin('typ', 'geraet'),
      ...(fehler ? [lin('maname', 'geraet')] : []),
    ],
  };
}

// ---------- Projektzeiterfassung (Fehler + Muster) ----------
function projekte(fehler) {
  return {
    breite: 910,
    hoehe: 330,
    knoten: [
      ent('ma', 30, 140, 'Mitarbeiter'),
      bez('arb', 220, 135, 'arbeitet an'),
      ent('proj', 400, 140, 'Projekt'),
      bez('beauf', 585, 135, 'beauftragt'),
      ent('kunde', 770, 140, 'Kunde'),
      pk('pnr', 4, 40, 'Personalnummer'),
      att('name', 20, 250, 'Name'),
      fehler ? att('std', 130, 250, 'Stunden', { marke: 1 }) : att('std', 233, 245, 'Stunden', { hervor: true }),
      pk('prnr', 330, 40, 'Projektnummer', fehler ? { marke: 4 } : {}),
      att('bez', 480, 40, 'Bezeichnung'),
      ...(fehler ? [att('fname2', 420, 250, 'Firmenname', { marke: 2 })] : []),
      pk('knr', 740, 40, 'Kundennummer'),
      att('fname', 776, 250, 'Firmenname'),
    ],
    kanten: [
      lin('ma', 'arb', { textVon: 'm' }),
      lin('arb', 'proj', { textNach: 'n' }),
      lin('proj', 'beauf', { textVon: fehler ? 'm' : 'n', hervor: !fehler }),
      lin('beauf', 'kunde', { textNach: fehler ? 'n' : '1', ...(fehler ? { marke: 3 } : { hervor: true }) }),
      lin('pnr', 'ma'),
      lin('name', 'ma'),
      lin('std', fehler ? 'ma' : 'arb'),
      lin('prnr', 'proj'),
      lin('bez', 'proj'),
      ...(fehler ? [lin('fname2', 'proj')] : []),
      lin('knr', 'kunde'),
      lin('fname', 'kunde'),
    ],
  };
}

export const aufgaben = [
  // ---------- AP1 und AP2 ----------
  {
    id: 'er-e1',
    art: 'ergaenzen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-1',
    titel: 'Kfz-Werkstatt',
    text: 'Eine Kfz-Werkstatt speichert **Kunden** mit Kundennummer, Name und Telefonnummer. Ein Kunde kann mehrere **Fahrzeuge** besitzen; jedes Fahrzeug gehört genau einem Kunden. Ein Fahrzeug wird über seine Fahrgestellnummer eindeutig erkannt und hat außerdem Marke und Baujahr. Ergänze die Lücken [1] bis [4].',
    diagramm: {
      breite: 780,
      hoehe: 300,
      knoten: [
        ent('kunde', 60, 130, 'Kunde'),
        bez('besitzt', 300, 125, 'besitzt'),
        ent('fzg', 560, 130, 'Fahrzeug'),
        pk('knr', 10, 30, 'Kundennummer'),
        att('name', 160, 30, 'Name'),
        att('tel', 60, 230, '{3}', { w: breite('Telefonnummer') }),
        pk('fin', 430, 30, '{4}', { w: breite('Fahrgestellnummer') }),
        att('marke', 630, 30, 'Marke'),
        att('baujahr', 600, 230, 'Baujahr'),
      ],
      kanten: [
        lin('kunde', 'besitzt', { textVon: '{1}' }),
        lin('besitzt', 'fzg', { textNach: '{2}' }),
        lin('knr', 'kunde'),
        lin('name', 'kunde'),
        lin('tel', 'kunde'),
        lin('fin', 'fzg'),
        lin('marke', 'fzg'),
        lin('baujahr', 'fzg'),
      ],
    },
    felder: [
      { id: '1', label: 'Kardinalität auf der Seite „Kunde"', optionen: KARD, erwartet: '1' },
      { id: '2', label: 'Kardinalität auf der Seite „Fahrzeug"', optionen: KARD, erwartet: 'n' },
      { id: '3', label: 'Fehlendes Attribut am Kunden', optionen: ['Fahrgestellnummer', 'Telefonnummer', 'Marke'], erwartet: 'Telefonnummer' },
      { id: '4', label: 'Primärschlüssel von „Fahrzeug" (unterstrichen)', optionen: ['Marke', 'Kundennummer', 'Fahrgestellnummer'], erwartet: 'Fahrgestellnummer' },
    ],
    loesung: [
      '[1] und [2]: Ein Kunde besitzt **viele** Fahrzeuge, ein Fahrzeug gehört **einem** Kunden → 1:n. Die 1 steht beim Kunden, das n beim Fahrzeug.',
      '[3] Die Telefonnummer beschreibt den Kunden, nicht das Fahrzeug – also hängt sie am Kunden.',
      '[4] Der Primärschlüssel muss jedes Fahrzeug **eindeutig** kennzeichnen. Marken wiederholen sich; die Kundennummer gehört zum Kunden. Die Fahrgestellnummer ist je Fahrzeug einmalig.',
    ],
  },
  {
    id: 'er-q1',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-1',
    titel: 'Kardinalitäten aus dem Text',
    text: 'Bestimme für jeden Satz die Kardinalität der Beziehung. Frage dich in **beide** Richtungen: Wie viele B gehören zu einem A – und wie viele A zu einem B?',
    felder: [
      { id: 'a', label: 'Eine Abteilung hat viele Mitarbeiter; jeder Mitarbeiter gehört genau einer Abteilung an.', optionen: ['1:1', '1:n', 'm:n'], erwartet: '1:n' },
      { id: 'b', label: 'Ein Teilnehmer belegt mehrere Kurse; ein Kurs hat mehrere Teilnehmer.', optionen: ['1:1', '1:n', 'm:n'], erwartet: 'm:n' },
      { id: 'c', label: 'Jeder Mitarbeiter hat genau einen Dienstausweis; jeder Dienstausweis gehört genau einem Mitarbeiter.', optionen: ['1:1', '1:n', 'm:n'], erwartet: '1:1' },
      { id: 'd', label: 'Ein Lager hat viele Lagerplätze; jeder Lagerplatz liegt in genau einem Lager.', optionen: ['1:1', '1:n', 'm:n'], erwartet: '1:n' },
      { id: 'e', label: 'Ein Arzt behandelt viele Patienten; ein Patient wird von mehreren Ärzten behandelt.', optionen: ['1:1', '1:n', 'm:n'], erwartet: 'm:n' },
      {
        id: 'f',
        label: 'Bei „Abteilung – Mitarbeiter" (1:n): Wo steht das n?',
        optionen: ['An der Linie zur Abteilung', 'An der Linie zum Mitarbeiter', 'In der Raute'],
        erwartet: 'An der Linie zum Mitarbeiter',
      },
    ],
    loesung: [
      'Steht auf **einer** Seite „viele" und auf der anderen „genau ein" → **1:n**.',
      'Steht auf **beiden** Seiten „viele" / „mehrere" → **m:n**.',
      'Steht auf beiden Seiten „genau ein" → **1:1**.',
      'Das n steht bei der Entität, von der es **viele** gibt: viele Mitarbeiter je Abteilung → n an der Linie zum Mitarbeiter.',
    ],
  },
  {
    id: 'er-q2',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-1',
    titel: 'Attribute richtig zuordnen',
    text: 'Eine Arztpraxis plant ein ER-Modell mit den Entitäten **Patient**, **Arzt** und **Termin**. Ein Patient hat viele Termine, ein Arzt hat viele Termine, jeder Termin gehört zu genau einem Patienten und einem Arzt. Ordne die Attribute zu.',
    felder: [
      { id: 'a', label: 'Geburtsdatum', optionen: ['Patient', 'Arzt', 'Termin'], erwartet: 'Patient' },
      { id: 'b', label: 'Uhrzeit', optionen: ['Patient', 'Arzt', 'Termin'], erwartet: 'Termin' },
      { id: 'c', label: 'Fachrichtung', optionen: ['Patient', 'Arzt', 'Termin'], erwartet: 'Arzt' },
      { id: 'd', label: 'Krankenkasse', optionen: ['Patient', 'Arzt', 'Termin'], erwartet: 'Patient' },
      { id: 'e', label: 'Geeigneter Primärschlüssel für „Patient"', optionen: ['Nachname', 'Patientennummer', 'Geburtsdatum', 'Krankenkasse'], erwartet: 'Patientennummer' },
      {
        id: 'f',
        label: 'Ein Kollege schreibt den Namen des Arztes zusätzlich an jeden Termin. Was ist das Problem?',
        optionen: [
          'Nichts – so findet man den Namen schneller.',
          'Der Name steht dann viele Male und gehört nur zum Arzt; der Termin ist über die Beziehung schon mit dem Arzt verbunden.',
          'Termine dürfen gar keine Attribute haben.',
          'Der Arztname muss der Primärschlüssel des Termins sein.',
        ],
        erwartet: 'Der Name steht dann viele Male und gehört nur zum Arzt; der Termin ist über die Beziehung schon mit dem Arzt verbunden.',
      },
    ],
    loesung: [
      'Frage bei jedem Attribut: **Wen beschreibt es?** Geburtsdatum und Krankenkasse beschreiben den Patienten, die Fachrichtung den Arzt, die Uhrzeit den Termin.',
      'Ein Primärschlüssel muss **eindeutig** sein. Namen und Geburtsdaten können mehrfach vorkommen – eine vergebene Patientennummer nicht.',
      'Jede Angabe wird nur **einmal** gespeichert. Welcher Arzt zum Termin gehört, zeigt die Beziehung; den Namen liest man beim Arzt nach.',
    ],
  },
  {
    id: 'er-f1',
    art: 'fehler',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-1',
    titel: 'Fehler im Hardware-Verleih',
    text: 'Die IT-Abteilung verleiht Geräte an Mitarbeiter. Gespeichert wird nur die **aktuelle** Ausleihe: Ein Mitarbeiter kann mehrere Geräte gleichzeitig haben, ein Gerät ist immer nur bei einem Mitarbeiter. Jedes Gerät hat eine eindeutige Inventarnummer und einen Gerätetyp. Prüfe die markierten Stellen 1–4.',
    diagramm: verleih(true),
    felder: [
      {
        id: '1',
        label: 'Attribut „Inventarnummer"',
        optionen: ['korrekt', 'muss als Primärschlüssel unterstrichen sein', 'gehört zum Mitarbeiter', 'muss an der Beziehung hängen'],
        erwartet: 'muss als Primärschlüssel unterstrichen sein',
      },
      {
        id: '2',
        label: 'Attribut „Mitarbeitername" am Gerät',
        optionen: ['korrekt', 'muss Primärschlüssel von „Gerät" sein', 'überflüssig: der Name steht schon beim Mitarbeiter', 'gehört an die Beziehung „leiht aus"'],
        erwartet: 'überflüssig: der Name steht schon beim Mitarbeiter',
      },
      {
        id: '3',
        label: 'Kardinalitäten an „leiht aus"',
        optionen: ['korrekt', 'vertauscht: 1 gehört zum Mitarbeiter, n zum Gerät', 'muss m:n sein', 'muss 1:1 sein'],
        erwartet: 'vertauscht: 1 gehört zum Mitarbeiter, n zum Gerät',
      },
      {
        id: '4',
        label: 'Primärschlüssel „Personalnummer"',
        optionen: ['korrekt', '„Name" wäre der bessere Primärschlüssel', 'Primärschlüssel werden nicht unterstrichen', 'gehört zum Gerät'],
        erwartet: 'korrekt',
      },
    ],
    loesung: [
      '[1] Jede Entität braucht einen Primärschlüssel. Die Inventarnummer ist eindeutig – sie wird unterstrichen.',
      '[2] Der Name gehört zum Mitarbeiter. Welcher Mitarbeiter das Gerät hat, zeigt die Beziehung – ein zweiter Eintrag am Gerät wäre doppelt gespeichert.',
      '[3] Ein Mitarbeiter hat **viele** Geräte, ein Gerät ist bei **einem** Mitarbeiter → die 1 steht beim Mitarbeiter, das n beim Gerät.',
      '[4] Richtig: Die Personalnummer ist eindeutig. Ein Name kann mehrfach vorkommen.',
    ],
    muster: verleih(false),
  },

  // ---------- nur AP2 ----------
  {
    id: 'er-e2',
    art: 'ergaenzen',
    raum: ['AP2'],
    sp: 'AP2-2-2-1',
    titel: 'Schulungsanbieter',
    text: 'Ein Schulungsanbieter verwaltet **Teilnehmer** (Teilnehmernummer, Name), **Kurse** (Kursnummer, Titel, Startdatum) und **Trainer** (Trainernummer, Name). Ein Teilnehmer kann mehrere Kurse buchen, ein Kurs hat viele Teilnehmer. Zu jeder Buchung wird das Buchungsdatum gespeichert. Jeder Kurs wird von genau einem Trainer geleitet; ein Trainer leitet mehrere Kurse. Ergänze die Lücken.',
    diagramm: {
      breite: 910,
      hoehe: 330,
      knoten: [
        ent('tn', 30, 140, 'Teilnehmer'),
        bez('bucht', 220, 135, 'bucht'),
        ent('kurs', 400, 140, 'Kurs'),
        bez('leitet', 585, 135, 'leitet'),
        ent('trainer', 770, 140, 'Trainer'),
        pk('tnr', 4, 40, 'Teilnehmernummer'),
        att('tname', 20, 250, 'Name'),
        att('bdatum', 212, 245, '{2}', { w: breite('Teilnehmername') }),
        pk('knr', 360, 40, '{4}', { w: breite('Trainernummer') }),
        att('titel', 500, 40, 'Titel'),
        att('start', 410, 250, 'Startdatum'),
        pk('trnr', 735, 40, 'Trainernummer'),
        att('trname', 800, 250, 'Name'),
      ],
      kanten: [
        lin('tn', 'bucht', { textVon: 'm' }),
        lin('bucht', 'kurs', { textNach: '{1}' }),
        lin('kurs', 'leitet', { textVon: 'n' }),
        lin('leitet', 'trainer', { textNach: '{3}' }),
        lin('tnr', 'tn'),
        lin('tname', 'tn'),
        lin('bdatum', 'bucht'),
        lin('knr', 'kurs'),
        lin('titel', 'kurs'),
        lin('start', 'kurs'),
        lin('trnr', 'trainer'),
        lin('trname', 'trainer'),
      ],
    },
    felder: [
      { id: '1', label: 'Kardinalität auf der Seite „Kurs" (Beziehung „bucht")', optionen: KARD, erwartet: 'n' },
      { id: '2', label: 'Attribut an der Beziehung „bucht"', optionen: ['Titel', 'Buchungsdatum', 'Teilnehmername', 'Trainernummer'], erwartet: 'Buchungsdatum' },
      { id: '3', label: 'Kardinalität auf der Seite „Trainer" (Beziehung „leitet")', optionen: KARD, erwartet: '1' },
      { id: '4', label: 'Primärschlüssel von „Kurs"', optionen: ['Kursnummer', 'Trainernummer', 'Buchungsdatum'], erwartet: 'Kursnummer' },
    ],
    loesung: [
      '[1] Ein Teilnehmer bucht viele Kurse, ein Kurs hat viele Teilnehmer → **m:n**. Auf der Kurs-Seite steht also n.',
      '[2] Das Buchungsdatum gehört weder zum Teilnehmer allein (er bucht mehrere Kurse zu verschiedenen Zeiten) noch zum Kurs allein – es beschreibt das **Paar** Teilnehmer + Kurs. Deshalb hängt es an der Beziehung.',
      '[3] Ein Kurs hat **genau einen** Trainer, ein Trainer leitet **viele** Kurse → 1 beim Trainer, n beim Kurs.',
      '[4] Der Primärschlüssel kennzeichnet jeden Kurs eindeutig – die Kursnummer. Die Trainernummer gehört zum Trainer.',
    ],
  },
  {
    id: 'er-q3',
    art: 'fragen',
    raum: ['AP2'],
    sp: 'AP2-2-2-1',
    titel: 'Attribut an Entität oder Beziehung?',
    text: 'Ein Online-Shop hat die m:n-Beziehung **Bestellung – enthält – Artikel**. Eine Werkstatt hat die m:n-Beziehung **Mechaniker – arbeitet an – Auftrag**. Wohin gehört jedes Attribut?',
    felder: [
      { id: 'a', label: 'Bestellmenge eines Artikels', optionen: ['Bestellung', 'Artikel', 'Beziehung „enthält"'], erwartet: 'Beziehung „enthält"' },
      { id: 'b', label: 'Listenpreis laut aktueller Preisliste', optionen: ['Bestellung', 'Artikel', 'Beziehung „enthält"'], erwartet: 'Artikel' },
      { id: 'c', label: 'Bestelldatum', optionen: ['Bestellung', 'Artikel', 'Beziehung „enthält"'], erwartet: 'Bestellung' },
      { id: 'd', label: 'Arbeitsstunden eines Mechanikers an einem bestimmten Auftrag', optionen: ['Mechaniker', 'Auftrag', 'Beziehung „arbeitet an"'], erwartet: 'Beziehung „arbeitet an"' },
      { id: 'e', label: 'Qualifikation des Mechanikers (z. B. Elektrik)', optionen: ['Mechaniker', 'Auftrag', 'Beziehung „arbeitet an"'], erwartet: 'Mechaniker' },
      {
        id: 'f',
        label: 'Woran erkennst du ein Attribut der Beziehung?',
        optionen: [
          'Sein Wert ändert sich nie.',
          'Sein Wert ist erst bestimmt, wenn man beide Partner kennt – ein Exemplar jeder Seite.',
          'Es ist immer ein Datum.',
          'Es ist der Primärschlüssel einer der beiden Entitäten.',
        ],
        erwartet: 'Sein Wert ist erst bestimmt, wenn man beide Partner kennt – ein Exemplar jeder Seite.',
      },
    ],
    loesung: [
      'Frage: **Wovon hängt der Wert ab?** Die Menge hängt von der Bestellung **und** vom Artikel ab – also an die Beziehung.',
      'Der Listenpreis gilt für den Artikel, egal in welcher Bestellung → Artikel. Das Bestelldatum gilt für die ganze Bestellung → Bestellung.',
      'Die Stunden gehören zum Paar Mechaniker + Auftrag; die Qualifikation beschreibt nur den Mechaniker.',
      'Attribute an Beziehungen kommen fast nur bei **m:n** vor – bei 1:n kann man sie meist der n-Seite zuordnen.',
    ],
  },
  {
    id: 'er-f2',
    art: 'fehler',
    raum: ['AP2'],
    sp: 'AP2-2-2-1',
    titel: 'Fehler in der Projektzeiterfassung',
    text: 'Mitarbeiter (Personalnummer, Name) arbeiten an Projekten (Projektnummer, Bezeichnung). Ein Mitarbeiter arbeitet an mehreren Projekten, an einem Projekt arbeiten mehrere Mitarbeiter. Für jeden Mitarbeiter wird **je Projekt** die Summe der Stunden gespeichert. Jedes Projekt wird von genau einem Kunden (Kundennummer, Firmenname) beauftragt; ein Kunde kann mehrere Projekte beauftragen. Prüfe die Stellen 1–4.',
    diagramm: projekte(true),
    felder: [
      {
        id: '1',
        label: 'Attribut „Stunden" am Mitarbeiter',
        optionen: ['korrekt', 'gehört an die Beziehung „arbeitet an"', 'gehört zum Projekt', 'muss Primärschlüssel sein'],
        erwartet: 'gehört an die Beziehung „arbeitet an"',
      },
      {
        id: '2',
        label: 'Attribut „Firmenname" am Projekt',
        optionen: ['korrekt', 'muss Primärschlüssel von „Projekt" sein', 'gehört an die Beziehung „arbeitet an"', 'doppelt gespeichert: gehört nur zum Kunden'],
        erwartet: 'doppelt gespeichert: gehört nur zum Kunden',
      },
      {
        id: '3',
        label: 'Kardinalitäten an „beauftragt"',
        optionen: ['korrekt', 'falsch: 1 beim Kunden, n beim Projekt', 'falsch: 1 beim Projekt, n beim Kunden', 'falsch: muss 1:1 sein'],
        erwartet: 'falsch: 1 beim Kunden, n beim Projekt',
      },
      {
        id: '4',
        label: 'Primärschlüssel „Projektnummer"',
        optionen: ['korrekt', '„Bezeichnung" wäre der bessere Primärschlüssel', 'muss an der Beziehung hängen'],
        erwartet: 'korrekt',
      },
    ],
    loesung: [
      '[1] Die Stunden hängen vom Mitarbeiter **und** vom Projekt ab. Am Mitarbeiter könnte man nur eine Zahl für alle Projekte speichern → Attribut an die Beziehung „arbeitet an".',
      '[2] Der Firmenname beschreibt den Kunden. Welcher Kunde zum Projekt gehört, zeigt die Beziehung „beauftragt" – am Projekt wäre er doppelt gespeichert.',
      '[3] Ein Kunde beauftragt **viele** Projekte, ein Projekt hat **einen** Kunden → 1:n mit der 1 beim Kunden.',
      '[4] Richtig: Die Projektnummer ist eindeutig, eine Bezeichnung kann sich wiederholen oder ändern.',
    ],
    muster: projekte(false),
  },

  // ---------- Zeichnen ----------
  {
    id: 'er-z1',
    art: 'zeichnen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-1',
    titel: 'Fahrschule erweitern',
    text: 'Das begonnene ER-Modell einer Fahrschule zeigt Fahrlehrer und Fahrschüler: Jeder Fahrschüler hat genau einen festen Fahrlehrer, ein Fahrlehrer betreut viele Fahrschüler. Erweitere das Modell:\n- Jedem Fahrlehrer ist genau ein **Fahrzeug** fest zugeordnet, jedes Fahrzeug genau einem Fahrlehrer. Ein Fahrzeug hat eine eindeutige Fahrzeugnummer, ein Kennzeichen und ein Modell.\n- Fahrschüler besuchen **Theorieunterrichte** (Unterrichtsnummer, Datum, Thema). Ein Fahrschüler besucht viele Theorieunterrichte, an einem Theorieunterricht nehmen viele Fahrschüler teil.\n- Trage alle Kardinalitäten ein und unterstreiche die Primärschlüssel.',
    vorlage: {
      breite: 620,
      hoehe: 280,
      knoten: [
        ent('fl', 40, 130, 'Fahrlehrer'),
        bez('betreut', 230, 125, 'betreut'),
        ent('fs', 420, 130, 'Fahrschüler'),
        pk('lnr', 4, 30, 'Lehrernummer'),
        att('lname', 130, 30, 'Name'),
        pk('snr', 360, 30, 'Schülernummer'),
        att('sname', 500, 30, 'Name'),
        att('geb', 440, 230, 'Geburtsdatum'),
      ],
      kanten: [
        lin('fl', 'betreut', { textVon: '1' }),
        lin('betreut', 'fs', { textNach: 'n' }),
        lin('lnr', 'fl'),
        lin('lname', 'fl'),
        lin('snr', 'fs'),
        lin('sname', 'fs'),
        lin('geb', 'fs'),
      ],
    },
    muster: {
      breite: 930,
      hoehe: 520,
      knoten: [
        ent('fl', 40, 150, 'Fahrlehrer'),
        bez('betreut', 230, 145, 'betreut'),
        ent('fs', 420, 150, 'Fahrschüler'),
        bez('besucht', 605, 145, 'besucht'),
        ent('tu', 780, 150, 'Theorieunterricht', { w: 136 }),
        bez('nutzt', 45, 270, 'nutzt'),
        ent('fzg', 40, 390, 'Fahrzeug'),
        pk('lnr', 4, 50, 'Lehrernummer'),
        att('lname', 130, 50, 'Name'),
        pk('snr', 360, 50, 'Schülernummer'),
        att('sname', 500, 50, 'Name'),
        att('geb', 440, 260, 'Geburtsdatum'),
        pk('unr', 744, 50, 'Unterrichtsnummer'),
        att('datum', 740, 260, 'Datum'),
        att('thema', 840, 260, 'Thema'),
        pk('fnr', 200, 350, 'Fahrzeugnummer'),
        att('kz', 200, 430, 'Kennzeichen'),
        att('modell', 56, 470, 'Modell'),
      ],
      kanten: [
        lin('fl', 'betreut', { textVon: '1' }),
        lin('betreut', 'fs', { textNach: 'n' }),
        lin('fs', 'besucht', { textVon: 'm' }),
        lin('besucht', 'tu', { textNach: 'n' }),
        lin('fl', 'nutzt', { textVon: '1' }),
        lin('nutzt', 'fzg', { textNach: '1' }),
        lin('lnr', 'fl'),
        lin('lname', 'fl'),
        lin('snr', 'fs'),
        lin('sname', 'fs'),
        lin('geb', 'fs'),
        lin('unr', 'tu'),
        lin('datum', 'tu'),
        lin('thema', 'tu'),
        lin('fnr', 'fzg'),
        lin('kz', 'fzg'),
        lin('modell', 'fzg'),
      ],
    },
    pruefliste: [
      'Neue Entitäten **Fahrzeug** und **Theorieunterricht** als Rechtecke',
      'Beziehung (Raute) zwischen Fahrlehrer und Fahrzeug mit **1** und **1**',
      'Beziehung (Raute) zwischen Fahrschüler und Theorieunterricht mit **m** und **n**',
      'Attribute als Ellipsen an der richtigen Entität: Kennzeichen und Modell am Fahrzeug, Datum und Thema am Theorieunterricht',
      'Primärschlüssel **Fahrzeugnummer** und **Unterrichtsnummer** unterstrichen',
      'Keine Angabe doppelt: kein Lehrername am Fahrzeug, keine Schülernamen am Theorieunterricht',
      'Beziehungen mit einem Verb benannt (z. B. „nutzt", „besucht")',
    ],
    hinweise: 'Die Beziehungsnamen darfst du frei wählen, solange sie den Zusammenhang beschreiben („fährt", „ist zugeordnet", „nimmt teil an"). Wo die Ellipsen genau liegen, ist egal – wichtig ist, an welcher Entität sie hängen.',
  },
  {
    id: 'er-z2',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-2-1',
    titel: 'Elektrogroßhandel vollständig',
    text: 'Ein Elektrogroßhandel will seine Aufträge erfassen. Zeichne das ER-Modell mit allen Attributen, Primärschlüsseln und Kardinalitäten.\n- **Kunden** (Kundennummer, Firma, Ort) erteilen Aufträge. Ein **Auftrag** (Auftragsnummer, Datum) gehört zu genau einem Kunden.\n- Ein Auftrag umfasst mehrere **Artikel** (Artikelnummer, Bezeichnung, Preis); ein Artikel kommt in vielen Aufträgen vor. Je Artikel im Auftrag wird die **Menge** gespeichert.\n- Jeder Artikel wird von genau einem **Lieferanten** (Lieferantennummer, Name) bezogen; ein Lieferant liefert viele Artikel.',
    muster: {
      breite: 960,
      hoehe: 470,
      knoten: [
        ent('kunde', 30, 140, 'Kunde'),
        bez('erteilt', 210, 135, 'erteilt'),
        ent('auftrag', 370, 140, 'Auftrag'),
        bez('umfasst', 560, 135, 'umfasst'),
        ent('artikel', 720, 140, 'Artikel'),
        bez('liefert', 725, 270, 'liefert'),
        ent('lief', 720, 390, 'Lieferant'),
        pk('knr', 4, 40, 'Kundennummer'),
        att('firma', 140, 40, 'Firma'),
        att('ort', 30, 250, 'Ort'),
        pk('anr', 320, 40, 'Auftragsnummer'),
        att('datum', 470, 40, 'Datum'),
        att('menge', 573, 250, 'Menge'),
        pk('artnr', 640, 40, 'Artikelnummer'),
        att('bez', 790, 40, 'Bezeichnung'),
        att('preis', 860, 200, 'Preis'),
        pk('lnr', 520, 395, 'Lieferantennummer'),
        att('lname', 870, 395, 'Name'),
      ],
      kanten: [
        lin('kunde', 'erteilt', { textVon: '1' }),
        lin('erteilt', 'auftrag', { textNach: 'n' }),
        lin('auftrag', 'umfasst', { textVon: 'm' }),
        lin('umfasst', 'artikel', { textNach: 'n' }),
        lin('artikel', 'liefert', { textVon: 'n' }),
        lin('liefert', 'lief', { textNach: '1' }),
        lin('knr', 'kunde'),
        lin('firma', 'kunde'),
        lin('ort', 'kunde'),
        lin('anr', 'auftrag'),
        lin('datum', 'auftrag'),
        lin('menge', 'umfasst'),
        lin('artnr', 'artikel'),
        lin('bez', 'artikel'),
        lin('preis', 'artikel'),
        lin('lnr', 'lief'),
        lin('lname', 'lief'),
      ],
    },
    pruefliste: [
      'Vier Entitäten: **Kunde**, **Auftrag**, **Artikel**, **Lieferant**',
      'Kunde – Auftrag als **1:n** (1 beim Kunden, n beim Auftrag)',
      'Auftrag – Artikel als **m:n**',
      'Artikel – Lieferant als **1:n** (n beim Artikel, 1 beim Lieferanten)',
      '**Menge** hängt an der Beziehung zwischen Auftrag und Artikel – nicht an einer Entität',
      'Primärschlüssel unterstrichen: Kundennummer, Auftragsnummer, Artikelnummer, Lieferantennummer',
      'Alle übrigen Attribute an der richtigen Entität, keines doppelt (z. B. kein Lieferantenname am Artikel)',
      'Keine Fremdschlüssel als Attribute eingezeichnet – die Beziehungen reichen',
    ],
    hinweise: 'Auch richtig: die Menge als Ellipse direkt neben der Raute „umfasst". Falsch wäre die Menge am Artikel – dann hätte ein Artikel in allen Aufträgen dieselbe Menge.',
  },
  {
    id: 'er-z3',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-2-1',
    titel: 'Arztpraxis erweitern',
    text: 'Das vorhandene Modell einer Arztpraxis speichert Patienten und ihre Termine. Erweitere es:\n- Jeder Termin findet bei genau einem **Arzt** statt (Arztnummer, Name, Fachrichtung); ein Arzt hat viele Termine.\n- In einem Termin können mehrere **Leistungen** erbracht werden (Leistungsnummer, Bezeichnung, Gebühr); eine Leistung kommt in vielen Terminen vor. Je Termin und Leistung wird die **Anzahl** gespeichert.\n- Achte darauf, keine Angabe doppelt zu speichern.',
    vorlage: {
      breite: 600,
      hoehe: 290,
      knoten: [
        ent('pat', 30, 130, 'Patient'),
        bez('hat', 220, 125, 'hat'),
        ent('termin', 410, 130, 'Termin'),
        pk('pnr', 4, 30, 'Patientennummer'),
        att('pname', 170, 30, 'Name'),
        att('geb', 30, 230, 'Geburtsdatum'),
        pk('tnr', 360, 30, 'Terminnummer'),
        att('datum', 500, 30, 'Datum'),
        att('uhr', 440, 230, 'Uhrzeit'),
      ],
      kanten: [
        lin('pat', 'hat', { textVon: '1' }),
        lin('hat', 'termin', { textNach: 'n' }),
        lin('pnr', 'pat'),
        lin('pname', 'pat'),
        lin('geb', 'pat'),
        lin('tnr', 'termin'),
        lin('datum', 'termin'),
        lin('uhr', 'termin'),
      ],
    },
    muster: {
      breite: 920,
      hoehe: 520,
      knoten: [
        ent('pat', 30, 150, 'Patient'),
        bez('hat', 210, 145, 'hat'),
        ent('termin', 380, 150, 'Termin'),
        bez('umfasst', 570, 145, 'umfasst'),
        ent('leistung', 750, 150, 'Leistung'),
        bez('fuehrt', 385, 280, 'führt durch'),
        ent('arzt', 380, 410, 'Arzt'),
        pk('pnr', 4, 50, 'Patientennummer'),
        att('pname', 160, 50, 'Name'),
        att('geb', 30, 260, 'Geburtsdatum'),
        pk('tnr', 310, 50, 'Terminnummer'),
        att('datum', 450, 50, 'Datum'),
        att('uhr', 270, 240, 'Uhrzeit'),
        att('anzahl', 583, 250, 'Anzahl', { hervor: true }),
        pk('lnr', 630, 50, 'Leistungsnummer'),
        att('gebuehr', 800, 50, 'Gebühr'),
        att('lbez', 760, 260, 'Bezeichnung'),
        pk('anr', 210, 420, 'Arztnummer'),
        att('aname', 400, 470, 'Name'),
        att('fach', 560, 420, 'Fachrichtung'),
      ],
      kanten: [
        lin('pat', 'hat', { textVon: '1' }),
        lin('hat', 'termin', { textNach: 'n' }),
        lin('termin', 'umfasst', { textVon: 'm' }),
        lin('umfasst', 'leistung', { textNach: 'n' }),
        lin('termin', 'fuehrt', { textVon: 'n' }),
        lin('fuehrt', 'arzt', { textNach: '1' }),
        lin('pnr', 'pat'),
        lin('pname', 'pat'),
        lin('geb', 'pat'),
        lin('tnr', 'termin'),
        lin('datum', 'termin'),
        lin('uhr', 'termin'),
        lin('anzahl', 'umfasst'),
        lin('lnr', 'leistung'),
        lin('gebuehr', 'leistung'),
        lin('lbez', 'leistung'),
        lin('anr', 'arzt'),
        lin('aname', 'arzt'),
        lin('fach', 'arzt'),
      ],
    },
    pruefliste: [
      'Neue Entitäten **Arzt** und **Leistung** als Rechtecke mit ihren Attributen',
      'Termin – Arzt als **1:n**: n beim Termin, 1 beim Arzt',
      'Termin – Leistung als **m:n**',
      '**Anzahl** als Attribut an der Beziehung zwischen Termin und Leistung',
      'Primärschlüssel **Arztnummer** und **Leistungsnummer** unterstrichen',
      'Fachrichtung nur beim Arzt, Gebühr nur bei der Leistung – nichts zusätzlich am Termin',
      'Das vorhandene Modell (Patient – Termin, 1:n) ist unverändert übernommen',
    ],
    hinweise: 'Die Gebühr gehört zur Leistung (sie gilt für jeden Termin gleich). Wird je Termin ein abweichender Betrag berechnet, käme dieser Betrag zusätzlich an die Beziehung – das verlangt der Text hier nicht.',
  },
];

export default { spickzettel, notation, aufgaben };
