// Modus „Masken & Mockups" – Format: siehe ../README.md

export const spickzettel = `- **Gruppieren**: Zusammengehöriges in einen Rahmen mit Titel (z. B. Person, Adresse, Zahlung)
- **Einheitlich**: Beschriftungen immer an derselben Stelle, Felder bündig, Schaltflächen gleich groß und immer am selben Ort (z. B. unten rechts)
- **Verständlich**: Begriffe der Nutzer, Pflichtfelder mit * und Hinweis; Fehlermeldung sagt, **was** falsch ist und **wie** es richtig geht
- **Corporate Identity**: Logo, Hausfarben und Hausschrift des Unternehmens in jeder Maske gleich
- **Barrierefreiheit**: genug Kontrast, Schrift vergrößerbar, alles per Tastatur bedienbar, Information **nie nur über Farbe**
- **Mockup**: Skizze der Oberfläche ohne Funktion → frühe Rückmeldung, Missverständnisse früh sichtbar, Änderungen billig
- **Prototyp**: ausprobierbares Vorab-Modell; sinnvoll, wenn Anforderungen oder Bedienung noch unklar sind`;

// ---------- Bausteine ----------

const kb = (id, stil, x, y, w, h, text, extra = {}) => ({ id, typ: 'kasten', stil, x, y, w, h, ...(text !== undefined ? { text } : {}), ...extra });
const tx = (id, x, y, w, text, extra = {}) => kb(id, 'text', x, y, w, extra.h ?? 28, text, extra);
const PUNKT = (id, x, y, extra = {}) => ({ id, typ: 'text', x, y, text: '', ...extra });
const notiz = (id, x, y, text) => ({ id, typ: 'text', x, y, text, anker: 'start', klein: true });
const li = (von, nach, extra = {}) => ({ von, nach, typ: 'linie', ...extra });

const ROT = '#c62828';
const GRUEN = '#2e9e4f';
const ROSA = '#f6caca';
const PLATZ = '#e3e8eb';

// ---------- Notation ----------

const beispielMaske = {
  breite: 840,
  hoehe: 442,
  rahmen: [{ typ: 'maske', x: 16, y: 16, w: 520, h: 410, text: 'Kundendaten erfassen' }],
  knoten: [
    kb('leiste', 'leiste', 16, 46, 520, 36, 'Muster GmbH'),
    kb('logo', 'bild', 460, 52, 64, 24, 'Logo'),
    kb('gPerson', 'rahmen', 32, 100, 488, 124, 'Person'),
    tx('lAnrede', 48, 114, 90, 'Anrede'),
    kb('rFrau', 'radio', 150, 114, 70, 28, 'Frau', { an: true }),
    kb('rHerr', 'radio', 226, 114, 70, 28, 'Herr'),
    kb('rDiv', 'radio', 302, 114, 80, 28, 'divers'),
    tx('lName', 48, 148, 90, 'Name *'),
    kb('fName', 'feld', 150, 148, 350, 28, 'Nachname'),
    tx('lMail', 48, 182, 90, 'E-Mail *'),
    kb('fMail', 'feld', 150, 182, 350, 28, 'name@beispiel.de'),
    kb('gVertrag', 'rahmen', 32, 244, 488, 92, 'Vertrag'),
    tx('lTarif', 48, 260, 90, 'Tarif'),
    kb('aTarif', 'auswahl', 150, 260, 200, 28, 'Basis'),
    kb('cNews', 'check', 150, 298, 220, 24, 'Newsletter abonnieren'),
    tx('pflicht', 32, 350, 120, '* Pflichtfeld', { h: 20 }),
    kb('kAbbr', 'knopf', 300, 380, 100, 32, 'Abbrechen', { zweit: true }),
    kb('kSpeich', 'knopf', 410, 380, 110, 32, 'Speichern'),
    PUNKT('p1', 556, 64),
    notiz('n1', 566, 64, 'Kopfleiste: Logo, Hausfarbe, Hausschrift (CI)'),
    PUNKT('p2', 556, 106),
    notiz('n2', 566, 106, 'Gruppe: Rahmen mit Titel'),
    PUNKT('p3', 556, 128),
    notiz('n3', 566, 132, 'Optionsfelder: genau eine Wahl'),
    PUNKT('p4', 556, 162),
    notiz('n4', 566, 162, 'Beschriftung links, Eingabefeld rechts'),
    PUNKT('p5', 556, 274),
    notiz('n5', 566, 274, 'Auswahlliste (Dropdown)'),
    PUNKT('p6', 556, 310),
    notiz('n6', 566, 310, 'Kontrollkästchen: an/aus'),
    PUNKT('p7', 556, 360),
    notiz('n7', 566, 360, '* kennzeichnet Pflichtfelder'),
    PUNKT('p8', 556, 396),
    notiz('n8', 566, 396, 'Hauptaktion farbig, Nebenaktion schlicht'),
  ],
  kanten: [
    li('p1', 'leiste'),
    li('p2', 'gPerson', { nachSeite: 'rechts:-56' }),
    li('p3', 'rDiv'),
    li('p4', 'fName'),
    li('p5', 'aTarif'),
    li('p6', 'cNews'),
    li('p7', 'pflicht'),
    li('p8', 'kSpeich'),
  ],
};

export const notation = {
  text: 'Ein **Mockup** zeigt, wo welche Elemente einer Maske stehen – ohne echte Funktion. Für die Skizze reichen wenige Bausteine: Beschriftung, Eingabefeld, Auswahlliste, Optionsfeld, Kontrollkästchen, Schaltfläche, Anzeige, Diagramm und Rahmen für Gruppen.',
  bilder: [{ titel: 'Beispiel: Kundendaten erfassen', diagramm: beispielMaske }],
  punkte: [
    '**Eingabefeld** für freie Eingaben (Name, E-Mail); **Auswahlliste**, wenn es feste Werte gibt; **Optionsfelder** (rund) für genau eine Wahl; **Kontrollkästchen** (eckig) für an/aus.',
    '**Datumsauswahl** (Kalender) statt freier Eingabe – so entstehen keine Formatfehler. **Wertanzeige** in großer Schrift für den wichtigsten Wert, **Diagramm** für Verläufe.',
    '**Softwareergonomie:** gruppieren, einheitlich anordnen, verständlich beschriften, Pflichtfelder kennzeichnen, klare Fehlermeldungen („Bitte gib das Datum als TT.MM.JJJJ ein").',
    '**Corporate Identity:** Logo, Farben und Schrift des Unternehmens – in jeder Maske an derselben Stelle.',
    '**Barrierefreiheit:** dunkle Schrift auf hellem Grund (Kontrast), Schrift vergrößerbar, Bedienung mit Tab und Enter, Zustände zusätzlich als Text oder Symbol statt nur rot/grün.',
    '**Grundsätze der Dialoggestaltung** (DIN EN ISO 9241-110), u. a.: Aufgabenangemessenheit, Selbstbeschreibungsfähigkeit, Erwartungskonformität, Steuerbarkeit, Fehlertoleranz.',
    '**Prototyp:** ausprobierbares Modell. **Horizontal** = viele Masken, aber ohne Funktion dahinter; **vertikal** = eine Funktion vollständig durch alle Schichten. **Wegwerfprototyp** wird nach der Klärung verworfen, **evolutionärer** Prototyp wird zum Produkt weiterentwickelt.',
  ],
};

// ---------- Aufgaben ----------

const OPT_MK1 = ['korrekt', 'zu wenig Kontrast', 'Information nur über Farbe', 'Beschriftung fehlt', 'Schaltflächen uneinheitlich'];
const OPT_MK2 = ['korrekt', 'Corporate Identity nicht eingehalten', 'Information nur über Farbe', 'Fehlermeldung nicht verständlich'];
const OPT_BEREICH = ['Softwareergonomie', 'Corporate Identity', 'Barrierefreiheit'];
const OPT_DIALOG = ['Aufgabenangemessenheit', 'Selbstbeschreibungsfähigkeit', 'Erwartungskonformität', 'Steuerbarkeit', 'Fehlertoleranz'];
const OPT_BS = ['Wertanzeige in großer Schrift', 'Liniendiagramm', 'Datumsauswahl', 'Schalter / Kontrollkästchen', 'Freitextfeld'];
const ANZ_BS = { 'Wertanzeige in großer Schrift': 'Wertanzeige', Liniendiagramm: 'Diagramm', Datumsauswahl: 'Datumsauswahl', 'Schalter / Kontrollkästchen': 'Schalter', Freitextfeld: 'Freitext' };

// Tabellenzeilen aus Textkästen (Zeilenhöhe 24)
const zeile = (id, y, werte, xs, extra = {}) => werte.map((w, i) => tx(`${id}${i}`, xs[i], y, 100, w, { h: 24, ...extra }));

export const aufgaben = [
  // ---------- AP1 ----------
  {
    id: 'mk-f1',
    art: 'fehler',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-3',
    titel: 'Maske „Urlaubsantrag" beurteilen',
    text: 'Ein Azubi hat die Maske für den Urlaubsantrag entworfen. Beurteile die markierten Stellen 1–5 nach Softwareergonomie und Barrierefreiheit.',
    diagramm: {
      breite: 600,
      hoehe: 400,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 560, h: 370, text: 'Urlaubsantrag' }],
      knoten: [
        tx('lMa', 40, 60, 100, 'Mitarbeiter'),
        kb('fMa', 'feld', 150, 60, 220, 28, 'Max Muster'),
        { id: 'rest', typ: 'text', x: 400, y: 74, text: 'Resturlaub: 12 Tage', anker: 'start', klein: true },
        PUNKT('restM', 514, 62, { marke: 1 }),
        kb('gZeit', 'rahmen', 32, 110, 528, 70, 'Zeitraum', { marke: 5 }),
        tx('lVon', 48, 132, 40, 'Von'),
        kb('fVon', 'feld', 96, 132, 160, 28, 'TT.MM.JJJJ', { farbe: ROSA }),
        tx('lBis', 290, 132, 34, 'Bis'),
        kb('fBis', 'feld', 344, 132, 160, 28, 'TT.MM.JJJJ', { farbe: ROSA, marke: 2 }),
        tx('lArt', 40, 200, 100, 'Urlaubsart'),
        kb('aArt', 'auswahl', 150, 200, 240, 28, 'Erholungsurlaub', { farbe: ROSA }),
        kb('aOhne', 'auswahl', 150, 240, 240, 28, 'Bitte wählen …', { marke: 3 }),
        tx('hinweis', 40, 282, 420, 'Rot hinterlegte Felder müssen ausgefüllt werden.', { h: 20 }),
        kb('kSenden', 'knopf', 40, 322, 150, 40, 'Senden'),
        kb('kAbbr', 'knopf', 400, 332, 70, 22, 'abbrechen', { zweit: true, groesse: 10 }),
        kb('kVerw', 'knopf', 480, 328, 80, 30, 'Verwerfen', { farbe: ROT, marke: 4 }),
      ],
    },
    felder: [
      { id: '1', label: 'Text „Resturlaub: 12 Tage"', optionen: OPT_MK1, erwartet: 'zu wenig Kontrast' },
      { id: '2', label: 'Rot hinterlegte Pflichtfelder (z. B. „Bis")', optionen: OPT_MK1, erwartet: 'Information nur über Farbe' },
      { id: '3', label: 'Zweite Auswahlliste „Bitte wählen …"', optionen: OPT_MK1, erwartet: 'Beschriftung fehlt' },
      { id: '4', label: 'Schaltflächen „Senden", „abbrechen", „Verwerfen"', optionen: OPT_MK1, erwartet: 'Schaltflächen uneinheitlich' },
      { id: '5', label: 'Rahmen „Zeitraum" um Von und Bis', optionen: OPT_MK1, erwartet: 'korrekt' },
    ],
    loesung: [
      '[1] Hellgrau auf Weiß ist kaum lesbar – besonders bei Sehschwäche oder Sonnenlicht. Text braucht **ausreichenden Kontrast**.',
      '[2] Pflichtfelder nur durch rote Farbe zu kennzeichnen schließt Menschen mit Rot-Grün-Schwäche aus. Information **nie allein über Farbe**: zusätzlich ein * und der Hinweis „* Pflichtfeld".',
      '[3] Ohne Beschriftung weiß niemand, was hier gewählt werden soll (z. B. „Vertretung"). Jedes Feld braucht eine **verständliche Beschriftung** – Screenreader lesen sie auch vor.',
      '[4] Drei Größen, drei Farben, kein fester Platz. Schaltflächen sollen **gleich groß** sein und **einheitlich** an derselben Stelle stehen; nur die Hauptaktion wird hervorgehoben.',
      '[5] Richtig: Von und Bis gehören zusammen und sind in einem Rahmen mit Titel **gruppiert**.',
    ],
    muster: {
      breite: 600,
      hoehe: 400,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 560, h: 370, text: 'Urlaubsantrag' }],
      knoten: [
        tx('lMa', 40, 60, 100, 'Mitarbeiter'),
        kb('fMa', 'feld', 150, 60, 220, 28, 'Max Muster'),
        tx('rest', 400, 60, 150, 'Resturlaub: 12 Tage'),
        kb('gZeit', 'rahmen', 32, 110, 528, 70, 'Zeitraum'),
        tx('lVon', 48, 132, 40, 'Von *'),
        kb('fVon', 'feld', 96, 132, 160, 28, 'TT.MM.JJJJ'),
        tx('lBis', 290, 132, 50, 'Bis *'),
        kb('fBis', 'feld', 344, 132, 160, 28, 'TT.MM.JJJJ'),
        tx('lArt', 40, 200, 100, 'Urlaubsart *'),
        kb('aArt', 'auswahl', 150, 200, 240, 28, 'Erholungsurlaub'),
        tx('lVert', 40, 240, 100, 'Vertretung'),
        kb('aOhne', 'auswahl', 150, 240, 240, 28, 'Bitte wählen …'),
        tx('hinweis', 40, 282, 420, '* Pflichtfeld', { h: 20 }),
        kb('kAbbr', 'knopf', 330, 330, 110, 32, 'Abbrechen', { zweit: true }),
        kb('kSenden', 'knopf', 450, 330, 110, 32, 'Absenden'),
      ],
    },
  },
  {
    id: 'mk-f2',
    art: 'fehler',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-3',
    titel: 'Bestellverwaltung der Nordlicht GmbH',
    text: 'Die Nordlicht GmbH hat **Dunkelblau** als Hausfarbe; oben links steht in jeder Anwendung das **Firmenlogo**. Ein Dienstleister liefert diesen Entwurf für die Bestellverwaltung. Beurteile die Stellen 1–4.',
    diagramm: {
      breite: 612,
      hoehe: 362,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 580, h: 330, text: 'Bestellverwaltung' }],
      knoten: [
        kb('leiste', 'leiste', 16, 46, 580, 34, 'Bestellungen', { farbe: '#e8871e', marke: 1 }),
        kb('gSuche', 'rahmen', 32, 98, 548, 56, 'Suche', { marke: 4 }),
        tx('lKunde', 48, 112, 90, 'Kundenname'),
        kb('fKunde', 'feld', 150, 112, 280, 28, 'Mia'),
        kb('kSuche', 'knopf', 450, 112, 110, 28, 'Suchen'),
        kb('liste', 'liste', 32, 170, 548, 96),
        ...zeile('h', 170, ['Nr.', 'Kunde', 'Datum', 'Status'], [44, 120, 320, 470], { fett: true }),
        ...zeile('a', 194, ['4711', 'Bäckerei Kurz', '02.10.'], [44, 120, 320]),
        ...zeile('b', 218, ['4712', 'Autohaus Lenz', '03.10.'], [44, 120, 320]),
        ...zeile('c', 242, ['4713', 'Café Mira', '05.10.'], [44, 120, 320]),
        kb('s1', 'feld', 480, 199, 14, 14, undefined, { farbe: GRUEN }),
        kb('s2', 'feld', 480, 223, 14, 14, undefined, { farbe: ROT }),
        PUNKT('s2m', 512, 230, { marke: 2 }),
        kb('s3', 'feld', 480, 247, 14, 14, undefined, { farbe: GRUEN }),
        tx('fehler', 32, 280, 130, 'Fehler 0x80004005', { marke: 3 }),
        kb('kNeu', 'knopf', 450, 300, 130, 30, 'Neue Bestellung'),
      ],
    },
    felder: [
      { id: '1', label: 'Orange Kopfleiste ohne Logo', optionen: OPT_MK2, erwartet: 'Corporate Identity nicht eingehalten' },
      { id: '2', label: 'Spalte „Status" mit roten und grünen Quadraten', optionen: OPT_MK2, erwartet: 'Information nur über Farbe' },
      { id: '3', label: 'Meldung „Fehler 0x80004005"', optionen: OPT_MK2, erwartet: 'Fehlermeldung nicht verständlich' },
      { id: '4', label: 'Suchbereich: Beschriftung, Feld und Schaltfläche in einem Rahmen', optionen: OPT_MK2, erwartet: 'korrekt' },
      {
        id: 'v',
        label: 'Wie behebst du den Mangel an Stelle 2 am besten?',
        optionen: ['Rot und Grün tauschen', 'den Status zusätzlich als Text zeigen, z. B. „offen" und „geliefert"', 'die Quadrate kleiner machen', 'die Spalte „Status" weglassen'],
        erwartet: 'den Status zusätzlich als Text zeigen, z. B. „offen" und „geliefert"',
      },
    ],
    loesung: [
      '[1] **Corporate Identity** heißt: Hausfarbe, Logo und Schrift überall gleich. Orange statt Dunkelblau und das fehlende Logo passen nicht zum Unternehmen.',
      '[2] Rot und Grün sind für viele Menschen mit Farbsehschwäche nicht zu unterscheiden. Der Status muss **zusätzlich als Text oder Symbol** erkennbar sein.',
      '[3] Eine gute Fehlermeldung sagt in der Sprache des Nutzers, **was** passiert ist und **was er tun kann** – z. B. „Zu „Mia" wurde kein Kunde gefunden. Prüfe die Schreibweise."',
      '[4] Richtig: Was zusammen benutzt wird, steht **gruppiert** in einem Rahmen mit Titel.',
    ],
    muster: {
      breite: 612,
      hoehe: 362,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 580, h: 330, text: 'Bestellverwaltung' }],
      knoten: [
        kb('leiste0', 'leiste', 16, 46, 84, 34, ''),
        kb('leiste', 'leiste', 100, 46, 496, 34, 'Nordlicht GmbH – Bestellungen'),
        kb('logo', 'bild', 26, 51, 64, 24, 'Logo'),
        kb('gSuche', 'rahmen', 32, 98, 548, 56, 'Suche'),
        tx('lKunde', 48, 112, 90, 'Kundenname'),
        kb('fKunde', 'feld', 150, 112, 280, 28, 'Mia'),
        kb('kSuche', 'knopf', 450, 112, 110, 28, 'Suchen'),
        kb('liste', 'liste', 32, 170, 548, 96),
        ...zeile('h', 170, ['Nr.', 'Kunde', 'Datum', 'Status'], [44, 120, 320, 470], { fett: true }),
        ...zeile('a', 194, ['4711', 'Bäckerei Kurz', '02.10.'], [44, 120, 320]),
        ...zeile('b', 218, ['4712', 'Autohaus Lenz', '03.10.'], [44, 120, 320]),
        ...zeile('c', 242, ['4713', 'Café Mira', '05.10.'], [44, 120, 320]),
        kb('s1', 'feld', 470, 199, 14, 14, undefined, { farbe: GRUEN }),
        tx('t1', 490, 194, 80, 'geliefert', { h: 24 }),
        kb('s2', 'feld', 470, 223, 14, 14, undefined, { farbe: ROT }),
        tx('t2', 490, 218, 80, 'offen', { h: 24 }),
        kb('s3', 'feld', 470, 247, 14, 14, undefined, { farbe: GRUEN }),
        tx('t3', 490, 242, 80, 'geliefert', { h: 24 }),
        tx('fehler', 32, 276, 420, 'Zu „Mia" wurde kein Kunde gefunden. Prüfe die Schreibweise.'),
        kb('kNeu', 'knopf', 450, 306, 130, 30, 'Neue Bestellung'),
      ],
    },
  },
  {
    id: 'mk-q1',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-3',
    titel: 'Ergonomie, CI oder Barrierefreiheit?',
    text: 'Für die neue Kundenmaske einer Versicherung wurden Vorgaben gesammelt. Ordne jede Vorgabe dem Gesichtspunkt zu, zu dem sie gehört.',
    felder: [
      { id: 'a', label: 'Logo und Hausfarbe stehen in jeder Maske an derselben Stelle.', optionen: OPT_BEREICH, erwartet: 'Corporate Identity' },
      { id: 'b', label: 'Die Schrift lässt sich auf 200 % vergrößern, ohne dass Inhalte abgeschnitten werden.', optionen: OPT_BEREICH, erwartet: 'Barrierefreiheit' },
      { id: 'c', label: 'Die Adressfelder stehen gemeinsam in einem Rahmen „Anschrift".', optionen: OPT_BEREICH, erwartet: 'Softwareergonomie' },
      { id: 'd', label: 'Die Masken verwenden die Hausschrift aus dem Gestaltungshandbuch des Unternehmens.', optionen: OPT_BEREICH, erwartet: 'Corporate Identity' },
      { id: 'e', label: 'Ein Screenreader kann jedes Feld vorlesen, weil alle Felder eine Beschriftung haben.', optionen: OPT_BEREICH, erwartet: 'Barrierefreiheit' },
      { id: 'f', label: 'Die Fehlermeldung nennt das falsche Feld und sagt, wie die Eingabe richtig aussieht.', optionen: OPT_BEREICH, erwartet: 'Softwareergonomie' },
    ],
    loesung: [
      '**Corporate Identity** = das Erscheinungsbild des Unternehmens: Logo, Farben, Schrift – einheitlich in allen Anwendungen.',
      '**Barrierefreiheit** = auch Menschen mit Einschränkungen können die Maske nutzen: Vergrößern, Screenreader, Tastatur, Kontrast, nicht nur Farbe.',
      '**Softwareergonomie** = die Maske ist für alle leicht und fehlerarm zu bedienen: gruppieren, einheitlich anordnen, verständlich beschriften, hilfreiche Fehlermeldungen.',
    ],
  },
  {
    id: 'mk-q2',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-3',
    titel: 'Gute Fehlermeldungen, barrierefreie Masken',
    text: 'Beantworte die Fragen zur Gestaltung einer Anmeldemaske für ein Kundenportal.',
    felder: [
      {
        id: 'a',
        label: 'Das Geburtsdatum wurde als „7.3.90" eingegeben. Welche Fehlermeldung ist am besten?',
        optionen: ['Ungültige Eingabe!', 'Fehler 4021 im Feld GEB_DAT', 'Bitte gib das Geburtsdatum als TT.MM.JJJJ ein, z. B. 07.03.1990.', 'Das hat leider nicht geklappt.'],
        erwartet: 'Bitte gib das Geburtsdatum als TT.MM.JJJJ ein, z. B. 07.03.1990.',
      },
      {
        id: 'b',
        label: 'Was bedeutet „Bedienung mit der Tastatur"?',
        optionen: [
          'Alle Felder und Schaltflächen sind mit der Tab-Taste in sinnvoller Reihenfolge erreichbar und mit Enter oder Leertaste auslösbar.',
          'Die Maske hat ein Feld, in das man Text tippen kann.',
          'Die Maske zeigt eine Bildschirmtastatur an.',
          'Die Maus wird abgeschaltet.',
        ],
        erwartet: 'Alle Felder und Schaltflächen sind mit der Tab-Taste in sinnvoller Reihenfolge erreichbar und mit Enter oder Leertaste auslösbar.',
      },
      {
        id: 'c',
        label: 'Welche Textgestaltung erfüllt die Anforderung „ausreichender Kontrast"?',
        optionen: ['hellgraue Schrift auf weißem Grund', 'dunkelgraue Schrift auf weißem Grund', 'gelbe Schrift auf weißem Grund', 'hellblaue Schrift auf hellgrünem Grund'],
        erwartet: 'dunkelgraue Schrift auf weißem Grund',
      },
      {
        id: 'd',
        label: 'Ein ungültiges Feld wird bisher nur rot umrandet. Was ergänzt du?',
        optionen: ['einen dickeren roten Rahmen', 'ein Warnsymbol und einen Text unter dem Feld', 'einen Signalton', 'nichts – Rot ist eindeutig'],
        erwartet: 'ein Warnsymbol und einen Text unter dem Feld',
      },
      {
        id: 'e',
        label: 'Wo stehen die Beschriftungen in einer ergonomischen Maske?',
        optionen: ['mal links, mal rechts vom Feld – je nach Platz', 'immer an derselben Stelle zum Feld, z. B. links davor oder darüber', 'nur als Platzhalter im Feld, der beim Tippen verschwindet', 'gesammelt in einer Legende unter der Maske'],
        erwartet: 'immer an derselben Stelle zum Feld, z. B. links davor oder darüber',
      },
    ],
    loesung: [
      'Eine gute Fehlermeldung ist **verständlich** (keine Codes), **konkret** (welches Feld) und **hilft weiter** (wie es richtig geht, mit Beispiel).',
      'Tastaturbedienung brauchen Menschen, die keine Maus benutzen können – und sie macht geübte Nutzer schneller. Wichtig ist eine **sinnvolle Tab-Reihenfolge**.',
      'Kontrast heißt: Schrift und Hintergrund unterscheiden sich deutlich in der Helligkeit – dunkle Schrift auf hellem Grund.',
      'Ein roter Rahmen allein reicht nicht, weil manche Menschen Rot nicht erkennen. Ein **Symbol** und ein **Text** tragen dieselbe Information ohne Farbe.',
      'Einheitlich angeordnete Beschriftungen findet man schneller. Ein Platzhalter allein verschwindet beim Tippen – dann weiß niemand mehr, was ins Feld gehört.',
    ],
  },
  {
    id: 'mk-q3',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-3',
    titel: 'Grundsätze der Dialoggestaltung',
    text: 'Die Norm DIN EN ISO 9241-110 beschreibt Grundsätze für die Gestaltung von Dialogen. Ordne jede Eigenschaft eines Bestellportals dem passenden Grundsatz zu.',
    felder: [
      { id: 'a', label: 'Die Maske zeigt nur die Felder, die für die Bestellung gebraucht werden; das Bestelldatum wird automatisch eingetragen.', optionen: OPT_DIALOG, erwartet: 'Aufgabenangemessenheit' },
      { id: 'b', label: 'Neben dem Feld steht „Format: TT.MM.JJJJ"; ein Hinweistext erklärt, was in das Feld gehört.', optionen: OPT_DIALOG, erwartet: 'Selbstbeschreibungsfähigkeit' },
      { id: 'c', label: 'Strg+S speichert wie in anderen Programmen, „Speichern" steht in allen Masken unten rechts.', optionen: OPT_DIALOG, erwartet: 'Erwartungskonformität' },
      { id: 'd', label: 'Der Nutzer kann jederzeit einen Schritt zurückgehen oder den Vorgang abbrechen.', optionen: OPT_DIALOG, erwartet: 'Steuerbarkeit' },
      { id: 'e', label: 'Bei einer falschen Postleitzahl bleiben alle anderen Eingaben erhalten, das Feld wird markiert und erklärt.', optionen: OPT_DIALOG, erwartet: 'Fehlertoleranz' },
    ],
    loesung: [
      '**Aufgabenangemessenheit:** Der Dialog unterstützt die Aufgabe, ohne unnötige Schritte oder Felder.',
      '**Selbstbeschreibungsfähigkeit:** Der Nutzer erkennt jederzeit, was er tun kann und was erwartet wird.',
      '**Erwartungskonformität:** Der Dialog verhält sich so, wie man es gewohnt ist – einheitlich und wie in anderen Programmen.',
      '**Steuerbarkeit:** Der Nutzer bestimmt Ablauf und Tempo selbst (zurück, abbrechen, unterbrechen).',
      '**Fehlertoleranz** (in der neuen Fassung „Robustheit gegen Benutzungsfehler"): Fehler werden verhindert oder lassen sich mit wenig Aufwand beheben.',
    ],
  },

  // ---------- AP2 ----------
  {
    id: 'mk-e1',
    art: 'ergaenzen',
    raum: ['AP2'],
    sp: 'AP2-1-5-2',
    titel: 'Smart-Home-App: Mockup ergänzen',
    text: 'Die Seite „Wohnzimmer" einer Smart-Home-App soll zeigen: [1] die aktuelle Temperatur gut sichtbar, [2] den Temperaturverlauf der letzten sieben Tage, [3] die Wahl eines Tages, für den der Verlauf gezeigt wird, und [4] ob die Heizung ein- oder ausgeschaltet ist (zum Umschalten). Wähle für jeden Platzhalter den passenden Baustein.',
    diagramm: {
      breite: 332,
      hoehe: 572,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 300, h: 540, text: 'Wohnzimmer', geraet: true }],
      knoten: [
        tx('l1', 36, 56, 200, 'Ist-Temperatur', { h: 20 }),
        kb('p1', 'feld', 36, 80, 260, 60, '{1}', { farbe: PLATZ }),
        tx('l2', 36, 152, 200, 'Verlauf', { h: 20 }),
        kb('p2', 'feld', 36, 176, 260, 130, '{2}', { farbe: PLATZ }),
        tx('l3', 36, 318, 200, 'Tag', { h: 20 }),
        kb('p3', 'feld', 36, 342, 260, 36, '{3}', { farbe: PLATZ }),
        tx('l4', 36, 396, 120, 'Heizung', { h: 32 }),
        kb('p4', 'feld', 196, 396, 100, 32, '{4}', { farbe: PLATZ }),
        tx('l5', 36, 440, 120, 'Solltemperatur', { h: 32 }),
        kb('soll', 'auswahl', 196, 440, 100, 32, '21 °C'),
        kb('kSp', 'knopf', 36, 496, 260, 40, 'Speichern'),
      ],
    },
    felder: [
      { id: '1', label: 'Platzhalter für die aktuelle Temperatur', optionen: OPT_BS, erwartet: 'Wertanzeige in großer Schrift', anzeige: ANZ_BS },
      { id: '2', label: 'Platzhalter für den Verlauf der letzten sieben Tage', optionen: OPT_BS, erwartet: 'Liniendiagramm', anzeige: ANZ_BS },
      { id: '3', label: 'Platzhalter für die Wahl des Tages', optionen: OPT_BS, erwartet: 'Datumsauswahl', anzeige: ANZ_BS },
      { id: '4', label: 'Platzhalter für Heizung ein/aus', optionen: OPT_BS, erwartet: 'Schalter / Kontrollkästchen', anzeige: ANZ_BS },
      {
        id: 'v',
        label: 'Warum passt für den Verlauf ein Diagramm besser als eine Tabelle?',
        optionen: ['Ein Diagramm braucht keine Messwerte.', 'Steigen und Fallen der Temperatur sind auf einen Blick erkennbar.', 'Tabellen dürfen in Apps nicht verwendet werden.', 'Im Diagramm kann der Nutzer die Werte ändern.'],
        erwartet: 'Steigen und Fallen der Temperatur sind auf einen Blick erkennbar.',
      },
    ],
    loesung: [
      '[1] Der wichtigste Wert der Seite wird **nur angezeigt**, nicht eingegeben → Wertanzeige in großer Schrift.',
      '[2] Ein **Verlauf** über mehrere Tage → Liniendiagramm.',
      '[3] Für ein Datum nimmst du eine **Datumsauswahl** (Kalender). Freitext führt zu Formatfehlern.',
      '[4] Zwei Zustände (ein/aus) → **Schalter** oder Kontrollkästchen.',
      'Diagramme machen Entwicklungen sichtbar; Tabellen eignen sich für genaue Einzelwerte.',
    ],
    muster: {
      breite: 332,
      hoehe: 572,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 300, h: 540, text: 'Wohnzimmer', geraet: true }],
      knoten: [
        tx('l1', 36, 56, 200, 'Ist-Temperatur', { h: 20 }),
        tx('p1', 36, 80, 260, '21,5 °C', { h: 60, groesse: 34, fett: true }),
        tx('l2', 36, 152, 200, 'Verlauf', { h: 20 }),
        kb('p2', 'diagramm', 36, 176, 260, 130, 'Temperatur in °C'),
        tx('l3', 36, 318, 200, 'Tag', { h: 20 }),
        kb('p3', 'auswahl', 36, 342, 260, 36, 'Mo, 05.10.2026'),
        tx('l4', 36, 396, 120, 'Heizung', { h: 32 }),
        kb('p4', 'check', 196, 396, 100, 32, 'an', { an: true }),
        tx('l5', 36, 440, 120, 'Solltemperatur', { h: 32 }),
        kb('soll', 'auswahl', 196, 440, 100, 32, '21 °C'),
        kb('kSp', 'knopf', 36, 496, 260, 40, 'Speichern'),
      ],
    },
  },
  {
    id: 'mk-f3',
    art: 'fehler',
    raum: ['AP2'],
    sp: 'AP2-1-5-2',
    titel: 'Mockup der Zeiterfassungs-App',
    text: 'Mit der App stempeln Mitarbeiter auf dem Smartphone „Kommen" und „Gehen", sehen ihre heutige Arbeitszeit und können einen Tag wählen, um dessen Buchungen zu sehen. Beurteile das Mockup an den Stellen 1–4.',
    diagramm: {
      breite: 332,
      hoehe: 552,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 300, h: 520, text: 'Zeiterfassung', geraet: true }],
      knoten: [
        tx('l1', 36, 56, 200, 'Arbeitszeit heute', { h: 20 }),
        tx('wert', 36, 80, 140, '7:42 h', { h: 44, groesse: 32, fett: true, marke: 3 }),
        tx('l2', 36, 140, 200, 'Datum', { h: 20 }),
        kb('fDatum', 'feld', 36, 162, 260, 32, 'Datum eingeben, z. B. 2026-10-07', { marke: 1 }),
        tx('l3', 36, 210, 200, 'Buchungen', { h: 20 }),
        kb('tab', 'tabelle', 36, 232, 260, 132, undefined, { marke: 4 }),
        tx('kopf', 40, 232, 250, 'Datum Kommen Gehen Pause Soll Ist Saldo', { h: 22, groesse: 8 }),
        kb('kKommen', 'knopf', 196, 470, 48, 20, 'Kommen', { groesse: 9 }),
        kb('kGehen', 'knopf', 248, 470, 48, 20, 'Gehen', { groesse: 9, marke: 2 }),
      ],
    },
    felder: [
      {
        id: '1',
        label: 'Datumsfeld zum Eintippen',
        optionen: ['korrekt', 'besser eine Datumsauswahl (Kalender) – vermeidet Formatfehler', 'überflüssig – der Tag ist immer heute', 'muss eine Tabelle sein'],
        erwartet: 'besser eine Datumsauswahl (Kalender) – vermeidet Formatfehler',
      },
      {
        id: '2',
        label: 'Schaltflächen „Kommen" und „Gehen"',
        optionen: ['korrekt', 'zu klein und zu eng für die Bedienung mit dem Finger', 'müssen rot sein', 'gehören in die Titelleiste'],
        erwartet: 'zu klein und zu eng für die Bedienung mit dem Finger',
      },
      {
        id: '3',
        label: 'Anzeige „7:42 h" in großer Schrift',
        optionen: ['korrekt', 'zu groß – Werte immer klein darstellen', 'muss ein Eingabefeld sein', 'gehört ans Ende der Seite'],
        erwartet: 'korrekt',
      },
      {
        id: '4',
        label: 'Tabelle mit sieben Spalten',
        optionen: ['korrekt', 'zu viele Spalten für die schmale Anzeige – besser eine Liste mit wenigen Angaben je Buchung', 'braucht zusätzliche Spalten', 'muss ein Kontrollkästchen sein'],
        erwartet: 'zu viele Spalten für die schmale Anzeige – besser eine Liste mit wenigen Angaben je Buchung',
      },
      {
        id: 'v',
        label: 'Warum lohnt es sich, solche Mängel schon im Mockup zu finden?',
        optionen: ['Ein Mockup wird automatisch getestet.', 'Änderungen an einer Skizze kosten wenig – im fertigen Programm wären sie teuer.', 'Danach braucht man kein Pflichtenheft mehr.', 'Aus dem Mockup entsteht der Quellcode.'],
        erwartet: 'Änderungen an einer Skizze kosten wenig – im fertigen Programm wären sie teuer.',
      },
    ],
    loesung: [
      '[1] Ein Freitextfeld lässt beliebige Formate zu. Eine **Datumsauswahl** verhindert Fehleingaben und ist auf dem Smartphone schneller.',
      '[2] Die wichtigsten Aktionen der App müssen **groß** und gut mit dem Daumen treffbar sein – mit Abstand, damit man nicht versehentlich „Gehen" statt „Kommen" tippt.',
      '[3] Richtig: Der wichtigste Wert steht oben und **groß** – man erfasst ihn sofort.',
      '[4] Sieben Spalten passen nicht auf ein schmales Display; die Schrift wird unlesbar. Auf dem Smartphone zeigst du je Buchung nur **Uhrzeit und Art** in einer Liste.',
      'Genau dafür sind Mockups da: **Missverständnisse und Mängel früh** finden, solange Änderungen noch billig sind.',
    ],
    muster: {
      breite: 332,
      hoehe: 552,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 300, h: 520, text: 'Zeiterfassung', geraet: true }],
      knoten: [
        tx('l1', 36, 56, 200, 'Arbeitszeit heute', { h: 20 }),
        tx('wert', 36, 80, 140, '7:42 h', { h: 44, groesse: 32, fett: true }),
        tx('l2', 36, 140, 200, 'Datum', { h: 20 }),
        kb('fDatum', 'auswahl', 36, 162, 260, 32, 'Mi, 07.10.2026'),
        tx('l3', 36, 210, 200, 'Buchungen', { h: 20 }),
        kb('liste', 'liste', 36, 232, 260, 88),
        tx('b1', 46, 232, 240, '07:58   Kommen', { h: 22 }),
        tx('b2', 46, 254, 240, '12:01   Gehen', { h: 22 }),
        tx('b3', 46, 276, 240, '12:35   Kommen', { h: 22 }),
        kb('kKommen', 'knopf', 36, 460, 125, 52, 'Kommen'),
        kb('kGehen', 'knopf', 171, 460, 125, 52, 'Gehen'),
      ],
    },
  },
  {
    id: 'mk-q4',
    art: 'fragen',
    raum: ['AP2'],
    sp: 'AP2-1-5-2',
    titel: 'Mockup und Prototyping',
    text: 'Eine Praxis für Physiotherapie lässt eine App zur Terminbuchung entwickeln. Die Inhaberin kann sich noch nicht vorstellen, wie die Buchung ablaufen soll. Beantworte die Fragen.',
    felder: [
      {
        id: 'a',
        label: 'Was ist ein Mockup?',
        optionen: [
          'eine Skizze der Oberfläche, die zeigt, wo welche Elemente stehen – ohne echte Funktion',
          'die erste lauffähige Version mit allen Funktionen',
          'ein Testprotokoll der fertigen App',
          'das Datenmodell der App',
        ],
        erwartet: 'eine Skizze der Oberfläche, die zeigt, wo welche Elemente stehen – ohne echte Funktion',
      },
      {
        id: 'b',
        label: 'Welcher Vorteil eines Mockups stimmt?',
        optionen: [
          'Es ersetzt den Test der fertigen Software.',
          'Die Kundin gibt früh Rückmeldung; Missverständnisse fallen vor dem Programmieren auf.',
          'Aus dem Mockup wird automatisch der Quellcode erzeugt.',
          'Mit dem Mockup wird die Datenbank schneller.',
        ],
        erwartet: 'Die Kundin gibt früh Rückmeldung; Missverständnisse fallen vor dem Programmieren auf.',
      },
      {
        id: 'c',
        label: 'Was ist Prototyping?',
        optionen: [
          'früh ein ausprobierbares Modell der Software bauen, um Anforderungen mit dem Kunden zu klären',
          'die fertige Software an den Kunden ausliefern',
          'den Quellcode nachträglich dokumentieren',
          'Fehler im Betrieb beheben',
        ],
        erwartet: 'früh ein ausprobierbares Modell der Software bauen, um Anforderungen mit dem Kunden zu klären',
      },
      {
        id: 'd',
        label: 'Wann ist Prototyping besonders sinnvoll?',
        optionen: [
          'wenn alle Anforderungen feststehen und sich nicht ändern',
          'erst nach der Abnahme der Software',
          'wenn Anforderungen oder Bedienung noch unklar sind – wie hier bei der Inhaberin',
          'nur bei Programmen ohne Oberfläche',
        ],
        erwartet: 'wenn Anforderungen oder Bedienung noch unklar sind – wie hier bei der Inhaberin',
      },
      { id: 'e', label: 'Der Prototyp zeigt alle Masken der App zum Durchklicken, dahinter passiert aber noch nichts.', optionen: ['horizontaler Prototyp', 'vertikaler Prototyp'], erwartet: 'horizontaler Prototyp' },
      { id: 'f', label: 'Der Prototyp setzt nur „Termin buchen" um – von der Maske bis zur Speicherung in der Datenbank.', optionen: ['horizontaler Prototyp', 'vertikaler Prototyp'], erwartet: 'vertikaler Prototyp' },
      { id: 'g', label: 'Nach der Abstimmung wird der Prototyp verworfen; die App wird neu programmiert.', optionen: ['Wegwerfprototyp', 'evolutionärer Prototyp'], erwartet: 'Wegwerfprototyp' },
    ],
    loesung: [
      'Ein **Mockup** ist eine (oft handgezeichnete) Skizze der Oberfläche. Es kostet wenig und lässt sich schnell ändern.',
      'Vorteile: **frühe Rückmeldung** der Kundin, **Missverständnisse** werden vor dem Programmieren sichtbar, **Änderungen kosten wenig**.',
      'Beim **Prototyping** baust du früh ein ausprobierbares Modell. Das lohnt sich, wenn Anforderungen oder Bedienung **noch unklar** sind.',
      '**Horizontal** = eine Schicht in der Breite (z. B. alle Masken ohne Logik). **Vertikal** = ein Ausschnitt in der Tiefe (eine Funktion durch alle Schichten).',
      'Ein **Wegwerfprototyp** dient nur der Klärung; ein **evolutionärer** Prototyp wird Schritt für Schritt zum fertigen Produkt ausgebaut.',
    ],
  },

  // ---------- Zeichnen ----------
  {
    id: 'mk-z1',
    art: 'zeichnen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-3',
    titel: 'Maske „Störung melden" skizzieren',
    text: 'Skizziere für das IT-Service-Portal der Nordlicht GmbH (Hausfarbe Dunkelblau, Logo) eine Maske „Störung melden". Erfasst werden:\n- **Name** und **Abteilung** (aus einer festen Liste) der meldenden Person\n- **Art** der Störung: Hardware, Software oder Netzwerk (genau eine)\n- eine **Beschreibung** der Störung\n- ob die Störung **dringend** ist\nAlle Angaben außer „dringend" sind Pflicht. Achte auf Softwareergonomie, Corporate Identity und Barrierefreiheit.',
    muster: {
      breite: 600,
      hoehe: 500,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 560, h: 470, text: 'Störung melden' }],
      knoten: [
        kb('leiste', 'leiste', 16, 46, 560, 36, 'Nordlicht GmbH – IT-Service'),
        kb('logo', 'bild', 500, 52, 64, 24, 'Logo'),
        kb('gWer', 'rahmen', 32, 100, 528, 90, 'Wer meldet?'),
        tx('lName', 48, 116, 110, 'Name *'),
        kb('fName', 'feld', 170, 116, 370, 28, 'Vor- und Nachname'),
        tx('lAbt', 48, 150, 110, 'Abteilung *'),
        kb('aAbt', 'auswahl', 170, 150, 220, 28, 'Bitte wählen …'),
        kb('gStoer', 'rahmen', 32, 210, 528, 190, 'Störung'),
        tx('lArt', 48, 226, 110, 'Art *'),
        kb('rHw', 'radio', 170, 226, 100, 28, 'Hardware', { an: true }),
        kb('rSw', 'radio', 280, 226, 100, 28, 'Software'),
        kb('rNw', 'radio', 390, 226, 100, 28, 'Netzwerk'),
        tx('lBes', 48, 262, 110, 'Beschreibung *'),
        kb('fBes', 'feld', 170, 262, 370, 90, 'Was ist passiert?'),
        kb('cDr', 'check', 170, 362, 300, 24, 'dringend (Arbeit nicht möglich)'),
        tx('pflicht', 32, 414, 120, '* Pflichtfeld', { h: 20 }),
        kb('kAbbr', 'knopf', 330, 440, 110, 32, 'Abbrechen', { zweit: true }),
        kb('kSend', 'knopf', 450, 440, 110, 32, 'Absenden'),
      ],
    },
    pruefliste: [
      '**Kopfbereich** mit Logo und Firmenname in der Hausfarbe (Corporate Identity)',
      'Felder **gruppiert** (z. B. „Wer meldet?" und „Störung"), Gruppen mit Titel',
      'Jedes Feld hat eine **Beschriftung**, alle Beschriftungen stehen **einheitlich** (z. B. links, bündig)',
      '**Name** als Eingabefeld, **Abteilung** als Auswahlliste',
      '**Art** als drei Optionsfelder (genau eine Wahl), **dringend** als Kontrollkästchen',
      '**Beschreibung** als mehrzeiliges Eingabefeld',
      'Pflichtfelder mit **\\*** und Hinweis „* Pflichtfeld" – nicht nur farbig markiert',
      '**Schaltflächen** gleich groß, an fester Stelle (unten rechts), Hauptaktion „Absenden" hervorgehoben',
    ],
    hinweise: 'Beschriftungen über den Feldern sind genauso richtig wie links davor – wichtig ist, dass es überall gleich ist. Statt „dringend" als Kontrollkästchen ist auch eine Auswahl „Priorität" (niedrig/mittel/hoch) vertretbar.',
  },
  {
    id: 'mk-z2',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-1-5-2',
    titel: 'Energie-App: Mockup ergänzen',
    text: 'Die Vorlage zeigt die begonnene Seite „Mein Stromverbrauch" einer App für Mieter. Ergänze das Mockup um:\n- den **Verbrauch von heute** in kWh als gut sichtbare Anzeige\n- einen **Zeitraum** (von – bis), jeweils mit Datumsauswahl\n- die Wahl der Darstellung **Tag, Woche oder Monat**\n- ein **Diagramm** des Verbrauchs im gewählten Zeitraum\n- eine Schaltfläche zum **Export als PDF**',
    vorlage: {
      breite: 332,
      hoehe: 562,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 300, h: 530, text: 'Mein Stromverbrauch', geraet: true }],
      knoten: [
        tx('zaehler', 36, 52, 260, 'Zähler 1 – Wohnung 3.2', { h: 22, fett: true }),
        kb('n1', 'knopf', 24, 494, 90, 30, 'Übersicht', { zweit: true }),
        kb('n2', 'knopf', 121, 494, 90, 30, 'Verlauf'),
        kb('n3', 'knopf', 218, 494, 90, 30, 'Konto', { zweit: true }),
      ],
    },
    muster: {
      breite: 332,
      hoehe: 562,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 300, h: 530, text: 'Mein Stromverbrauch', geraet: true }],
      knoten: [
        tx('zaehler', 36, 52, 260, 'Zähler 1 – Wohnung 3.2', { h: 22, fett: true }),
        tx('lHeute', 36, 80, 200, 'Heute', { h: 18 }),
        tx('wert', 36, 100, 200, '7,4 kWh', { h: 44, groesse: 32, fett: true }),
        tx('lZeit', 36, 154, 200, 'Zeitraum', { h: 18 }),
        kb('von', 'auswahl', 36, 176, 125, 32, 'von 01.10.'),
        kb('bis', 'auswahl', 171, 176, 125, 32, 'bis 07.10.'),
        kb('rTag', 'radio', 36, 220, 70, 24, 'Tag', { an: true }),
        kb('rWoche', 'radio', 110, 220, 85, 24, 'Woche'),
        kb('rMonat', 'radio', 200, 220, 85, 24, 'Monat'),
        kb('dia', 'diagramm', 36, 256, 260, 160, 'kWh pro Tag'),
        kb('pdf', 'knopf', 36, 430, 260, 40, 'Als PDF exportieren', { zweit: true }),
        kb('n1', 'knopf', 24, 494, 90, 30, 'Übersicht', { zweit: true }),
        kb('n2', 'knopf', 121, 494, 90, 30, 'Verlauf'),
        kb('n3', 'knopf', 218, 494, 90, 30, 'Konto', { zweit: true }),
      ],
    },
    pruefliste: [
      '**Wertanzeige** „Heute: … kWh" groß und weit oben',
      '**Zeitraum** mit zwei Datumsauswahlen (von, bis), beide beschriftet',
      '**Tag / Woche / Monat** als Optionsfelder oder umschaltbare Reiter (genau eine Wahl)',
      '**Diagramm** mit erkennbarer Achse bzw. Beschriftung (z. B. „kWh pro Tag")',
      'Schaltfläche **„Als PDF exportieren"**',
      'Vorhandene Elemente (Zählerangabe, Navigation unten) bleiben erhalten',
      'Alles passt **untereinander** auf die schmale Smartphone-Seite, nichts überlappt',
    ],
    hinweise: 'Die Reihenfolge darf abweichen, solange die Zeitraumwahl in der Nähe des Diagramms steht, das sie steuert. Statt zweier Auswahlfelder ist auch ein Kalender mit markiertem Bereich richtig.',
  },
  {
    id: 'mk-z3',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-1-5-2',
    titel: 'Maske „Wareneingang" verbessern',
    text: 'Die Vorlage zeigt den ersten Entwurf der Maske „Wareneingang". Erfasst werden Lieferant, Lieferscheinnummer, Lieferdatum, Artikelnummer, Bezeichnung und Menge; „OK" bucht den Wareneingang. Notiere zuerst die Mängel, die du siehst. Skizziere dann einen verbesserten Entwurf, der alle Mängel behebt.',
    vorlage: {
      breite: 640,
      hoehe: 362,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 600, h: 330, text: 'Wareneingang' }],
      knoten: [
        tx('lArt', 40, 60, 90, 'Artikelnr.'),
        kb('fArt', 'feld', 130, 60, 140, 28),
        kb('fLief', 'feld', 300, 60, 160, 28),
        tx('lLief', 468, 60, 80, 'Lieferant'),
        tx('lDat', 40, 104, 100, 'Lieferdatum', { h: 20 }),
        kb('fDat', 'feld', 40, 126, 140, 28),
        { id: 'hin', typ: 'text', x: 210, y: 140, text: 'Menge prüfen!', anker: 'start', klein: true },
        kb('fMenge', 'feld', 360, 126, 120, 28),
        tx('lMenge', 488, 126, 60, 'Menge'),
        tx('lLs', 40, 186, 120, 'Lieferschein-Nr.'),
        kb('fLs', 'feld', 160, 186, 130, 28),
        tx('lBez', 320, 186, 100, 'Bezeichnung'),
        kb('fBez', 'feld', 420, 186, 170, 28),
        kb('kOk', 'knopf', 40, 284, 40, 22, 'OK', { groesse: 10 }),
        kb('kAbbr', 'knopf', 420, 272, 180, 44, 'ABBRUCH', { farbe: ROT }),
      ],
    },
    muster: {
      breite: 640,
      hoehe: 432,
      rahmen: [{ typ: 'maske', x: 16, y: 16, w: 600, h: 400, text: 'Wareneingang erfassen' }],
      knoten: [
        kb('gLief', 'rahmen', 32, 58, 568, 120, 'Lieferung'),
        tx('lLief', 48, 74, 130, 'Lieferant *'),
        kb('aLief', 'auswahl', 190, 74, 260, 28, 'Bitte wählen …'),
        tx('lLs', 48, 108, 130, 'Lieferschein-Nr. *'),
        kb('fLs', 'feld', 190, 108, 260, 28),
        tx('lDat', 48, 142, 130, 'Lieferdatum *'),
        kb('aDat', 'auswahl', 190, 142, 160, 28, '07.10.2026'),
        kb('gArt', 'rahmen', 32, 198, 568, 120, 'Artikel'),
        tx('lArt', 48, 214, 130, 'Artikelnr. *'),
        kb('fArt', 'feld', 190, 214, 160, 28),
        tx('lBez', 48, 248, 130, 'Bezeichnung'),
        kb('fBez', 'feld', 190, 248, 390, 28, 'wird aus der Artikelnummer gefüllt', { farbe: PLATZ }),
        tx('lMenge', 48, 282, 130, 'Menge *'),
        kb('fMenge', 'feld', 190, 282, 100, 28),
        tx('einheit', 300, 282, 60, 'Stück'),
        tx('hin', 32, 330, 420, 'Hinweis: Menge mit dem Lieferschein vergleichen.', { h: 20 }),
        tx('pflicht', 32, 356, 120, '* Pflichtfeld', { h: 20 }),
        kb('kAbbr', 'knopf', 370, 370, 110, 32, 'Abbrechen', { zweit: true }),
        kb('kOk', 'knopf', 490, 370, 110, 32, 'Buchen'),
      ],
    },
    pruefliste: [
      'Zusammengehöriges **gruppiert**: „Lieferung" (Lieferant, Lieferschein-Nr., Lieferdatum) und „Artikel" (Artikelnr., Bezeichnung, Menge)',
      'Jedes Feld hat eine Beschriftung, alle Beschriftungen stehen **einheitlich** auf derselben Seite (vorher mal links, mal rechts, beim Lieferanten gar keine passende)',
      'Felder **bündig** untereinander statt verstreut',
      '**Lieferant** als Auswahlliste, **Lieferdatum** als Datumsauswahl',
      'Hinweis zur Menge **gut lesbar** (dunkle Schrift) statt hellgrau',
      'Schaltflächen **gleich groß** und nebeneinander unten rechts; Hauptaktion verständlich beschriftet (z. B. „Buchen") und hervorgehoben, „Abbrechen" schlicht',
      'Pflichtfelder mit **\\*** und Hinweis gekennzeichnet',
    ],
    hinweise: 'Mängel im Entwurf: Beschriftungen uneinheitlich (links, rechts, darüber), Felder ohne Ordnung verteilt, Datum als Freitext ohne Format, Hinweis mit zu wenig Kontrast, „OK" winzig und unklar, „ABBRUCH" groß und rot – die Nebenaktion wirkt wichtiger als die Hauptaktion. Ob die Bezeichnung automatisch gefüllt wird, ist eine sinnvolle Idee, aber kein Muss.',
  },
];

export default { spickzettel, notation, aufgaben };
