// Modus „EPK & BPMN" – Format: siehe ../README.md

export const spickzettel = `- **EPK-Ereignis** (Sechseck) = Zustand, der eingetreten ist („Antrag liegt vor"); **Funktion** (abgerundetes Rechteck) = Tätigkeit („Antrag prüfen")
- **Ereignis und Funktion wechseln sich ab**; die EPK beginnt und endet mit einem Ereignis
- Konnektoren: **UND (∧)** alle Zweige, **XOR** genau ein Zweig, **ODER (∨)** mindestens ein Zweig – zusammenführen mit demselben Konnektor
- **Nach einem Ereignis nur UND verzweigen** – entscheiden kann nur eine Funktion (danach XOR oder ODER)
- **Organisationseinheit** (Ellipse mit Strich) und **Informationsobjekt** (Rechteck) hängen per Linie an der Funktion
- BPMN: **Aufgabe** (abgerundetes Rechteck), Ereignisse als Kreis: Start dünn, Zwischen doppelt, Ende dick; Gateways: **X** exklusiv, **O** inklusiv, **+** parallel
- **Sequenzfluss** (durchgezogen) nur **innerhalb eines Pools**, **Nachrichtenfluss** (gestrichelt) **zwischen Pools**; Lanes = Rollen im Pool`;

// ---------- Bausteine ----------

const E = (id, x, y, text, extra = {}) => ({ id, typ: 'ereignis', x, y, text, ...extra });
const F = (id, x, y, text, extra = {}) => ({ id, typ: 'funktion', x, y, text, ...extra });
const O = (id, x, y, text, extra = {}) => ({ id, typ: 'org', x, y, w: 150, text, ...extra });
const I = (id, x, y, text, extra = {}) => ({ id, typ: 'info', x, y, w: 130, text, ...extra });
const K = (id, x, y, art, extra = {}) => ({ id, typ: 'konnektor', x, y, art, ...extra });
const fl = (von, nach, extra = {}) => ({ von, nach, typ: 'fluss', ...extra });
const li = (von, nach, extra = {}) => ({ von, nach, typ: 'linie', ...extra });
// Verzweigen aus einem Konnektor (Mitte cy) zu einem Knoten mit Mitte xZiel
const abL = (von, nach, xZiel, cy, extra = {}) => fl(von, nach, { vonSeite: 'links', via: [[xZiel, cy]], nachSeite: 'oben', ...extra });
const abR = (von, nach, xZiel, cy, extra = {}) => fl(von, nach, { vonSeite: 'rechts', via: [[xZiel, cy]], nachSeite: 'oben', ...extra });
// Zusammenführen in einen Konnektor (Mitte cy) von einem Knoten mit Mitte xQuelle
const zuL = (von, nach, xQuelle, cy, extra = {}) => fl(von, nach, { vonSeite: 'unten', via: [[xQuelle, cy]], nachSeite: 'links', ...extra });
const zuR = (von, nach, xQuelle, cy, extra = {}) => fl(von, nach, { vonSeite: 'unten', via: [[xQuelle, cy]], nachSeite: 'rechts', ...extra });

const A = (id, x, y, text, extra = {}) => ({ id, typ: 'aufgabe', x, y, text, ...extra });
const S = (id, x, y, text, extra = {}) => ({ id, typ: 'startereignis', x, y, text, ...extra });
const Z = (id, x, y, text, extra = {}) => ({ id, typ: 'zwischenereignis', x, y, text, ...extra });
const EN = (id, x, y, text, extra = {}) => ({ id, typ: 'endereignis', x, y, text, ...extra });
const G = (id, x, y, art, text, extra = {}) => ({ id, typ: 'gateway', x, y, art, ...(text ? { text } : {}), ...extra });
const PUNKT = (id, x, y, extra = {}) => ({ id, typ: 'text', x, y, text: '', ...extra }); // Anker für Nachrichtenflüsse am Poolrand
const sf = (von, nach, extra = {}) => ({ von, nach, typ: 'sequenzfluss', ...extra });
const nf = (von, nach, extra = {}) => ({ von, nach, typ: 'nachrichtenfluss', ...extra });
const df = (von, nach, extra = {}) => ({ von, nach, typ: 'datenfluss', ...extra });
const notiz = (id, x, y, text, anker = 'start') => ({ id, typ: 'text', x, y, text, anker, klein: true });


// ---------- Notation ----------

const epkUebersicht = {
  breite: 800,
  hoehe: 520,
  knoten: [
    E('e1', 230, 16, 'Urlaubsantrag liegt vor'),
    F('f1', 230, 96, 'Urlaubsantrag prüfen'),
    O('o1', 40, 99, 'Teamleitung'),
    I('i1', 410, 101, 'Urlaubskonto'),
    K('k1', 284, 176, 'xor'),
    E('e2', 100, 238, 'Antrag genehmigt'),
    E('e3', 360, 238, 'Antrag abgelehnt'),
    F('f2', 100, 318, 'Urlaub im Plan eintragen'),
    F('f3', 360, 318, 'Ablehnung begründen'),
    K('k2', 284, 398, 'xor'),
    E('e4', 230, 450, 'Antrag bearbeitet'),
    notiz('n1', 380, 41, '← Ereignis: Zustand'),
    notiz('n2', 115, 160, 'Organisationseinheit', 'middle'),
    notiz('n3', 475, 158, 'Informationsobjekt', 'middle'),
    notiz('n4', 510, 343, '← Funktion: Tätigkeit'),
    notiz('n5', 322, 166, 'XOR verzweigt'),
    notiz('n6', 322, 438, 'XOR führt zusammen'),
    notiz('l0', 620, 96, 'Konnektoren'),
    K('l1', 620, 116, 'und'),
    notiz('l1t', 662, 132, 'UND: alle Zweige'),
    K('l2', 620, 166, 'xor'),
    notiz('l2t', 662, 182, 'XOR: genau ein Zweig'),
    K('l3', 620, 216, 'oder'),
    notiz('l3t', 662, 232, 'ODER: mind. ein Zweig'),
  ],
  kanten: [
    fl('e1', 'f1'),
    li('o1', 'f1'),
    li('i1', 'f1'),
    fl('f1', 'k1'),
    abL('k1', 'e2', 170, 192),
    abR('k1', 'e3', 430, 192),
    fl('e2', 'f2'),
    fl('e3', 'f3'),
    zuL('f2', 'k2', 170, 414),
    zuR('f3', 'k2', 430, 414),
    fl('k2', 'e4'),
  ],
};

const bpmnUebersicht = {
  breite: 900,
  hoehe: 535,
  rahmen: [
    { typ: 'pool', x: 16, y: 16, w: 868, h: 64, text: 'Kunde' },
    { typ: 'pool', x: 16, y: 110, w: 868, text: 'Onlineshop', lanes: [{ text: 'Vertrieb', h: 175 }, { text: 'Lager', h: 120 }] },
  ],
  knoten: [
    PUNKT('m1', 106, 80),
    PUNKT('m2', 540, 80),
    S('s1', 90, 151, 'Bestellung\neingegangen', { symbol: 'brief' }),
    A('a1', 160, 140, 'Bestellung prüfen'),
    { id: 'd1', typ: 'datenobjekt', x: 203, y: 214, text: 'Bestellung' },
    G('g1', 320, 146, 'x', 'Ware vorrätig?'),
    A('a3', 480, 140, 'Absage senden'),
    EN('e1', 660, 151, 'Bestellung\nabgelehnt'),
    A('a2', 480, 318, 'Ware versenden'),
    EN('e2', 660, 329, 'Ware\nversendet'),
    S('ls1', 60, 455, 'Start-\nereignis'),
    Z('ls2', 160, 455, 'Zwischen-\nereignis', { symbol: 'uhr' }),
    EN('ls3', 260, 455, 'End-\nereignis'),
    G('lg1', 360, 450, 'x'),
    notiz('lg1t', 381, 509, 'exklusiv', 'middle'),
    G('lg2', 460, 450, 'o'),
    notiz('lg2t', 481, 509, 'inklusiv', 'middle'),
    G('lg3', 560, 450, '+'),
    notiz('lg3t', 581, 509, 'parallel', 'middle'),
    { id: 'ld', typ: 'datenobjekt', x: 664, y: 445, text: 'Datenobjekt' },
  ],
  kanten: [
    nf('m1', 's1', { nachSeite: 'oben', text: 'Bestellung', textPos: 0.25 }),
    sf('s1', 'a1'),
    df('d1', 'a1'),
    sf('a1', 'g1'),
    sf('g1', 'a3', { text: 'nein' }),
    sf('a3', 'e1'),
    sf('g1', 'a2', { vonSeite: 'unten', via: [[341, 345]], nachSeite: 'links', text: 'ja', textPos: 0.62 }),
    sf('a2', 'e2'),
    nf('a3', 'm2', { vonSeite: 'oben', text: 'Absage', textPos: 0.8 }),
  ],
};

export const notation = {
  text: 'Beide Bilder zeigen einen Ablauf von oben nach unten bzw. von links nach rechts. In der **EPK** wechseln sich Ereignisse (was ist passiert?) und Funktionen (was wird getan?) ab. In **BPMN** stehen die Aufgaben in **Lanes** – so siehst du sofort, wer was tut. Was zwischen zwei Beteiligten mit eigenem Pool hin und her geht, ist ein **Nachrichtenfluss**.',
  bilder: [
    { titel: 'EPK – Urlaubsantrag', diagramm: epkUebersicht },
    { titel: 'BPMN – Bestellung im Onlineshop', diagramm: bpmnUebersicht },
  ],
  punkte: [
    '**EPK lesen:** Ereignis „Urlaubsantrag liegt vor" → die Teamleitung prüft ihn (mit dem Urlaubskonto) → **genau eins** von beiden: genehmigt oder abgelehnt → passende Funktion → „Antrag bearbeitet".',
    '**Ereignis** als Zustand benennen („… liegt vor", „… genehmigt"), **Funktion** als Tätigkeit (Substantiv + Verb: „Antrag prüfen").',
    'Eine Entscheidung trifft immer eine **Funktion**. Direkt nach einem Ereignis darfst du deshalb nur mit **UND** verzweigen, nie mit XOR oder ODER.',
    'Was mit einem Konnektor aufgeteilt wird, führst du mit **demselben** Konnektor wieder zusammen (XOR … XOR, UND … UND).',
    '**BPMN-Gateways:** X = genau ein Weg (je nach Bedingung), O = ein oder mehrere Wege, + = alle Wege gleichzeitig. Die Bedingung schreibst du an das Gateway, die Antworten an die Pfeile.',
    '**Sequenzfluss** (durchgezogen, gefüllte Spitze) verbindet Schritte **in einem Pool** – auch über Lane-Grenzen. **Nachrichtenfluss** (gestrichelt, kleiner Kreis am Anfang) verbindet **zwei Pools**.',
    '**Datenobjekt** (Blatt mit Eselsohr) hängt per gepunkteter Linie an der Aufgabe, die es liest oder schreibt.',
  ],
};

// AP1: nur lesen und benennen – ohne Datenobjekt und ohne Modellierungsregeln
const bpmnUebersichtAP1 = {
  ...bpmnUebersicht,
  knoten: bpmnUebersicht.knoten.filter((k) => k.id !== 'd1' && k.id !== 'ld'),
  kanten: bpmnUebersicht.kanten.filter((k) => k.von !== 'd1'),
};

export const spickzettelAP1 = `- **EPK-Ereignis** (Sechseck) = Zustand, der eingetreten ist („Antrag liegt vor"); **Funktion** (abgerundetes Rechteck) = Tätigkeit („Antrag prüfen")
- **Ereignis und Funktion wechseln sich ab**; die EPK beginnt und endet mit einem Ereignis
- **Organisationseinheit** (Ellipse mit Strich) = **wer** die Funktion ausführt; **Informationsobjekt** (Rechteck) = Daten, die sie nutzt
- Konnektoren: **UND (∧)** alle Zweige, **XOR** genau ein Zweig, **ODER (∨)** mindestens ein Zweig
- BPMN: **Aufgabe** (abgerundetes Rechteck), Ereignisse als Kreis: Start dünn, Zwischen doppelt, Ende dick; Gateways: **X** exklusiv, **O** inklusiv, **+** parallel
- **Pool** = Beteiligter, **Lane** = Rolle darin – die Lane zeigt, **wer** eine Aufgabe erledigt
- **Sequenzfluss** (durchgezogen) = Reihenfolge im Pool, **Nachrichtenfluss** (gestrichelt) = Nachricht zwischen zwei Pools`;

export const notationAP1 = {
  text: notation.text,
  bilder: [
    { titel: 'EPK – Urlaubsantrag', diagramm: epkUebersicht },
    { titel: 'BPMN – Bestellung im Onlineshop', diagramm: bpmnUebersichtAP1 },
  ],
  punkte: [
    notation.punkte[0],
    '**Ereignis** = Zustand („… liegt vor", „… genehmigt"), **Funktion** = Tätigkeit („Antrag prüfen"). Beides wechselt sich ab; Anfang und Ende sind Ereignisse.',
    '**Wer** etwas tut, steht in der EPK in der **Organisationseinheit** an der Funktion, in BPMN in der **Lane**, in der die Aufgabe liegt.',
    '**BPMN-Gateways:** X = genau ein Weg (je nach Bedingung), O = ein oder mehrere Wege, + = alle Wege gleichzeitig. Die Bedingung steht am Gateway, die Antworten an den Pfeilen.',
    '**BPMN lesen:** Die Bestellung kommt als Nachricht vom Kunden → der Vertrieb prüft sie → Ware vorrätig? nein: der Vertrieb sendet eine Absage an den Kunden; ja: das Lager versendet die Ware.',
    '**Sequenzfluss** (durchgezogen, gefüllte Spitze) verbindet Schritte **in einem Pool** – auch über Lane-Grenzen. **Nachrichtenfluss** (gestrichelt, kleiner Kreis am Anfang) verbindet **zwei Pools**.',
  ],
};

// ---------- Aufgaben ----------

const OPT_EPK = ['Ereignis', 'Funktion', 'Organisationseinheit', 'Informationsobjekt'];
const OPT_GW = ['exklusives Gateway (X)', 'inklusives Gateway (O)', 'paralleles Gateway (+)'];
const ANZ_GW = { 'exklusives Gateway (X)': 'X', 'inklusives Gateway (O)': 'O', 'paralleles Gateway (+)': '+' };
const OPT_KON = ['XOR (exklusives Oder)', 'UND', 'ODER (inklusives Oder)'];
const ANZ_KON = { 'XOR (exklusives Oder)': 'XOR', UND: '∧', 'ODER (inklusives Oder)': '∨' };

export const aufgaben = [
  // ---------- AP1: lesen und benennen ----------
  {
    id: 'pr-q1',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-4',
    titel: 'EPK lesen: Störung im IT-Support',
    text: 'Die EPK zeigt, wie der IT-Support eine gemeldete Störung bearbeitet. Benenne die markierten Sinnbilder 1–5 und beantworte die Fragen zum Ablauf.',
    diagramm: {
      breite: 720,
      hoehe: 466,
      knoten: [
        E('e1', 250, 16, 'Störung gemeldet', { marke: 1 }),
        F('f1', 250, 96, 'Störung analysieren', { marke: 2 }),
        O('o1', 50, 99, 'IT-Support', { marke: 3 }),
        I('i1', 440, 101, 'Ticket', { marke: 4 }),
        K('k1', 304, 176, 'xor', { marke: 5 }),
        E('e2', 110, 238, 'Vor Ort behebbar'),
        E('e3', 390, 238, 'Ersatzgerät nötig'),
        F('f2', 110, 318, 'Störung beheben'),
        F('f3', 390, 318, 'Ersatzgerät bestellen'),
        E('e4', 110, 398, 'Störung behoben'),
        E('e5', 390, 398, 'Ersatzgerät bestellt'),
      ],
      kanten: [
        fl('e1', 'f1'),
        li('o1', 'f1'),
        li('i1', 'f1'),
        fl('f1', 'k1'),
        abL('k1', 'e2', 180, 192),
        abR('k1', 'e3', 460, 192),
        fl('e2', 'f2'),
        fl('e3', 'f3'),
        fl('f2', 'e4'),
        fl('f3', 'e5'),
      ],
    },
    felder: [
      { id: '1', label: 'Sinnbild 1 (Sechseck)', optionen: OPT_EPK, erwartet: 'Ereignis' },
      { id: '2', label: 'Sinnbild 2 (abgerundetes Rechteck)', optionen: OPT_EPK, erwartet: 'Funktion' },
      { id: '3', label: 'Sinnbild 3 (Ellipse mit senkrechtem Strich)', optionen: OPT_EPK, erwartet: 'Organisationseinheit' },
      { id: '4', label: 'Sinnbild 4 (Rechteck)', optionen: OPT_EPK, erwartet: 'Informationsobjekt' },
      {
        id: '5',
        label: 'Was bedeutet der Konnektor 5?',
        optionen: ['Beide Wege werden durchlaufen.', 'Genau einer der beiden Wege wird durchlaufen.', 'Einer oder beide Wege werden durchlaufen.', 'Der Ablauf endet hier.'],
        erwartet: 'Genau einer der beiden Wege wird durchlaufen.',
      },
      { id: 'w', label: 'Wer analysiert die Störung?', optionen: ['der IT-Support', 'das Ticket', 'der Lieferant des Ersatzgeräts', 'niemand – das läuft automatisch'], erwartet: 'der IT-Support' },
      {
        id: 'a',
        label: 'Was passiert, wenn die Störung nicht vor Ort behebbar ist?',
        optionen: ['Die Störung wird trotzdem vor Ort behoben.', 'Es wird ein Ersatzgerät bestellt.', 'Es wird erst ein Ersatzgerät bestellt und dann die Störung vor Ort behoben.', 'Das Ticket wird gelöscht.'],
        erwartet: 'Es wird ein Ersatzgerät bestellt.',
      },
    ],
    loesung: [
      '[1] Das **Sechseck** ist ein Ereignis: Es beschreibt einen Zustand („Störung gemeldet"), keine Tätigkeit.',
      '[2] Das **abgerundete Rechteck** ist eine Funktion: Hier wird etwas getan („Störung analysieren").',
      '[3] Die **Ellipse mit Strich** ist eine Organisationseinheit: Sie sagt, **wer** die Funktion ausführt.',
      '[4] Das **Rechteck** ist ein Informationsobjekt: Daten, die die Funktion braucht oder erzeugt – hier das Ticket.',
      '[5] **XOR** heißt exklusives Oder: Nach der Analyse tritt genau eines der beiden Ereignisse ein.',
      'Die Organisationseinheit hängt an „Störung analysieren" – also analysiert der IT-Support.',
      'Folge dem rechten Zweig: „Ersatzgerät nötig" → „Ersatzgerät bestellen" → „Ersatzgerät bestellt".',
    ],
  },
  {
    id: 'pr-q2',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-4',
    titel: 'BPMN lesen: Bestellung beim Lieferanten',
    text: 'Das BPMN-Diagramm zeigt, wie eine Fachabteilung Material über den Einkauf beim Lieferanten bestellt. Benenne die markierten Sinnbilder 1–6 und beantworte die Fragen.',
    diagramm: {
      breite: 920,
      hoehe: 440,
      rahmen: [
        { typ: 'pool', x: 16, y: 16, w: 888, h: 64, text: 'Lieferant' },
        { typ: 'pool', x: 16, y: 104, w: 888, text: 'Unternehmen', lanes: [{ text: 'Fachabteilung', h: 120 }, { text: 'Einkauf', h: 200 }] },
      ],
      knoten: [
        PUNKT('m1', 620, 80),
        PUNKT('m2', 746, 80),
        S('s1', 84, 148, 'Bedarf\nfestgestellt', { marke: 1 }),
        A('a1', 140, 137, 'Bestellung anfordern'),
        A('a2', 280, 253, 'Anforderung prüfen', { marke: 2 }),
        G('g1', 460, 259, 'x'),
        notiz('g1t', 481, 250, 'genehmigt?', 'middle'),
        PUNKT('g1m', 460, 304, { marke: 3 }),
        A('a3', 560, 253, 'Bestellung senden'),
        Z('z1', 730, 264, 'Ware geliefert', { symbol: 'brief', marke: 5 }),
        EN('e1', 830, 264, 'Ware\nerhalten', { marke: 6 }),
        A('a4', 560, 340, 'Anforderung ablehnen'),
        EN('e2', 730, 351, 'Anforderung\nabgelehnt'),
      ],
      kanten: [
        sf('s1', 'a1'),
        sf('a1', 'a2', { vonSeite: 'rechts', via: [[340, 164]], nachSeite: 'oben' }),
        sf('a2', 'g1'),
        sf('g1', 'a3', { text: 'ja', textSeite: -1 }),
        sf('a3', 'z1'),
        sf('z1', 'e1'),
        sf('g1', 'a4', { vonSeite: 'unten', via: [[481, 367]], nachSeite: 'links', text: 'nein', textPos: 0.35 }),
        sf('a4', 'e2'),
        nf('a3', 'm1', { vonSeite: 'oben', text: 'Bestellung', marke: 4, textPos: 0.4 }),
        nf('m2', 'z1', { nachSeite: 'oben', text: 'Lieferung' }),
      ],
    },
    felder: [
      { id: '1', label: 'Sinnbild 1 (einfacher dünner Kreis)', optionen: ['Startereignis', 'Zwischenereignis', 'Endereignis', 'Aufgabe'], erwartet: 'Startereignis' },
      { id: '2', label: 'Sinnbild 2', optionen: ['Ereignis', 'Aufgabe', 'Datenobjekt', 'Gateway'], erwartet: 'Aufgabe' },
      {
        id: '3',
        label: 'Sinnbild 3 (Raute mit X)',
        optionen: ['paralleles Gateway – alle Wege laufen', 'exklusives Gateway – genau ein Weg', 'inklusives Gateway – ein oder mehrere Wege', 'Zwischenereignis'],
        erwartet: 'exklusives Gateway – genau ein Weg',
      },
      {
        id: '4',
        label: 'Verbindung 4 (gestrichelt, zum Lieferanten)',
        optionen: ['Sequenzfluss innerhalb des Pools', 'Datenfluss zu einem Datenobjekt', 'Nachrichtenfluss zwischen zwei Pools', 'Grenze zwischen zwei Lanes'],
        erwartet: 'Nachrichtenfluss zwischen zwei Pools',
      },
      {
        id: '5',
        label: 'Sinnbild 5 (doppelter Kreis mit Brief)',
        optionen: ['Startereignis: Der Lieferant startet den Ablauf.', 'Zwischenereignis: Der Einkauf wartet, bis die Lieferung eintrifft.', 'Endereignis: Der Ablauf ist zu Ende.', 'Aufgabe: Ware einlagern.'],
        erwartet: 'Zwischenereignis: Der Einkauf wartet, bis die Lieferung eintrifft.',
      },
      { id: '6', label: 'Sinnbild 6 (dicker Kreis)', optionen: ['Startereignis', 'Zwischenereignis', 'Endereignis', 'paralleles Gateway'], erwartet: 'Endereignis' },
      { id: 'l', label: 'Wie heißen „Fachabteilung" und „Einkauf" innerhalb des Pools „Unternehmen"?', optionen: ['Pools', 'Lanes', 'Gateways', 'Aufgaben'], erwartet: 'Lanes' },
      { id: 'w', label: 'Wer prüft die Anforderung?', optionen: ['die Fachabteilung', 'der Einkauf', 'der Lieferant'], erwartet: 'der Einkauf' },
    ],
    loesung: [
      '[1] Ein dünner Kreis startet den Ablauf – das **Startereignis**.',
      '[2] Ein abgerundetes Rechteck ist eine **Aufgabe**: ein Arbeitsschritt.',
      '[3] Die Raute ist ein **Gateway**; das X macht es **exklusiv**: je nach Antwort auf „genehmigt?" genau ein Weg.',
      '[4] Gestrichelt mit Kreis am Anfang = **Nachrichtenfluss**. Er verbindet zwei Pools – hier das Unternehmen mit dem Lieferanten.',
      '[5] Der doppelte Kreis ist ein **Zwischenereignis**; der Brief sagt: Hier wird auf eine Nachricht gewartet.',
      '[6] Der dicke Kreis beendet den Ablauf – das **Endereignis**.',
      'Ein **Pool** steht für einen Beteiligten, seine **Lanes** für Rollen oder Abteilungen darin. „Anforderung prüfen" liegt in der Lane „Einkauf".',
    ],
  },
  {
    id: 'pr-q3',
    art: 'fragen',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-4',
    titel: 'Bewerbung: Wer macht was?',
    text: 'Das BPMN-Diagramm zeigt, wie ein Unternehmen eine Bewerbung bearbeitet. Gib den Ablauf in Worten wieder.',
    diagramm: {
      breite: 980,
      hoehe: 330,
      rahmen: [{ typ: 'pool', x: 16, y: 16, w: 948, text: 'Unternehmen', lanes: [{ text: 'Personalabteilung', h: 170 }, { text: 'Fachabteilung', h: 130 }] }],
      knoten: [
        S('s1', 84, 120, 'Bewerbung\neingegangen', { symbol: 'brief' }),
        A('a1', 136, 109, 'Unterlagen prüfen'),
        G('g1', 290, 115, 'x'),
        notiz('g1t', 311, 172, 'vollständig?', 'middle'),
        A('a2', 360, 29, 'Unterlagen nachfordern'),
        EN('e1', 530, 40, 'Unterlagen\nnachgefordert'),
        G('g2', 410, 115, '+'),
        A('a3', 490, 109, 'Referenzen einholen'),
        A('a4', 480, 224, 'Vorstellungsgespräch führen', { w: 140 }),
        G('g3', 660, 230, '+'),
        A('a5', 740, 224, 'Entscheidung treffen'),
        EN('e2', 884, 235, 'Entscheidung\ngetroffen'),
      ],
      kanten: [
        sf('s1', 'a1'),
        sf('a1', 'g1'),
        sf('g1', 'a2', { vonSeite: 'oben', via: [[311, 56]], nachSeite: 'links', text: 'nein', textPos: 0.75 }),
        sf('a2', 'e1'),
        sf('g1', 'g2', { text: 'ja', textSeite: -1 }),
        sf('g2', 'a3'),
        sf('g2', 'a4', { vonSeite: 'unten', via: [[431, 251]], nachSeite: 'links' }),
        sf('a3', 'g3', { vonSeite: 'rechts', via: [[681, 136]], nachSeite: 'oben' }),
        sf('a4', 'g3'),
        sf('g3', 'a5'),
        sf('a5', 'e2'),
      ],
    },
    felder: [
      { id: 'w1', label: 'Wer prüft die Unterlagen?', optionen: ['die Fachabteilung', 'die Personalabteilung', 'der Bewerber'], erwartet: 'die Personalabteilung' },
      { id: 'w2', label: 'Wer führt das Vorstellungsgespräch?', optionen: ['die Personalabteilung', 'der Bewerber', 'die Fachabteilung'], erwartet: 'die Fachabteilung' },
      {
        id: 'n',
        label: 'Was passiert, wenn die Unterlagen nicht vollständig sind?',
        optionen: [
          'Die Personalabteilung fordert Unterlagen nach; danach endet dieser Ablauf.',
          'Die Fachabteilung lädt trotzdem zum Gespräch ein.',
          'Die Referenzen werden eingeholt, das Gespräch entfällt.',
          'Die Bewerbung geht an die Fachabteilung zur Prüfung.',
        ],
        erwartet: 'Die Personalabteilung fordert Unterlagen nach; danach endet dieser Ablauf.',
      },
      {
        id: 'p',
        label: 'Was bedeutet das Gateway mit dem Plus nach „ja"?',
        optionen: [
          'Entweder werden Referenzen eingeholt oder das Gespräch geführt.',
          'Referenzen einholen und Vorstellungsgespräch finden beide statt, unabhängig voneinander.',
          'Das Gespräch findet nur statt, wenn die Referenzen gut sind.',
          'Hier wird gewartet, bis der Bewerber antwortet.',
        ],
        erwartet: 'Referenzen einholen und Vorstellungsgespräch finden beide statt, unabhängig voneinander.',
      },
      {
        id: 'j',
        label: 'Wann trifft die Fachabteilung die Entscheidung?',
        optionen: ['sobald eine der beiden Aufgaben erledigt ist', 'erst wenn Referenzen und Gespräch beide erledigt sind', 'direkt nach dem Prüfen der Unterlagen', 'nur wenn die Unterlagen unvollständig sind'],
        erwartet: 'erst wenn Referenzen und Gespräch beide erledigt sind',
      },
    ],
    loesung: [
      'Wer etwas tut, liest du an der **Lane** ab: „Unterlagen prüfen" liegt bei der Personalabteilung, das Vorstellungsgespräch bei der Fachabteilung.',
      'Das **exklusive Gateway** „vollständig?" lässt genau einen Weg zu. Bei „nein" folgen „Unterlagen nachfordern" und ein Endereignis – dieser Ablauf ist dann zu Ende.',
      'Das **parallele Gateway** (+) teilt den Ablauf: **Beide** Aufgaben werden erledigt, in beliebiger Reihenfolge oder gleichzeitig.',
      'Das zweite +-Gateway **wartet**, bis alle eingehenden Wege fertig sind. Erst dann geht es mit „Entscheidung treffen" weiter.',
    ],
  },
  {
    id: 'pr-f1',
    art: 'fehler',
    raum: ['AP1', 'AP2'],
    sp: 'AP1-8-4-4',
    titel: 'Grundregel der EPK: Wareneingang',
    text: 'Eine Kollegin hat den Wareneingang als EPK skizziert. Prüfe an den Stellen 1–4, ob die Grundregeln der EPK eingehalten sind.',
    diagramm: {
      breite: 620,
      hoehe: 406,
      knoten: [
        E('e1', 230, 16, 'Ware angeliefert', { marke: 1 }),
        F('f1', 230, 96, 'Lieferschein prüfen'),
        F('f2', 230, 176, 'Ware einlagern'),
        E('e2', 230, 256, 'Ware eingelagert'),
        O('o1', 430, 259, 'Lager', { marke: 4 }),
        F('f3', 230, 336, 'Bestand buchen', { marke: 3 }),
      ],
      kanten: [fl('e1', 'f1'), fl('f1', 'f2', { marke: 2 }), fl('f2', 'e2'), li('e2', 'o1'), fl('e2', 'f3')],
    },
    felder: [
      { id: '1', label: 'Beginn mit „Ware angeliefert"', optionen: ['korrekt', 'zwei Funktionen folgen direkt aufeinander', 'Ablauf endet nicht mit einem Ereignis', 'Organisationseinheit gehört an eine Funktion'], erwartet: 'korrekt' },
      { id: '2', label: 'Übergang „Lieferschein prüfen" → „Ware einlagern"', optionen: ['korrekt', 'zwei Funktionen folgen direkt aufeinander', 'Ablauf endet nicht mit einem Ereignis', 'Organisationseinheit gehört an eine Funktion'], erwartet: 'zwei Funktionen folgen direkt aufeinander' },
      { id: '3', label: 'Letztes Element „Bestand buchen"', optionen: ['korrekt', 'zwei Funktionen folgen direkt aufeinander', 'Ablauf endet nicht mit einem Ereignis', 'Organisationseinheit gehört an eine Funktion'], erwartet: 'Ablauf endet nicht mit einem Ereignis' },
      { id: '4', label: 'Organisationseinheit „Lager" an „Ware eingelagert"', optionen: ['korrekt', 'zwei Funktionen folgen direkt aufeinander', 'Ablauf endet nicht mit einem Ereignis', 'Organisationseinheit gehört an eine Funktion'], erwartet: 'Organisationseinheit gehört an eine Funktion' },
    ],
    loesung: [
      '[1] Richtig: Eine EPK **beginnt mit einem Ereignis**, das den Ablauf auslöst.',
      '[2] Ereignis und Funktion **wechseln sich ab**. Zwischen „Lieferschein prüfen" und „Ware einlagern" fehlt das Ergebnis der Prüfung, z. B. „Lieferung vollständig".',
      '[3] Eine EPK **endet mit einem Ereignis**. Nach „Bestand buchen" fehlt „Bestand gebucht".',
      '[4] Ein Ereignis ist nur ein Zustand – es führt niemand aus. Die Organisationseinheit sagt, **wer eine Funktion ausführt**; sie gehört an „Ware einlagern".',
    ],
    muster: {
      breite: 620,
      hoehe: 566,
      knoten: [
        E('e1', 230, 16, 'Ware angeliefert'),
        F('f1', 230, 96, 'Lieferschein prüfen'),
        E('e2', 230, 176, 'Lieferung vollständig', { hervor: true }),
        F('f2', 230, 256, 'Ware einlagern'),
        O('o1', 430, 259, 'Lager', { hervor: true }),
        E('e3', 230, 336, 'Ware eingelagert'),
        F('f3', 230, 416, 'Bestand buchen'),
        E('e4', 230, 496, 'Bestand gebucht', { hervor: true }),
      ],
      kanten: [fl('e1', 'f1'), fl('f1', 'e2'), fl('e2', 'f2'), li('f2', 'o1'), fl('f2', 'e3'), fl('e3', 'f3'), fl('f3', 'e4')],
    },
  },

  // ---------- AP2: Konnektoren, Gateways, Pools ----------
  {
    id: 'pr-e1',
    art: 'ergaenzen',
    raum: ['AP2'],
    sp: 'AP2-2-3-1',
    titel: 'Gateways: Reisekostenabrechnung',
    text: 'Nach einer Dienstreise erstellt der Mitarbeiter seine Abrechnung, die Buchhaltung prüft sie. Sind die Belege vollständig, wird der Betrag überwiesen **und** die Abrechnung archiviert – beides unabhängig voneinander. Sonst weist die Buchhaltung die Abrechnung zurück. Ergänze die Gateways [1]–[3] und beantworte die Fragen.',
    diagramm: {
      breite: 840,
      hoehe: 372,
      rahmen: [{ typ: 'pool', x: 16, y: 16, w: 808, text: 'Firma', lanes: [{ text: 'Mitarbeiter', h: 110 }, { text: 'Buchhaltung', h: 230 }] }],
      knoten: [
        S('s1', 92, 55, 'Reise\nbeendet'),
        A('a1', 150, 44, 'Abrechnung erstellen'),
        A('a2', 150, 214, 'Abrechnung prüfen'),
        G('g1', 310, 220, '{1}'),
        notiz('g1t', 331, 282, 'Belege vollständig?', 'middle'),
        A('a3', 390, 139, 'Abrechnung zurückweisen'),
        EN('e1', 570, 150, 'zurückgewiesen'),
        G('g2', 430, 220, '{2}'),
        A('a4', 510, 214, 'Betrag überweisen'),
        A('a5', 510, 289, 'Abrechnung archivieren'),
        G('g3', 670, 220, '{3}'),
        EN('e2', 760, 225, 'Abrechnung\nerledigt'),
      ],
      kanten: [
        sf('s1', 'a1'),
        sf('a1', 'a2'),
        sf('a2', 'g1'),
        sf('g1', 'a3', { vonSeite: 'oben', via: [[331, 166]], nachSeite: 'links', text: 'nein', textPos: 0.7 }),
        sf('a3', 'e1'),
        sf('g1', 'g2', { text: 'ja', textSeite: -1 }),
        sf('g2', 'a4'),
        sf('g2', 'a5', { vonSeite: 'unten', via: [[451, 316]], nachSeite: 'links' }),
        sf('a4', 'g3'),
        sf('a5', 'g3', { vonSeite: 'rechts', via: [[691, 316]], nachSeite: 'unten' }),
        sf('g3', 'e2'),
      ],
    },
    felder: [
      { id: '1', label: 'Gateway „Belege vollständig?"', optionen: OPT_GW, erwartet: 'exklusives Gateway (X)', anzeige: ANZ_GW },
      { id: '2', label: 'Gateway vor „Betrag überweisen" und „Abrechnung archivieren"', optionen: OPT_GW, erwartet: 'paralleles Gateway (+)', anzeige: ANZ_GW },
      { id: '3', label: 'Gateway, das beide Wege wieder zusammenführt', optionen: OPT_GW, erwartet: 'paralleles Gateway (+)', anzeige: ANZ_GW },
      {
        id: 'i',
        label: 'Wann wäre an [2] ein inklusives Gateway richtig?',
        optionen: ['wenn immer genau eine der beiden Aufgaben erledigt wird', 'wenn je nach Fall eine oder beide Aufgaben erledigt werden', 'wenn beide Aufgaben immer erledigt werden', 'wenn die Aufgaben in verschiedenen Pools liegen'],
        erwartet: 'wenn je nach Fall eine oder beide Aufgaben erledigt werden',
      },
      {
        id: 's',
        label: 'Welche Verbindung führt von „Abrechnung erstellen" zu „Abrechnung prüfen"?',
        optionen: ['Nachrichtenfluss, weil die Lane wechselt', 'Sequenzfluss, weil beide Lanes im selben Pool liegen', 'Datenfluss, weil die Abrechnung übergeben wird'],
        erwartet: 'Sequenzfluss, weil beide Lanes im selben Pool liegen',
      },
    ],
    loesung: [
      '[1] „Belege vollständig?" hat genau zwei Antworten, es gilt **genau ein** Weg → exklusives Gateway (X).',
      '[2] Überweisen **und** archivieren passieren beide, unabhängig voneinander → paralleles Gateway (+).',
      '[3] Zusammengeführt wird mit **derselben Art** wie verzweigt: Das +-Gateway wartet, bis beide Aufgaben fertig sind.',
      'Ein **inklusives** Gateway (O) passt, wenn je nach Bedingung ein Weg **oder mehrere** laufen – z. B. „Hotel und/oder Fahrtkosten erfassen".',
      'Lanes teilen nur den Pool auf. Innerhalb eines Pools verbindet immer der **Sequenzfluss** – auch über Lane-Grenzen hinweg.',
    ],
  },
  {
    id: 'pr-e2',
    art: 'ergaenzen',
    raum: ['AP2'],
    sp: 'AP2-2-3-1',
    titel: 'Konnektoren: Neue Mitarbeiterin',
    text: 'Nach der Vertragsunterschrift prüft die Personalabteilung die Einstellungsunterlagen. Sind sie unvollständig, werden sie nachgefordert. Sind sie vollständig, werden der IT-Zugang **und** der Arbeitsplatz eingerichtet. Wenn beides erledigt ist, ist der erste Arbeitstag vorbereitet. Ergänze die Konnektoren [1]–[3].',
    diagramm: {
      breite: 700,
      hoehe: 600,
      knoten: [
        E('e1', 260, 16, 'Arbeitsvertrag unterschrieben'),
        F('f1', 260, 96, 'Unterlagen prüfen'),
        O('o1', 70, 99, 'Personalabteilung'),
        I('i1', 450, 101, 'Personalakte'),
        K('k1', 314, 176, 'xor', { text: '{1}' }),
        E('e2', 120, 238, 'Unterlagen vollständig'),
        E('e3', 470, 238, 'Unterlagen unvollständig'),
        F('f3', 470, 318, 'Unterlagen nachfordern'),
        E('e5', 470, 398, 'Unterlagen nachgefordert'),
        K('k2', 174, 318, 'und', { text: '{2}' }),
        F('fa', 40, 380, 'IT-Zugang einrichten'),
        F('fb', 200, 380, 'Arbeitsplatz einrichten'),
        K('k3', 174, 460, 'und', { text: '{3}' }),
        E('e4', 120, 530, 'Arbeitstag vorbereitet'),
      ],
      kanten: [
        fl('e1', 'f1'),
        li('o1', 'f1'),
        li('i1', 'f1'),
        fl('f1', 'k1'),
        abL('k1', 'e2', 190, 192),
        abR('k1', 'e3', 540, 192),
        fl('e3', 'f3'),
        fl('f3', 'e5'),
        fl('e2', 'k2'),
        abL('k2', 'fa', 110, 334),
        abR('k2', 'fb', 270, 334),
        zuL('fa', 'k3', 110, 476),
        zuR('fb', 'k3', 270, 476),
        fl('k3', 'e4'),
      ],
    },
    felder: [
      { id: '1', label: 'Konnektor nach „Unterlagen prüfen"', optionen: OPT_KON, erwartet: 'XOR (exklusives Oder)', anzeige: ANZ_KON },
      { id: '2', label: 'Konnektor nach „Unterlagen vollständig"', optionen: OPT_KON, erwartet: 'UND', anzeige: ANZ_KON },
      { id: '3', label: 'Konnektor vor „Arbeitstag vorbereitet"', optionen: OPT_KON, erwartet: 'UND', anzeige: ANZ_KON },
      {
        id: 'r',
        label: 'Warum darf an [2] kein XOR stehen?',
        optionen: [
          'Weil XOR nur am Ende einer EPK erlaubt ist.',
          'Weil ein Ereignis nichts entscheiden kann – nach einem Ereignis darf nur mit UND verzweigt werden.',
          'Weil an einem XOR keine Funktionen folgen dürfen.',
          'Weil die Organisationseinheit fehlt.',
        ],
        erwartet: 'Weil ein Ereignis nichts entscheiden kann – nach einem Ereignis darf nur mit UND verzweigt werden.',
      },
    ],
    loesung: [
      '[1] Die Funktion „Unterlagen prüfen" hat **genau ein** Ergebnis: vollständig oder unvollständig → **XOR**.',
      '[2] Bei vollständigen Unterlagen passieren **beide** Funktionen → **UND**. Direkt nach einem Ereignis ist ohnehin nur UND erlaubt, denn ein Ereignis trifft keine Entscheidung.',
      '[3] Erst wenn **beide** Funktionen erledigt sind, ist der Arbeitstag vorbereitet → **UND**. Zusammengeführt wird mit demselben Konnektor, mit dem verzweigt wurde.',
    ],
  },
  {
    id: 'pr-f2',
    art: 'fehler',
    raum: ['AP2'],
    sp: 'AP2-2-3-1',
    titel: 'Fehler in der EPK: Reklamation',
    text: 'Ein Kunde reklamiert eine Ware. Der Kundenservice prüft die Reklamation und erstellt danach **entweder** eine Gutschrift **oder** liefert Ersatzware. Danach wird der Kunde informiert und der Vorgang abgeschlossen. Prüfe die Stellen 1–4.',
    diagramm: {
      breite: 600,
      hoehe: 600,
      knoten: [
        E('e1', 230, 16, 'Reklamation eingegangen'),
        K('k1', 284, 96, 'xor', { marke: 1 }),
        F('f1', 100, 150, 'Gutschrift erstellen'),
        F('f2', 360, 150, 'Ersatzware liefern'),
        E('e2', 100, 230, 'Gutschrift erstellt'),
        E('e3', 360, 230, 'Ersatzware geliefert'),
        K('k2', 284, 310, 'oder', { marke: 2 }),
        F('f3', 230, 372, 'Kunde informieren'),
        O('o1', 40, 375, 'Kundenservice', { marke: 3 }),
        I('i1', 420, 377, 'Reklamation'),
        F('f4', 230, 452, 'Vorgang abschließen'),
        E('e4', 230, 532, 'Vorgang abgeschlossen'),
      ],
      kanten: [
        fl('e1', 'k1'),
        abL('k1', 'f1', 170, 112),
        abR('k1', 'f2', 430, 112),
        fl('f1', 'e2'),
        fl('f2', 'e3'),
        zuL('e2', 'k2', 170, 326),
        zuR('e3', 'k2', 430, 326),
        fl('k2', 'f3'),
        li('o1', 'f3'),
        li('i1', 'f3'),
        fl('f3', 'f4', { marke: 4 }),
        fl('f4', 'e4'),
      ],
    },
    felder: [
      {
        id: '1',
        label: 'XOR direkt nach „Reklamation eingegangen"',
        optionen: ['korrekt', 'falsch: Nach einem Ereignis darf nicht mit XOR verzweigt werden – davor fehlt eine Funktion', 'falsch: XOR darf nur zusammenführen, nicht verzweigen', 'falsch: Hier muss ein UND stehen, weil beide Wege durchlaufen werden'],
        erwartet: 'falsch: Nach einem Ereignis darf nicht mit XOR verzweigt werden – davor fehlt eine Funktion',
      },
      {
        id: '2',
        label: 'ODER-Konnektor, der beide Zweige zusammenführt',
        optionen: ['korrekt', 'falsch: Konnektoren dürfen nichts zusammenführen', 'falsch: Zusammenführen muss zum Verzweigen passen – hier XOR', 'falsch: Nach einem Konnektor muss ein Ereignis folgen'],
        erwartet: 'falsch: Zusammenführen muss zum Verzweigen passen – hier XOR',
      },
      {
        id: '3',
        label: 'Organisationseinheit „Kundenservice" an „Kunde informieren"',
        optionen: ['korrekt', 'falsch: Organisationseinheiten gehören an Ereignisse', 'falsch: Die Verbindung muss ein Pfeil sein', 'falsch: Organisationseinheiten gibt es in der EPK nicht'],
        erwartet: 'korrekt',
      },
      {
        id: '4',
        label: 'Übergang „Kunde informieren" → „Vorgang abschließen"',
        optionen: ['korrekt', 'falsch: Hier fehlt ein UND-Konnektor', 'falsch: Zwischen zwei Funktionen fehlt ein Ereignis', 'falsch: Eine EPK darf nur eine Funktion enthalten'],
        erwartet: 'falsch: Zwischen zwei Funktionen fehlt ein Ereignis',
      },
    ],
    loesung: [
      '[1] Ein Ereignis ist nur ein Zustand und kann **nicht entscheiden**. Erst eine Funktion („Reklamation prüfen") liefert die Entscheidung; danach folgt das XOR mit den beiden Ergebnis-Ereignissen.',
      '[2] Aufgeteilt wurde mit **XOR** (entweder – oder), also wird auch mit **XOR** zusammengeführt. Ein ODER würde behaupten, dass auch beide Zweige laufen könnten.',
      '[3] Richtig: Die Organisationseinheit hängt mit einer Linie an der Funktion, die sie ausführt.',
      '[4] Ereignis und Funktion **wechseln sich ab**. Zwischen den beiden Funktionen fehlt „Kunde informiert".',
    ],
    muster: {
      breite: 600,
      hoehe: 850,
      knoten: [
        E('e1', 230, 16, 'Reklamation eingegangen'),
        F('f0', 230, 96, 'Reklamation prüfen', { hervor: true }),
        K('k1', 284, 176, 'xor'),
        E('ea', 100, 238, 'Gutschrift gewünscht', { hervor: true }),
        E('eb', 360, 238, 'Ersatz gewünscht', { hervor: true }),
        F('f1', 100, 318, 'Gutschrift erstellen'),
        F('f2', 360, 318, 'Ersatzware liefern'),
        E('e2', 100, 398, 'Gutschrift erstellt'),
        E('e3', 360, 398, 'Ersatzware geliefert'),
        K('k2', 284, 478, 'xor', { hervor: true }),
        F('f3', 230, 540, 'Kunde informieren'),
        O('o1', 40, 543, 'Kundenservice'),
        I('i1', 420, 545, 'Reklamation'),
        E('e5', 230, 620, 'Kunde informiert', { hervor: true }),
        F('f4', 230, 700, 'Vorgang abschließen'),
        E('e4', 230, 780, 'Vorgang abgeschlossen'),
      ],
      kanten: [
        fl('e1', 'f0'),
        fl('f0', 'k1'),
        abL('k1', 'ea', 170, 192),
        abR('k1', 'eb', 430, 192),
        fl('ea', 'f1'),
        fl('eb', 'f2'),
        fl('f1', 'e2'),
        fl('f2', 'e3'),
        zuL('e2', 'k2', 170, 494),
        zuR('e3', 'k2', 430, 494),
        fl('k2', 'f3'),
        li('o1', 'f3'),
        li('i1', 'f3'),
        fl('f3', 'e5'),
        fl('e5', 'f4'),
        fl('f4', 'e4'),
      ],
    },
  },
  {
    id: 'pr-f3',
    art: 'fehler',
    raum: ['AP2'],
    sp: 'AP2-2-3-1',
    titel: 'Fehler in BPMN: Kfz-Werkstatt',
    text: 'Ein Kunde beauftragt eine Werkstatt mit einer Reparatur. Die Annahme nimmt den Auftrag an, die Technik prüft das Fahrzeug und bestellt **nur bei Bedarf** ein Ersatzteil, dann wird repariert. Die Annahme schickt dem Kunden die Rechnung. Prüfe die Stellen 1–4.',
    diagramm: {
      breite: 980,
      hoehe: 446,
      rahmen: [
        { typ: 'pool', x: 16, y: 16, w: 948, h: 100, text: 'Kunde' },
        { typ: 'pool', x: 16, y: 160, w: 948, text: 'Werkstatt', lanes: [{ text: 'Annahme', h: 100 }, { text: 'Technik', h: 170 }] },
      ],
      knoten: [
        S('ks', 70, 44, 'Defekt\nbemerkt'),
        A('ka1', 130, 33, 'Reparatur beauftragen'),
        Z('kz', 714, 44, '', { symbol: 'brief' }),
        notiz('kzt', 730, 30, 'Rechnung erhalten', 'middle'),
        A('ka2', 770, 33, 'Rechnung bezahlen'),
        EN('ke', 904, 44, 'bezahlt'),
        S('ws', 174, 194, 'Auftrag\neingegangen', { symbol: 'brief' }),
        A('wa1', 230, 183, 'Auftrag annehmen'),
        A('wt1', 230, 273, 'Fahrzeug prüfen'),
        G('g1', 380, 279, '+'),
        notiz('g1t', 401, 266, 'Ersatzteil nötig?', 'middle'),
        PUNKT('g1m', 378, 322, { marke: 4 }),
        A('wt2', 450, 353, 'Ersatzteil bestellen'),
        G('g2', 600, 279, 'x'),
        A('wt3', 670, 273, 'Fahrzeug reparieren'),
        A('wa2', 670, 183, 'Rechnung senden'),
        EN('we', 830, 194, 'Auftrag\nerledigt'),
      ],
      kanten: [
        sf('ks', 'ka1'),
        sf('ka1', 'kz'),
        sf('kz', 'ka2'),
        sf('ka2', 'ke'),
        sf('ka1', 'ws', { vonSeite: 'unten', nachSeite: 'oben', marke: 1 }),
        sf('ws', 'wa1'),
        nf('wa1', 'wt1', { vonSeite: 'unten', nachSeite: 'oben', marke: 2 }),
        sf('wt1', 'g1'),
        sf('g1', 'wt2', { vonSeite: 'unten', via: [[401, 380]], nachSeite: 'links', text: 'ja', textPos: 0.3 }),
        sf('g1', 'g2', { text: 'nein' }),
        sf('wt2', 'g2', { vonSeite: 'rechts', via: [[621, 380]], nachSeite: 'unten' }),
        sf('g2', 'wt3'),
        sf('wt3', 'wa2'),
        sf('wa2', 'we'),
        nf('wa2', 'kz', { vonSeite: 'oben', nachSeite: 'unten', text: 'Rechnung', marke: 3, textPos: 0.45 }),
      ],
    },
    felder: [
      {
        id: '1',
        label: 'Verbindung „Reparatur beauftragen" → „Auftrag eingegangen"',
        optionen: ['korrekt', 'falsch: muss ein Nachrichtenfluss sein, weil sie zwei Pools verbindet', 'falsch: muss ein Datenfluss sein', 'falsch: Pools dürfen nicht verbunden werden'],
        erwartet: 'falsch: muss ein Nachrichtenfluss sein, weil sie zwei Pools verbindet',
      },
      {
        id: '2',
        label: 'Verbindung „Auftrag annehmen" → „Fahrzeug prüfen"',
        optionen: ['korrekt', 'falsch: muss ein Sequenzfluss sein, weil beide Lanes im selben Pool liegen', 'falsch: muss ein Datenfluss sein', 'falsch: zwischen Lanes braucht es ein Gateway'],
        erwartet: 'falsch: muss ein Sequenzfluss sein, weil beide Lanes im selben Pool liegen',
      },
      {
        id: '3',
        label: 'Verbindung „Rechnung senden" → „Rechnung erhalten"',
        optionen: ['korrekt', 'falsch: muss ein Sequenzfluss sein', 'falsch: Ein Nachrichtenfluss darf nicht an einem Ereignis enden', 'falsch: Die Richtung muss umgekehrt sein'],
        erwartet: 'korrekt',
      },
      {
        id: '4',
        label: 'Gateway „Ersatzteil nötig?"',
        optionen: ['korrekt', 'falsch: muss ein exklusives Gateway sein – je nach Antwort gibt es genau einen Weg', 'falsch: muss ein inklusives Gateway sein', 'falsch: Hier darf kein Gateway stehen'],
        erwartet: 'falsch: muss ein exklusives Gateway sein – je nach Antwort gibt es genau einen Weg',
      },
    ],
    loesung: [
      '[1] Kunde und Werkstatt sind **zwei Pools**. Zwischen Pools fließen nur **Nachrichten** – der Sequenzfluss darf eine Poolgrenze nie überqueren.',
      '[2] Annahme und Technik sind Lanes **desselben Pools**. Die Reihenfolge der Schritte zeigt der **Sequenzfluss**, auch über die Lane-Grenze.',
      '[3] Richtig: Die Rechnung geht als Nachricht an den anderen Pool; dort wartet ein Zwischenereignis mit Brief auf sie.',
      '[4] Ein **paralleles** Gateway würde beide Wege gleichzeitig starten. Bei einer Ja/Nein-Frage gilt genau ein Weg → **exklusives** Gateway (X).',
    ],
    muster: {
      breite: 980,
      hoehe: 446,
      rahmen: [
        { typ: 'pool', x: 16, y: 16, w: 948, h: 100, text: 'Kunde' },
        { typ: 'pool', x: 16, y: 160, w: 948, text: 'Werkstatt', lanes: [{ text: 'Annahme', h: 100 }, { text: 'Technik', h: 170 }] },
      ],
      knoten: [
        S('ks', 70, 44, 'Defekt\nbemerkt'),
        A('ka1', 130, 33, 'Reparatur beauftragen'),
        Z('kz', 714, 44, '', { symbol: 'brief' }),
        notiz('kzt', 730, 30, 'Rechnung erhalten', 'middle'),
        A('ka2', 770, 33, 'Rechnung bezahlen'),
        EN('ke', 904, 44, 'bezahlt'),
        S('ws', 174, 194, 'Auftrag\neingegangen', { symbol: 'brief' }),
        A('wa1', 230, 183, 'Auftrag annehmen'),
        A('wt1', 230, 273, 'Fahrzeug prüfen'),
        G('g1', 380, 279, 'x', '', { hervor: true }),
        notiz('g1t', 401, 266, 'Ersatzteil nötig?', 'middle'),
        A('wt2', 450, 353, 'Ersatzteil bestellen'),
        G('g2', 600, 279, 'x'),
        A('wt3', 670, 273, 'Fahrzeug reparieren'),
        A('wa2', 670, 183, 'Rechnung senden'),
        EN('we', 830, 194, 'Auftrag\nerledigt'),
      ],
      kanten: [
        sf('ks', 'ka1'),
        sf('ka1', 'kz'),
        sf('kz', 'ka2'),
        sf('ka2', 'ke'),
        nf('ka1', 'ws', { vonSeite: 'unten', nachSeite: 'oben', text: 'Auftrag', hervor: true, textPos: 0.45 }),
        sf('ws', 'wa1'),
        sf('wa1', 'wt1', { vonSeite: 'unten', nachSeite: 'oben', hervor: true }),
        sf('wt1', 'g1'),
        sf('g1', 'wt2', { vonSeite: 'unten', via: [[401, 380]], nachSeite: 'links', text: 'ja', textPos: 0.3 }),
        sf('g1', 'g2', { text: 'nein' }),
        sf('wt2', 'g2', { vonSeite: 'rechts', via: [[621, 380]], nachSeite: 'unten' }),
        sf('g2', 'wt3'),
        sf('wt3', 'wa2'),
        sf('wa2', 'we'),
        nf('wa2', 'kz', { vonSeite: 'oben', nachSeite: 'unten', text: 'Rechnung', textPos: 0.45 }),
      ],
    },
  },

  // ---------- Zeichnen (AP2) ----------
  {
    id: 'pr-z1',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-3-1',
    titel: 'EPK: Bestellung beim Lieferanten',
    text: 'Zeichne den Ablauf als EPK mit Organisationseinheiten und Informationsobjekten:\n- Der Ablauf beginnt, wenn der **Meldebestand** eines Artikels unterschritten ist.\n- Der **Einkauf** ermittelt den Bestellwert; dazu nutzt er den **Artikelstamm**.\n- Liegt der Bestellwert **unter 500 €**, wird direkt bestellt.\n- Liegt er **bei 500 € oder darüber**, muss die **Abteilungsleitung** die Bestellung erst freigeben.\n- Danach versendet der Einkauf die **Bestellung** (Informationsobjekt) an den Lieferanten. Am Ende ist die Bestellung versendet.',
    muster: {
      breite: 740,
      hoehe: 690,
      knoten: [
        E('e1', 260, 16, 'Meldebestand unterschritten'),
        F('f1', 260, 96, 'Bestellwert ermitteln'),
        O('o1', 60, 99, 'Einkauf'),
        I('i1', 450, 101, 'Artikelstamm'),
        K('k1', 314, 176, 'xor'),
        E('eL', 120, 238, 'Bestellwert unter 500 €'),
        E('eR', 400, 238, 'Bestellwert ab 500 €'),
        F('fR', 400, 318, 'Bestellung freigeben'),
        O('o2', 570, 321, 'Abteilungsleitung'),
        E('eR2', 400, 398, 'Bestellung freigegeben'),
        K('k2', 314, 478, 'xor'),
        F('f2', 260, 540, 'Bestellung versenden'),
        O('o3', 60, 543, 'Einkauf'),
        I('i2', 450, 545, 'Bestellung'),
        E('e4', 260, 620, 'Bestellung versendet'),
      ],
      kanten: [
        fl('e1', 'f1'),
        li('o1', 'f1'),
        li('i1', 'f1'),
        fl('f1', 'k1'),
        abL('k1', 'eL', 190, 192),
        abR('k1', 'eR', 470, 192),
        fl('eR', 'fR'),
        li('fR', 'o2'),
        fl('fR', 'eR2'),
        zuL('eL', 'k2', 190, 494),
        zuR('eR2', 'k2', 470, 494),
        fl('k2', 'f2'),
        li('o3', 'f2'),
        li('i2', 'f2'),
        fl('f2', 'e4'),
      ],
    },
    pruefliste: [
      'Beginnt mit dem Ereignis **„Meldebestand unterschritten"** und endet mit **„Bestellung versendet"**',
      'Ereignisse und Funktionen **wechseln sich ab** – nirgends zwei Funktionen oder zwei Ereignisse direkt hintereinander',
      'Die Entscheidung trifft eine **Funktion** („Bestellwert ermitteln"), erst danach folgt der **XOR**-Konnektor',
      'Nach dem XOR zwei **Ereignisse** als Ergebnis: „unter 500 €" und „ab 500 €"',
      'Nur im Zweig „ab 500 €": Funktion **„Bestellung freigeben"** mit Organisationseinheit **Abteilungsleitung**',
      'Beide Zweige werden mit **XOR** zusammengeführt, bevor „Bestellung versenden" folgt',
      'Organisationseinheit **Einkauf** an „Bestellwert ermitteln" und „Bestellung versenden"',
      'Informationsobjekte **Artikelstamm** und **Bestellung** per Linie an der passenden Funktion',
    ],
    hinweise: 'Den Zweig „unter 500 €" führst du ohne eigene Funktion direkt in den XOR-Konnektor – Ereignis → XOR → Funktion ist erlaubt. Eine eigene Funktion „Bestellung direkt auslösen" mit Ereignis danach ist auch richtig.',
  },
  {
    id: 'pr-z2',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-3-1',
    titel: 'BPMN: Störungsmeldung',
    text: 'Zeichne den Ablauf als BPMN-Diagramm:\n- Ein **Mitarbeiter** meldet dem IT-Support eine Störung (eigener Pool, der Inhalt seines Pools muss nicht gezeigt werden).\n- Im Pool **IT-Support** gibt es die Lanes **1st-Level** und **2nd-Level**.\n- Der 1st-Level legt ein **Ticket** an (Datenobjekt) und analysiert die Störung.\n- Kann der 1st-Level die Störung selbst lösen, behebt er sie. Sonst behebt sie der 2nd-Level.\n- Danach informiert der 1st-Level den Mitarbeiter. Am Ende ist die Störung behoben.',
    muster: {
      breite: 990,
      hoehe: 416,
      rahmen: [
        { typ: 'pool', x: 16, y: 16, w: 958, h: 60, text: 'Mitarbeiter' },
        { typ: 'pool', x: 16, y: 120, w: 958, text: 'IT-Support', lanes: [{ text: '1st-Level', h: 170 }, { text: '2nd-Level', h: 110 }] },
      ],
      knoten: [
        PUNKT('m1', 100, 76),
        PUNKT('m2', 814, 76),
        S('s1', 84, 164, 'Störung\ngemeldet', { symbol: 'brief' }),
        A('a1', 134, 153, 'Ticket anlegen'),
        { id: 'd1', typ: 'datenobjekt', x: 177, y: 222, text: 'Ticket' },
        A('a2', 284, 153, 'Störung analysieren'),
        G('g1', 434, 159, 'x'),
        notiz('g1t', 447, 222, 'selbst lösbar?', 'end'),
        A('a3', 514, 153, 'Störung beheben'),
        A('a4', 514, 318, 'Störung beheben'),
        G('g2', 674, 159, 'x'),
        A('a5', 754, 153, 'Mitarbeiter informieren'),
        EN('e1', 904, 164, 'Störung\nbehoben'),
      ],
      kanten: [
        nf('m1', 's1', { nachSeite: 'oben', text: 'Meldung', textPos: 0.3 }),
        sf('s1', 'a1'),
        df('a1', 'd1'),
        sf('a1', 'a2'),
        sf('a2', 'g1'),
        sf('g1', 'a3', { text: 'ja', textSeite: -1 }),
        sf('g1', 'a4', { vonSeite: 'unten', via: [[455, 345]], nachSeite: 'links', text: 'nein', textPos: 0.3 }),
        sf('a3', 'g2'),
        sf('a4', 'g2', { vonSeite: 'rechts', via: [[695, 345]], nachSeite: 'unten' }),
        sf('g2', 'a5'),
        sf('a5', 'e1'),
        nf('a5', 'm2', { vonSeite: 'oben', text: 'Information', textPos: 0.75 }),
      ],
    },
    pruefliste: [
      'Zwei **Pools**: Mitarbeiter und IT-Support; IT-Support mit den **Lanes** 1st-Level und 2nd-Level',
      'Startereignis (am besten mit Brief) im 1st-Level, ausgelöst durch einen **Nachrichtenfluss** vom Pool Mitarbeiter',
      'Aufgaben **Ticket anlegen** und **Störung analysieren** in der Lane 1st-Level',
      '**Datenobjekt Ticket** mit gepunkteter Linie an „Ticket anlegen"',
      '**Exklusives Gateway** mit Frage („selbst lösbar?") und beschrifteten Ausgängen ja/nein',
      '„Störung beheben" einmal im 1st-Level (ja) und einmal im 2nd-Level (nein)',
      'Beide Wege mit einem **exklusiven Gateway** zusammengeführt, danach „Mitarbeiter informieren"',
      'Innerhalb des Pools nur **Sequenzfluss**; zum Mitarbeiter nur **Nachrichtenfluss**',
      '**Endereignis** (dicker Kreis) am Schluss',
    ],
    hinweise: 'Den Pool „Mitarbeiter" darfst du leer (zugeklappt) zeichnen – Nachrichtenflüsse enden dann an seinem Rand. Das zusammenführende Gateway darfst du weglassen, wenn beide Wege direkt in „Mitarbeiter informieren" münden.',
  },
  {
    id: 'pr-z3',
    art: 'zeichnen',
    raum: ['AP2'],
    sp: 'AP2-2-3-1',
    titel: 'Von der EPK zu BPMN: Wareneingang',
    text: 'Die Vorlage zeigt den Wareneingang als EPK. Zeichne denselben Ablauf als BPMN-Diagramm:\n- Pool **Unternehmen** mit den Lanes **Wareneingang**, **Lager** und **Buchhaltung**. Die Ware lagert das Lager ein, den Eingang bucht die Buchhaltung, alles andere erledigt der Wareneingang.\n- Eine Reklamation geht an den **Lieferanten** (eigener Pool).',
    vorlage: {
      breite: 700,
      hoehe: 590,
      knoten: [
        E('e1', 230, 16, 'Ware angeliefert'),
        F('f1', 230, 96, 'Lieferung prüfen'),
        O('o1', 40, 99, 'Wareneingang'),
        K('k1', 284, 176, 'xor'),
        E('eL', 100, 238, 'Lieferung in Ordnung'),
        E('eR', 380, 238, 'Lieferung mangelhaft'),
        K('kA', 154, 318, 'und'),
        F('fA', 20, 380, 'Ware einlagern'),
        F('fB', 180, 380, 'Eingang buchen'),
        K('kJ', 154, 460, 'und'),
        E('eE', 100, 520, 'Wareneingang abgeschlossen'),
        F('fR', 380, 318, 'Lieferung reklamieren'),
        O('o2', 540, 321, 'Wareneingang'),
        E('eR2', 380, 398, 'Lieferung reklamiert'),
      ],
      kanten: [
        fl('e1', 'f1'),
        li('o1', 'f1'),
        fl('f1', 'k1'),
        abL('k1', 'eL', 170, 192),
        abR('k1', 'eR', 450, 192),
        fl('eL', 'kA'),
        abL('kA', 'fA', 90, 334),
        abR('kA', 'fB', 250, 334),
        zuL('fA', 'kJ', 90, 476),
        zuR('fB', 'kJ', 250, 476),
        fl('kJ', 'eE'),
        fl('eR', 'fR'),
        li('fR', 'o2'),
        fl('fR', 'eR2'),
      ],
    },
    muster: {
      breite: 720,
      hoehe: 490,
      rahmen: [
        { typ: 'pool', x: 16, y: 16, w: 688, h: 60, text: 'Lieferant' },
        { typ: 'pool', x: 16, y: 110, w: 688, text: 'Unternehmen', lanes: [{ text: 'Wareneingang', h: 160 }, { text: 'Lager', h: 100 }, { text: 'Buchhaltung', h: 100 }] },
      ],
      knoten: [
        PUNKT('m1', 460, 76),
        S('s1', 84, 159, 'Ware\nangeliefert'),
        A('a1', 140, 148, 'Lieferung prüfen'),
        G('g1', 300, 154, 'x'),
        notiz('g1t', 312, 136, 'Lieferung in Ordnung?', 'end'),
        A('a2', 400, 148, 'Lieferung reklamieren'),
        EN('e1', 570, 159, 'Lieferung\nreklamiert'),
        G('g2', 300, 299, '+'),
        A('a3', 380, 293, 'Ware einlagern'),
        A('a4', 380, 393, 'Eingang buchen'),
        G('g3', 540, 299, '+'),
        EN('e2', 620, 304, 'Wareneingang\nabgeschlossen'),
      ],
      kanten: [
        sf('s1', 'a1'),
        sf('a1', 'g1'),
        sf('g1', 'a2', { text: 'nein' }),
        sf('a2', 'e1'),
        nf('a2', 'm1', { vonSeite: 'oben', text: 'Reklamation', textPos: 0.75 }),
        sf('g1', 'g2', { vonSeite: 'unten', nachSeite: 'oben', text: 'ja' }),
        sf('g2', 'a3'),
        sf('g2', 'a4', { vonSeite: 'unten', via: [[321, 420]], nachSeite: 'links' }),
        sf('a3', 'g3'),
        sf('a4', 'g3', { vonSeite: 'rechts', via: [[561, 420]], nachSeite: 'unten' }),
        sf('g3', 'e2'),
      ],
    },
    pruefliste: [
      'Pool **Unternehmen** mit drei Lanes, Pool **Lieferant** getrennt daneben oder darüber',
      'Das **Ereignis** „Ware angeliefert" wird zum **Startereignis**, die **Funktionen** werden zu **Aufgaben**',
      'Der **XOR**-Konnektor wird zum **exklusiven Gateway** mit Frage und den Ausgängen ja/nein',
      'Die Ergebnis-Ereignisse „in Ordnung"/„mangelhaft" stehen als **Beschriftung an den Ausgängen** des Gateways',
      'Der **UND**-Konnektor wird zum **parallelen Gateway** (+), zusammengeführt ebenfalls mit +',
      '„Ware einlagern" in der Lane **Lager**, „Eingang buchen" in der Lane **Buchhaltung**',
      '**Nachrichtenfluss** von „Lieferung reklamieren" zum Pool Lieferant',
      'Jeder Weg endet in einem **Endereignis**',
    ],
    hinweise: 'In BPMN brauchst du nicht nach jeder Aufgabe ein Ereignis – die Zwischenzustände der EPK fallen weg oder werden zu Beschriftungen an den Gateway-Ausgängen. Die Organisationseinheiten der EPK werden zu Lanes.',
  },
];

export default { spickzettel, notation, spickzettelAP1, notationAP1, aufgaben };
